//! Fixture parity tests for the MOSS audio tokenizer port.
//!
//! Fixtures live in `testdata/moss_audio_tokenizer/`, regenerated by
//! `tools/gen_moss_fixtures.py` against the pinned mlx-audio commit.
//! Gates: encode codes (exact, with normalized-lookup margins), code
//! length through the interleave/patch stack, and the decoded stereo
//! waveform. A real checkpoint can be pointed at via
//! TURBOSPARK_MOSS_AUDIO_TOKENIZER_MODEL and is skipped when unset.
//! Tests never download.

use std::path::{Path, PathBuf};

use super::{MossAudioTokenizer, MossConfig};
use turbospark_model_io::safetensors::SafetensorsFile;

fn testdata(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata/moss_audio_tokenizer")
        .join(name)
}

fn read_json(name: &str) -> serde_json::Value {
    let text = std::fs::read_to_string(testdata(name)).expect(name);
    serde_json::from_str(&text).expect(name)
}

fn read_npy(name: &str) -> (Vec<usize>, Vec<f32>) {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    assert!(header.contains("<f4"), "{name} must be f32");
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    let data = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (shape, data)
}

/// Codes arrive as int32; the reference's encode_audio returns
/// (frames, nq), rows are frames.
fn read_codes(name: &str) -> Vec<Vec<i32>> {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    assert!(header.contains("<i4"), "{name} must be int32");
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    assert_eq!(shape.len(), 2, "{name} must be [frames, books]");
    let (frames, books) = (shape[0], shape[1]);
    let data: Vec<i32> = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| i32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (0..books)
        .map(|b| (0..frames).map(|t| data[t * books + b]).collect())
        .collect()
}

fn rel_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(a.len(), b.len());
    let max = b.iter().fold(0.0f32, |acc, v| acc.max(v.abs()));
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
        / max
}

fn load_tiny() -> MossAudioTokenizer {
    let config = read_json("tiny_config.json");
    let config = MossConfig::from_json(&config).expect("config");
    let file = SafetensorsFile::open(&testdata("tiny_weights.safetensors")).expect("weights");
    MossAudioTokenizer::load(config, &file).expect("load")
}

#[test]
fn config_parses_modules_and_context() {
    let config = read_json("tiny_config.json");
    let config = MossConfig::from_json(&config).expect("config");
    assert_eq!(config.sample_rate, 8000);
    assert_eq!(config.number_channels, 2);
    assert!(config.enable_channel_interleave);
    assert_eq!(config.downsample_rate, 8);
    assert_eq!(config.quantizer.num_quantizers, 3);
    assert_eq!(config.quantizer.codebook_dim, 4);
    // Encoder: patch (rate 16000 -> 4000), transformer context
    // round(4000 * 0.001) = 4.
    assert_eq!(config.encoder.len(), 2);
    match &config.encoder[1] {
        super::MossModuleConfig::Transformer { context, .. } => assert_eq!(*context, Some(4)),
        other => panic!("expected transformer, got {other:?}"),
    }
    // Decoder transformer runs at the encoder's final rate (4000).
    match &config.decoder[0] {
        super::MossModuleConfig::Transformer { context, .. } => assert_eq!(*context, Some(4)),
        other => panic!("expected transformer, got {other:?}"),
    }
}

#[test]
fn config_refuses_unknown_module() {
    let err = MossConfig::from_json(&serde_json::json!({
        "encoder_kwargs": [{"module_type": "Mystery"}],
    }))
    .unwrap_err();
    assert!(err.to_string().contains("module_type"), "{err}");
}

#[test]
fn encode_codes_match_reference() {
    let model = load_tiny();
    let traces = read_json("traces.json");
    let (_, wave) = read_npy("wave.npy");
    let (codes, code_len) = model.encode(&wave).unwrap();
    let golden = read_codes("codes.npy");
    assert_eq!(codes.len(), golden.len(), "book count");
    for (b, (mine, gold)) in codes.iter().zip(&golden).enumerate() {
        assert_eq!(mine, gold, "book {b}");
    }
    assert_eq!(
        code_len as i64,
        traces["code_len"].as_i64().unwrap(),
        "code length through interleave + patch"
    );
    let margin = traces["lfq_min_margin"].as_f64().unwrap();
    assert!(margin > 1e-4, "lfq margin {margin}");
}

#[test]
fn decode_matches_reference() {
    let model = load_tiny();
    let (decoded_shape, golden) = read_npy("decoded.npy");
    let codes = read_codes("codes.npy");
    let audio = model.decode(&codes).unwrap();
    assert_eq!(
        audio.len(),
        decoded_shape.iter().product::<usize>(),
        "decoded samples * channels"
    );
    let rel = rel_diff(&audio, &golden);
    assert!(rel < 1e-4, "decode rel diff {rel}");
    // Round trip: 40 mono samples -> stereo (40, 2).
    assert_eq!(decoded_shape, vec![40, 2]);
}

#[test]
fn decode_validates_codes() {
    let model = load_tiny();
    let too_many = vec![vec![0i32; 2]; model.config.quantizer.num_quantizers + 1];
    assert!(model.decode(&too_many).is_err());
    let bad = vec![vec![model.config.quantizer.codebook_size as i32; 2]];
    assert!(model.decode(&bad).is_err());
}

/// Real-checkpoint gate; opt-in via TURBOSPARK_MOSS_AUDIO_TOKENIZER_MODEL
/// pointing at a directory with config.json + model.safetensors.
/// Skips when unset.
#[test]
fn real_checkpoint_gate() {
    let Ok(dir) = std::env::var("TURBOSPARK_MOSS_AUDIO_TOKENIZER_MODEL") else {
        eprintln!("skipping: TURBOSPARK_MOSS_AUDIO_TOKENIZER_MODEL not set");
        return;
    };
    let model = MossAudioTokenizer::open(Path::new(&dir)).unwrap();
    let codes: Vec<Vec<i32>> = (0..model.config.quantizer.num_quantizers)
        .map(|b| {
            (0..2)
                .map(|t| ((b * 3 + t) % model.config.quantizer.codebook_size) as i32)
                .collect()
        })
        .collect();
    let audio = model.decode(&codes).unwrap();
    assert!(!audio.is_empty());
    assert!(audio.iter().all(|v| v.is_finite()));
}
