//! Fixture parity tests for the Higgs Audio tokenizer port.
//!
//! Fixtures live in `testdata/higgs_audio/`, regenerated by
//! `tools/gen_higgs_fixtures.py` against the pinned mlx-audio commit
//! (tiny geometry: the reference hardcodes channel ladders and the
//! 1024/256 dims as class/constructor constants, so the generator
//! mirrors the `__init__` bodies at shrunk dims with identical weight
//! keys). Gates: acoustic encode, RVQ encode/decode, full token
//! decode. A real checkpoint can be pointed at via
//! TURBOSPARK_HIGGS_AUDIO_MODEL and is skipped when absent. Tests
//! never download.

use std::path::{Path, PathBuf};

use super::{HiggsAudioConfig, HiggsAudioTokenizer};
use turbospark_model_io::safetensors::SafetensorsFile;

fn testdata(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata/higgs_audio")
        .join(name)
}

fn read_json(name: &str) -> serde_json::Value {
    let text = std::fs::read_to_string(testdata(name)).expect(name);
    serde_json::from_str(&text).expect(name)
}

fn read_npy(name: &str) -> (Vec<usize>, Vec<f32>) {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    assert!(header.contains("<f4"), "{name} must be f32");
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    let data = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (shape, data)
}

/// Codes arrive as int32 (`<i4`), rows = frames, columns = books
/// (the reference stacks codes on the last axis).
fn read_codes(name: &str) -> Vec<Vec<i32>> {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    assert!(header.contains("<i4"), "{name} must be int32");
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    assert_eq!(shape.len(), 2, "{name} must be [T, books]");
    let (t, books) = (shape[0], shape[1]);
    let data: Vec<i32> = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| i32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (0..books)
        .map(|b| (0..t).map(|ti| data[ti * books + b]).collect())
        .collect()
}

fn rel_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(a.len(), b.len());
    let max = b.iter().fold(0.0f32, |acc, v| acc.max(v.abs()));
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
        / max
}

fn load_tiny() -> HiggsAudioTokenizer {
    let config = read_json("tiny_config.json");
    let config = HiggsAudioConfig::from_json(&config).expect("config");
    let file = SafetensorsFile::open(&testdata("tiny_weights.safetensors")).expect("weights");
    HiggsAudioTokenizer::load(config, &file).expect("load")
}

#[test]
fn config_defaults_match_reference() {
    let config = HiggsAudioConfig::from_json(&serde_json::json!({})).unwrap();
    assert_eq!(config.sample_rate, 24_000);
    assert_eq!(config.codebook_size, 1024);
    assert_eq!(config.codebook_dim, 64);
    assert_eq!(config.downsample_factor, 320);
    assert_eq!(config.dac_num_codebooks, 8);
    assert_eq!(config.dac_encoder_ratios, vec![8, 5, 4, 2, 3]);
    assert_eq!(config.dac_encoder_hidden, 64);
    assert_eq!(config.dac_decoder_hidden, 1024);
    assert_eq!(config.quantizer_latent_dim, 1024);
    assert_eq!(config.decoder_input_dim, 256);
    assert_eq!(config.acoustic_hop(), 960);
    assert_eq!(
        config.encoder_channels(),
        vec![64, 128, 256, 512, 1024, 2048]
    );
}

#[test]
fn acoustic_encoder_matches_reference() {
    let model = load_tiny();
    let traces = read_json("traces.json");
    for tag in ["a", "b"] {
        let (_, wave) = read_npy(&format!("{tag}_wave.npy"));
        let (feat_shape, golden) = read_npy(&format!("{tag}_acoustic.npy"));
        let rows = model.encode_acoustic(&wave).unwrap();
        assert_eq!(
            feat_shape,
            vec![
                rows.len() / model.config.decoder_input_dim,
                model.config.decoder_input_dim
            ]
        );
        // The tiny random-weight stack amplifies features to ~6e10
        // (see the generator), where f32 accumulation-order noise is
        // around 1e-5 relative; 1e-4 is the honest gate at that scale.
        let rel = rel_diff(&rows, &golden);
        assert!(rel < 1e-4, "tag {tag} acoustic rel diff {rel}");
        assert_eq!(
            rows.len() / model.config.decoder_input_dim,
            wave.len() / model.config.acoustic_hop()
        );
        let _ = traces;
    }
}

#[test]
fn rvq_round_trip_matches_reference() {
    let model = load_tiny();
    let traces = read_json("traces.json");
    let (z_shape, z) = read_npy("z_rows.npy");
    let frames = z_shape[0];
    let codes = model.rvq_encode(&z, frames).unwrap();
    let golden_codes = read_codes("codes.npy");
    assert_eq!(codes.len(), golden_codes.len());
    for (b, (mine, golden)) in codes.iter().zip(&golden_codes).enumerate() {
        assert_eq!(mine, golden, "book {b}");
    }
    let margin = traces["rvq_min_margin"].as_f64().unwrap();
    assert!(margin > 1e-4, "rvq margin {margin}");

    let (_, golden_recon) = read_npy("z_recon.npy");
    let recon = model.rvq_decode_rows(&codes).unwrap();
    let rel = rel_diff(&recon, &golden_recon);
    assert!(rel < 1e-5, "rvq recon rel diff {rel}");
}

#[test]
fn token_decode_matches_reference() {
    let model = load_tiny();
    let (_, golden) = read_npy("decoded.npy");
    let codes = read_codes("codes.npy");
    let wav = model.decode_tokens(&codes).unwrap();
    assert_eq!(wav.len(), golden.len());
    // Same amplification story as the acoustic gate: the decoded
    // waveform peaks near 2e4 and f32 order noise lands around 3e-5.
    let rel = rel_diff(&wav, &golden);
    assert!(rel < 1e-4, "decode rel diff {rel}");
    assert_eq!(wav.len(), codes[0].len() * model.config.acoustic_hop());
}

#[test]
fn decode_validates_codes() {
    let model = load_tiny();
    let too_many = vec![vec![0i32; 2]; model.config.dac_num_codebooks + 1];
    assert!(model.decode_tokens(&too_many).is_err());
    let bad = vec![vec![model.config.codebook_size as i32; 2]];
    assert!(model.decode_tokens(&bad).is_err());
}

/// Real-checkpoint gate; opt-in via TURBOSPARK_HIGGS_AUDIO_MODEL
/// pointing at a directory with config.json + model.safetensors.
/// Skips when unset.
#[test]
fn real_checkpoint_gate() {
    let Ok(dir) = std::env::var("TURBOSPARK_HIGGS_AUDIO_MODEL") else {
        eprintln!("skipping: TURBOSPARK_HIGGS_AUDIO_MODEL not set");
        return;
    };
    let model = HiggsAudioTokenizer::open(Path::new(&dir)).unwrap();
    let codes: Vec<Vec<i32>> = (0..model.config.dac_num_codebooks)
        .map(|b| {
            (0..4)
                .map(|t| ((b + t) % model.config.codebook_size) as i32)
                .collect()
        })
        .collect();
    let wav = model.decode_tokens(&codes).unwrap();
    assert_eq!(wav.len(), 4 * model.config.acoustic_hop());
    assert!(wav.iter().all(|v| v.is_finite()));
}
