//! Fixture parity tests for the Descript Audio Codec port.
//!
//! Fixtures live in `testdata/descript/`, regenerated by
//! `tools/gen_dac_fixtures.py` against the pinned mlx-audio commit.
//! Codes are exact-equality gates protected by recorded VQ distance
//! margins; tensors are float-tolerant (different matmul reduction
//! orders). No real DAC checkpoint ships a fixture; a local checkpoint
//! directory can be pointed at via TURBOSPARK_DAC_MODEL and is skipped
//! when absent. Tests never download.

use std::path::{Path, PathBuf};

use super::{Dac, DacConfig};
use turbospark_model_io::safetensors::SafetensorsFile;

fn testdata(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata/descript")
        .join(name)
}

fn read_json(name: &str) -> serde_json::Value {
    let text = std::fs::read_to_string(testdata(name)).expect(name);
    serde_json::from_str(&text).expect(name)
}

/// Read a little-endian f32 .npy (the shared testdata convention).
fn read_npy(name: &str) -> (Vec<usize>, Vec<f32>) {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    let data = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (shape, data)
}

fn floats(value: &serde_json::Value) -> Vec<f32> {
    value
        .as_array()
        .expect("float array")
        .iter()
        .map(|v| v.as_f64().expect("f64") as f32)
        .collect()
}

fn code_levels(value: &serde_json::Value) -> Vec<Vec<i32>> {
    value
        .as_array()
        .expect("levels")
        .iter()
        .map(|level| {
            level
                .as_array()
                .expect("level")
                .iter()
                .map(|v| v.as_i64().expect("i64") as i32)
                .collect()
        })
        .collect()
}

fn max_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(
        a.len(),
        b.len(),
        "length mismatch: {} vs {}",
        a.len(),
        b.len()
    );
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
}

fn load_tiny() -> Dac {
    let config = read_json("tiny_config.json");
    let config = DacConfig::from_json(&config).expect("config parses");
    let file = SafetensorsFile::open(&testdata("tiny_weights.safetensors")).expect("weights open");
    Dac::load(config, &file).expect("load")
}

#[test]
fn config_defaults_match_reference() {
    let config = DacConfig::from_json(&serde_json::json!({})).unwrap();
    assert_eq!(config.encoder_dim, 64);
    assert_eq!(config.encoder_rates, vec![2, 4, 5, 8]);
    assert_eq!(config.latent_dim, 64 * 16);
    assert_eq!(config.decoder_dim, 1536);
    assert_eq!(config.decoder_rates, vec![8, 5, 4, 2]);
    assert_eq!(config.n_codebooks, 32);
    assert_eq!(config.codebook_size, 1024);
    assert_eq!(config.sample_rate, 44100);
    assert_eq!(config.hop_length(), 320);
    // Scalar codebook_dim expands to one width per codebook.
    assert!(config.codebook_dims.iter().all(|&d| d == 8));
}

#[test]
fn tiny_end_to_end_matches_reference() {
    let model = load_tiny();
    let traces = read_json("traces.json");
    assert_eq!(model.delay as i64, traces["delay"].as_i64().unwrap());

    for (tag, zq_file, hat_file, fc_file) in [
        ("a", "a_zq.npy", "a_audio_hat.npy", "a_audio_from_codes.npy"),
        ("b", "b_zq.npy", "b_audio_hat.npy", "b_audio_from_codes.npy"),
    ] {
        let wave = floats(&traces[format!("{tag}_wave").as_str()]);
        let padded = model.padded_len(wave.len());
        assert_eq!(
            padded as i64,
            traces[format!("{tag}_padded_len").as_str()]
                .as_i64()
                .unwrap()
        );

        let (codes, z_q) = model
            .encode_partial(&wave, model.config.n_codebooks)
            .unwrap();
        let golden_codes = code_levels(&traces[format!("{tag}_codes").as_str()]);
        assert_eq!(codes.len(), golden_codes.len());
        for (got, want) in codes.iter().zip(&golden_codes) {
            assert_eq!(got, want, "{tag} code level mismatch");
        }

        // Level-0 margins keep the exact-index gate honest.
        let best = traces[format!("{tag}_vq_margins")]["best"]
            .as_array()
            .unwrap();
        let second = traces[format!("{tag}_vq_margins")]["second"]
            .as_array()
            .unwrap();
        for (b, s) in best.iter().zip(second) {
            let b = b.as_f64().unwrap();
            let s = s.as_f64().unwrap();
            assert!(s - b > 1e-5, "{tag} margin {s} - {b} too small");
        }

        let (_, golden_zq) = read_npy(zq_file);
        assert_eq!(z_q.len(), golden_zq.len());
        assert!(max_diff(&z_q, &golden_zq) < 1e-4, "{tag} z_q diff");

        let audio_hat = model.decode_latents(&golden_zq);
        let (_, golden_hat) = read_npy(hat_file);
        assert_eq!(audio_hat.len(), golden_hat.len());
        assert!(max_diff(&audio_hat, &golden_hat) < 1e-4, "{tag} decode");

        let audio_fc = model.decode_codes(&codes).unwrap();
        let (_, golden_fc) = read_npy(fc_file);
        assert_eq!(audio_fc.len(), golden_fc.len());
        assert!(max_diff(&audio_fc, &golden_fc) < 1e-4, "{tag} from codes");
    }
}

#[test]
fn compress_decompress_gain_round_trip() {
    let model = load_tiny();
    let traces = read_json("traces.json");
    let (_, wave) = read_npy("compress_wave.npy");
    let (codes, input_db) = model.compress(&wave, None).unwrap();
    assert!((input_db - traces["compress_input_db"].as_f64().unwrap() as f32).abs() < 1e-4);
    let recons = model.decompress(&codes, input_db).unwrap();
    let (_, golden) = read_npy("compress_recons.npy");
    assert_eq!(recons.len(), golden.len());
    assert!(max_diff(&recons, &golden) < 1e-4);
}

/// Real-checkpoint gate; opt-in via TURBOSPARK_DAC_MODEL pointing at a
/// directory with config.json + model.safetensors. Skips when unset.
#[test]
fn real_checkpoint_gate() {
    let Ok(dir) = std::env::var("TURBOSPARK_DAC_MODEL") else {
        eprintln!("skipping: TURBOSPARK_DAC_MODEL not set");
        return;
    };
    let model = Dac::open(std::path::Path::new(&dir)).unwrap();
    let (_, wave) = read_npy("compress_wave.npy");
    let codes = model.encode(&wave).unwrap();
    let audio = model.decode_codes(&codes).unwrap();
    assert_eq!(audio.len(), model.padded_len(wave.len()));
    assert!(audio.iter().all(|v| v.is_finite()));
    assert!(audio.iter().all(|v| v.abs() <= 1.0 + 1e-4));
}
