use crate::arch_config::{
    ArchConfig, CompressedAttentionConfig, HyperConnectionConfig, LinearAttentionConfig,
    ModelFamily, PleConfig, RopeScalingConfig, VisionConfig,
};

/// Witnessed MiniMax-M2 trunk; see docs/MINIMAX_M2_PHASE0.md.
pub fn minimax_m2() -> ArchConfig {
    ArchConfig {
        hidden_size: 3072,
        intermediate_size: 1536,
        moe_intermediate_size: 1536,
        num_heads: 48,
        num_kv_heads: 8,
        num_full_kv_heads: 8,
        head_dim: 128,
        full_head_dim: 128,
        vocab_size: 200_064,
        sliding_window: 0,
        final_logit_softcap: 0.0,
        rope_theta: 5_000_000.0,
        full_rope_theta: 5_000_000.0,
        partial_rotary_factor: 0.5,
        num_layers: 62,
        num_experts: 256,
        top_k_experts: 8,
        tie_word_embeddings: false,
        attention_k_eq_v: false,
        full_attention_layer_mask: vec![1u8; 62],
        hidden_activation: "silu".to_string(),
        family: ModelFamily::MiniMaxM2,
        attn_output_gate: false,
        attention_scale: 0.088_388_347_648_318_45,
        embedding_scaled_by_sqrt_hidden: false,
        router_scaled: false,
        ffn_sandwich_norms: false,
        shared_expert_gated: false,
        rope_neox_subdim: true,
        linear_attention: LinearAttentionConfig::NONE,
        compressed_attention: CompressedAttentionConfig::NONE,
        hyper_connections: HyperConnectionConfig::NONE,
        num_hash_routed_layers: 0,
        router_scoring_func: "sigmoid".to_string(),
        routed_scaling_factor: 1.0,
        swiglu_limit: 0.0,
        rope_scaling: RopeScalingConfig::NONE,
        vision: VisionConfig::NONE,
        ple: PleConfig::NONE,
    }
}
