//! Parity and regression tests for S3 speech tokenizers (v1 and v2).
//!
//! Pinned fixtures reside in `testdata/s3/`, generated by
//! `tools/gen_s3_fixtures.py` against mlx-audio 0.5.7 commit
//! `e1b19b9054bf163f5d812221a54fcc346f1890e9`.

use std::path::{Path, PathBuf};

use turbospark_model_io::safetensors::SafetensorsFile;

use super::{log_mel_spectrogram, S3Config, S3TokenizerV1, S3TokenizerV2, V1_25HZ};

fn testdata(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata/s3")
        .join(name)
}

fn read_json(name: &str) -> serde_json::Value {
    let text = std::fs::read_to_string(testdata(name)).expect(name);
    serde_json::from_str(&text).expect(name)
}

fn read_npy(name: &str) -> (Vec<usize>, Vec<f32>) {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    let data = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (shape, data)
}

fn read_npy_i32(name: &str) -> (Vec<usize>, Vec<i32>) {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    let data = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| i32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (shape, data)
}

fn max_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(
        a.len(),
        b.len(),
        "length mismatch: {} vs {}",
        a.len(),
        b.len()
    );
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
}

#[test]
fn config_defaults_match_reference() {
    let v1 = S3Config::v1();
    assert_eq!(v1.n_mels, 128);
    assert_eq!(v1.n_audio_ctx, 1500);
    assert_eq!(v1.n_audio_state, 1280);
    assert_eq!(v1.n_audio_head, 20);
    assert_eq!(v1.n_audio_layer, 6);
    assert_eq!(v1.n_codebook_size, 4096);

    let v2 = S3Config::v2();
    assert_eq!(v2.n_mels, 128);
    assert_eq!(v2.n_audio_ctx, 1500);
    assert_eq!(v2.n_audio_state, 1280);
    assert_eq!(v2.n_audio_head, 20);
    assert_eq!(v2.n_audio_layer, 6);
    assert_eq!(v2.n_codebook_size, 6561);
}

#[test]
fn v1_tiny_end_to_end_matches_reference() {
    let config_json = read_json("tiny_v1_config.json");
    let config = S3Config::from_json_with_defaults(&config_json, S3Config::v1()).unwrap();
    let file = SafetensorsFile::open(&testdata("tiny_v1_weights.safetensors")).unwrap();
    let tok = S3TokenizerV1::load(V1_25HZ, config, &file).unwrap();
    let traces = read_json("traces.json");

    // Case A
    let (mel_shape, mel_a) = read_npy("v1_a_mel.npy");
    let mel_len_a = traces["v1_a_mel_len"].as_u64().unwrap() as usize;
    assert_eq!(mel_shape[1], mel_len_a);
    let (codes_a, out_len_a) = tok.quantize(&mel_a, mel_len_a).unwrap();
    assert_eq!(
        out_len_a,
        traces["v1_a_code_len"].as_u64().unwrap() as usize
    );
    let expected_codes_a: Vec<i32> = traces["v1_a_code"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_i64().unwrap() as i32)
        .collect();
    assert_eq!(codes_a, expected_codes_a);

    // Dequantize A
    let deq_a = tok.dequantize(&codes_a).unwrap();
    let (_, ref_deq_a) = read_npy("v1_a_dequant.npy");
    let diff_a = max_diff(&deq_a, &ref_deq_a);
    assert!(diff_a < 1e-5, "v1 dequant A difference {diff_a}");

    // Case B
    let (mel_shape_b, mel_b) = read_npy("v1_b_mel.npy");
    let mel_len_b = traces["v1_b_mel_len"].as_u64().unwrap() as usize;
    assert_eq!(mel_shape_b[1], mel_len_b);
    let (codes_b, out_len_b) = tok.quantize(&mel_b, mel_len_b).unwrap();
    assert_eq!(
        out_len_b,
        traces["v1_b_code_len"].as_u64().unwrap() as usize
    );
    let expected_codes_b: Vec<i32> = traces["v1_b_code"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_i64().unwrap() as i32)
        .collect();
    assert_eq!(codes_b, expected_codes_b);

    // Dequantize B
    let deq_b = tok.dequantize(&codes_b).unwrap();
    let (_, ref_deq_b) = read_npy("v1_b_dequant.npy");
    let diff_b = max_diff(&deq_b, &ref_deq_b);
    assert!(diff_b < 1e-5, "v1 dequant B difference {diff_b}");
}

#[test]
fn v1_50hz_stride_matches_reference() {
    let config_json = read_json("tiny_v1_config.json");
    let config = S3Config::from_json_with_defaults(&config_json, S3Config::v1()).unwrap();
    let file = SafetensorsFile::open(&testdata("tiny_v1_weights.safetensors")).unwrap();
    let tok = S3TokenizerV1::load("speech_tokenizer_v1", config, &file).unwrap();
    let traces = read_json("traces.json");

    let (_, mel_a) = read_npy("v1_a_mel.npy");
    let (codes, out_len) = tok.quantize(&mel_a, 40).unwrap();
    assert_eq!(
        out_len,
        traces["v1_50hz_code_len"].as_u64().unwrap() as usize
    );
    let expected_codes: Vec<i32> = traces["v1_50hz_code"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_i64().unwrap() as i32)
        .collect();
    assert_eq!(codes, expected_codes);
}

#[test]
fn v2_tiny_end_to_end_matches_reference() {
    let config_json = read_json("tiny_v2_config.json");
    let config = S3Config::from_json_with_defaults(&config_json, S3Config::v2()).unwrap();
    let file = SafetensorsFile::open(&testdata("tiny_v2_weights.safetensors")).unwrap();
    let tok = S3TokenizerV2::load(config, &file).unwrap();
    let traces = read_json("traces.json");

    // Case A
    let (_, mel_a) = read_npy("v2_a_mel.npy");
    let mel_len_a = traces["v2_a_mel_len"].as_u64().unwrap() as usize;
    let (codes_a, out_len_a) = tok.quantize(&mel_a, mel_len_a).unwrap();
    assert_eq!(
        out_len_a,
        traces["v2_a_code_len"].as_u64().unwrap() as usize
    );
    let expected_codes_a: Vec<i32> = traces["v2_a_code"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_i64().unwrap() as i32)
        .collect();
    assert_eq!(codes_a, expected_codes_a);

    // Case B
    let (_, mel_b) = read_npy("v2_b_mel.npy");
    let mel_len_b = traces["v2_b_mel_len"].as_u64().unwrap() as usize;
    let (codes_b, out_len_b) = tok.quantize(&mel_b, mel_len_b).unwrap();
    assert_eq!(
        out_len_b,
        traces["v2_b_code_len"].as_u64().unwrap() as usize
    );
    let expected_codes_b: Vec<i32> = traces["v2_b_code"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_i64().unwrap() as i32)
        .collect();
    assert_eq!(codes_b, expected_codes_b);
}

#[test]
fn v2_long_sliding_window_matches_reference() {
    let config_json = read_json("tiny_v2_config.json");
    let config = S3Config::from_json_with_defaults(&config_json, S3Config::v2()).unwrap();
    let file = SafetensorsFile::open(&testdata("tiny_v2_weights.safetensors")).unwrap();
    let tok = S3TokenizerV2::load(config, &file).unwrap();
    let traces = read_json("traces.json");

    let (_, mel_long) = read_npy("v2_long_mel.npy");
    let mel_len = traces["v2_long_mel_len"].as_u64().unwrap() as usize;
    let (codes, out_len) = tok.quantize(&mel_long, mel_len).unwrap();
    assert_eq!(
        out_len,
        traces["v2_long_code_len"].as_u64().unwrap() as usize
    );
    let (_, ref_codes) = read_npy_i32("v2_long_code.npy");
    for (i, (&a, &b)) in codes.iter().zip(ref_codes.iter()).enumerate() {
        if a != b {
            panic!(
                "Mismatch at index {i}: got {a}, expected {b}, len={}",
                codes.len()
            );
        }
    }
    assert_eq!(codes, ref_codes);
}

#[test]
fn log_mel_spectrogram_matches_reference() {
    let (_, wave) = read_npy("mel_wave.npy");
    let frames = log_mel_spectrogram(&wave, 128).unwrap();
    let traces = read_json("traces.json");
    let expected_shape: Vec<usize> = traces["mel_shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    // frames is [T, n_mels], reference is [n_mels, T]
    assert_eq!(frames.len(), expected_shape[1]);
    assert_eq!(frames[0].len(), expected_shape[0]);

    let (_, ref_spec) = read_npy("mel_golden.npy");
    let n_mels = expected_shape[0];
    let n_frames = expected_shape[1];
    let mut flat = vec![0.0f32; n_mels * n_frames];
    for t in 0..n_frames {
        for m in 0..n_mels {
            flat[m * n_frames + t] = frames[t][m];
        }
    }
    let diff = max_diff(&flat, &ref_spec);
    assert!(diff < 1e-4, "log-mel spectrogram difference {diff}");
}

#[test]
#[ignore = "requires real S3 checkpoint in TURBOSPARK_S3_MODEL_DIR"]
fn real_checkpoint_gate() {
    let dir = match std::env::var("TURBOSPARK_S3_MODEL_DIR") {
        Ok(dir) => PathBuf::from(dir),
        Err(_) => return,
    };
    let tok = S3TokenizerV2::open(&dir).expect("opens real checkpoint");
    assert_eq!(tok.config.n_codebook_size, 6561);
}
