//! Env-gated FP16 overflow capture for the vision tower's residual stream
//! (`MFERENCE_VISION_OVERFLOW=/path.json`, ROADMAP M-V9).
//!
//! `docs/VISION_PHASE0.md` item 3 measured the extreme page's peak
//! activation at 13.8% of FP16's 65,504 ceiling (block 26, a 7.3x margin),
//! arriving as a STEP between blocks 8->9 and 25->26 rather than a slope --
//! so a differently-shaped future input is not guaranteed to stay under it.
//! The repack side already refuses an overflowing WEIGHT at install
//! (`crates/repack/src/gemma4_checkpoint/narrow.rs:209`); nothing checked
//! ACTIVATIONS until this file. Diagnostic only, never on by default,
//! following `resid_capture.rs` / `ffn_hist.rs`'s house pattern: zero cost
//! and zero readback when the env var is unset, so generated bytes are
//! byte-identical with this on or off (a readback cannot change what it
//! reads).
//!
//! # Where it hooks
//!
//! After every block's `pass.commit_and_wait()` in
//! `VisionTower::run_inner`, reading back `scratch.x` -- the buffer the
//! Phase 0 probe measured the block 8->9 and 25->26 jumps on.
//!
//! # Two outcomes, not one
//!
//! A non-finite value fails LOUDLY and IMMEDIATELY, naming the image and
//! block: this is AGENTS.md Gotcha 60's exact failure mode (an overflow
//! presents as NaN downstream, i.e. as anything but an overflow), and the
//! whole point of the capture is to say "this became non-finite at block
//! N" instead of letting it flow into a plausible-looking wrong answer.
//! A FINITE value past [`WARN_FRACTION`] of FP16's ceiling is a loud
//! `eprintln!`, not a failure -- crossing headroom on a page shape the
//! Phase 0 probe never measured is informative, not necessarily wrong.
//!
//! # Output
//!
//! A small JSON file on drop: per (image, block) peak absmax, following
//! `resid_capture.rs`'s convention of writing on `Drop` rather than per
//! call. No sidecar needed -- these are scalars, not tensors.

use crate::real_forward_types::RealForwardError;

/// FP16's largest finite magnitude (AGENTS.md Gotcha 60).
const FP16_MAX: f32 = 65_504.0;

/// Fraction of [`FP16_MAX`] that triggers a loud, non-fatal warning.
/// `docs/VISION_PHASE0.md`'s extreme page sits at 13.8%; this is set well
/// above that so the warning is reserved for a page actually approaching
/// the ceiling rather than firing on every ordinary run.
const WARN_FRACTION: f32 = 0.5;

struct BlockPeak {
    image: usize,
    block: usize,
    absmax: f32,
}

/// The env-gated capture. `from_env` returns `None` (and callers dispatch
/// no readback at all) whenever `MFERENCE_VISION_OVERFLOW` is unset.
pub(crate) struct VisionOverflowCapture {
    path: std::path::PathBuf,
    image: usize,
    peaks: Vec<BlockPeak>,
}

impl VisionOverflowCapture {
    /// `Some` only when `MFERENCE_VISION_OVERFLOW` names an output path.
    pub(crate) fn from_env() -> Option<Self> {
        let path = std::env::var_os("MFERENCE_VISION_OVERFLOW")?;
        Some(Self {
            path: path.into(),
            image: 0,
            peaks: Vec::new(),
        })
    }

    /// Called once per `run_inner`, before its block loop -- advances the
    /// image counter the JSON report keys on.
    pub(crate) fn note_image_start(&mut self) {
        self.image += 1;
    }

    /// Read `x` back and check it for this block. `x` is the buffer
    /// `docs/VISION_PHASE0.md` measured the block 8->9 and 25->26 jumps on;
    /// `count` is `seq * hidden`.
    pub(crate) fn check_block(
        &mut self,
        block: usize,
        x: &gpu::MetalBuffer,
        count: usize,
    ) -> Result<(), RealForwardError> {
        let values = gpu::read_buffer_f16(x, 0, count);
        let mut absmax = 0.0f32;
        for v in &values {
            let f = v.to_f32();
            if !f.is_finite() {
                return Err(RealForwardError::Unsupported(format!(
                    "vision overflow capture: image {}, block {block}: a non-finite value \
                     reached the residual stream (AGENTS.md Gotcha 60 -- this is what an FP16 \
                     overflow looks like downstream, not a NaN from nowhere)",
                    self.image
                )));
            }
            absmax = absmax.max(f.abs());
        }
        if absmax > WARN_FRACTION * FP16_MAX {
            eprintln!(
                "[vision-overflow] image {}, block {block}: absmax {absmax:.1} is {:.1}% of \
                 FP16's {FP16_MAX} ceiling",
                self.image,
                100.0 * absmax / FP16_MAX
            );
        }
        self.peaks.push(BlockPeak {
            image: self.image,
            block,
            absmax,
        });
        Ok(())
    }

    fn report_json(&self) -> String {
        let mut out = String::new();
        out.push_str(&format!(
            "{{\n  \"fp16_max\": {FP16_MAX},\n  \"warn_fraction\": {WARN_FRACTION},\n  \
             \"peaks\": [\n"
        ));
        for (i, p) in self.peaks.iter().enumerate() {
            if i > 0 {
                out.push_str(",\n");
            }
            out.push_str(&format!(
                "    {{\"image\": {}, \"block\": {}, \"absmax\": {}}}",
                p.image, p.block, p.absmax
            ));
        }
        out.push_str("\n  ]\n}\n");
        out
    }
}

impl Drop for VisionOverflowCapture {
    fn drop(&mut self) {
        if self.peaks.is_empty() {
            eprintln!(
                "[vision-overflow] no block ran; wrote nothing to {}",
                self.path.display()
            );
            return;
        }
        match std::fs::write(&self.path, self.report_json()) {
            Ok(()) => eprintln!(
                "[vision-overflow] wrote {} block reading(s) to {}",
                self.peaks.len(),
                self.path.display()
            ),
            Err(e) => eprintln!(
                "[vision-overflow] FAILED writing {}: {e}",
                self.path.display()
            ),
        }
    }
}
