//! Fixture parity tests for the StepAudio2 token-to-wav port.
//!
//! Fixtures live in `testdata/stepaudio2/`, regenerated by
//! `tools/gen_stepaudio2_fixtures.py` against the pinned mlx-audio
//! commit. Gates: the kaldi fbank, CAMPPlus embedding, prompt mel and
//! length-matched prompt_feat, the flow output mel, the HiFT f0, and
//! the HiFT / end-to-end waveforms (pre-clip and clipped). The HiFT
//! sine-generator randomness is fixture-provided. The tiny flow model
//! uses a reduced geometry; the HiFT vocoder and CAMPPlus encoder keep
//! the full reference structure. A real checkpoint can be pointed at
//! via TURBOSPARK_STEPAUDIO2_MODEL and is skipped when absent. Tests
//! never download.
//!
//! Scale note: the CAMPPlus fixture amplifies random weights through
//! its 50+ conv layers to ~1e6 magnitudes, where f32 order noise is
//! ~1e-5 relative, so its gate is the honest 1e-3; the other stages
//! hold 1e-4 or tighter.

use std::path::{Path, PathBuf};

use super::hift::SineDraws;
use super::{campplus::kaldi_fbank, StepAudio2Token2Wav};
use turbospark_model_io::safetensors::SafetensorsFile;

fn testdata(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata/stepaudio2")
        .join(name)
}

fn read_json(name: &str) -> serde_json::Value {
    let text = std::fs::read_to_string(testdata(name)).expect(name);
    serde_json::from_str(&text).expect(name)
}

fn read_npy(name: &str) -> (Vec<usize>, Vec<f32>) {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    assert!(header.contains("<f4"), "{name} must be f32");
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    let data = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (shape, data)
}

fn read_i32_npy(name: &str) -> Vec<i32> {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    assert!(header.contains("<i4"), "{name} must be int32");
    bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| i32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect()
}

fn rel_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(a.len(), b.len());
    let max = b.iter().fold(0.0f32, |acc, v| acc.max(v.abs()));
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
        / max
}

fn assert_close(a: &[f32], b: &[f32], gate: f32, what: &str) {
    let rel = rel_diff(a, b);
    assert!(rel < gate, "{what} rel diff {rel} (gate {gate})");
}

fn load_model() -> StepAudio2Token2Wav {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("testdata/stepaudio2");
    StepAudio2Token2Wav::open(&dir).expect("load tiny stepaudio2")
}

/// The recorded sine-generator randomness as the Rust port takes it.
fn load_draws(t_wav: usize) -> SineDraws {
    let (_, rand_ini) = read_npy("sine_rand_ini.npy");
    let (noise_shape, sine_noise) = read_npy("sine_noise.npy");
    assert_eq!(rand_ini.len(), 9);
    assert_eq!(noise_shape.last().copied(), Some(t_wav));
    SineDraws {
        rand_ini,
        sine_noise,
    }
}

#[test]
fn config_defaults_match_reference() {
    let config = super::StepAudio2Config::from_json(&serde_json::json!({})).unwrap();
    assert_eq!(config.input_size, 512);
    assert_eq!(config.output_size, 80);
    assert_eq!(config.spk_embed_dim, 192);
    assert_eq!(config.vocab_size, 6561);
    assert_eq!(config.attention_heads, 8);
    assert_eq!(config.linear_units, 2048);
    assert_eq!(config.num_blocks, 6);
    assert_eq!(config.num_up_blocks, 4);
    assert_eq!(config.up_stride, 2);
    assert_eq!(config.pre_lookahead_len, 3);
    assert_eq!(config.dit_depth, 16);
    assert_eq!(config.dit_hidden, 512);
    assert_eq!(config.dit_heads, 8);
    assert_eq!(config.dit_head_dim, 64);
    assert_eq!(config.dit_mlp_ratio, 4.0);
    assert_eq!(config.inference_cfg_rate, 0.7);
}

#[test]
fn tiny_config_loads_full_pipeline() {
    let model = load_model();
    let tiny = read_json("tiny_config.json");
    // The flow uses the tiny geometry; up_rate comes from up_stride.
    assert_eq!(
        model.config.input_size,
        tiny["input_size"].as_u64().unwrap() as usize
    );
    assert_eq!(
        model.config.dit_depth,
        tiny["dit_depth"].as_u64().unwrap() as usize
    );
    assert_eq!(model.flow.up_rate(), 2);
    assert_eq!(model.config.output_size, 80);
    assert_eq!(model.config.spk_embed_dim, 192);
    // The full-geometry submodels are present.
    assert!(model.campplus.is_some());
    let (_, mel) = read_npy("flow_mel.npy");
    assert_eq!(mel.len(), 16 * 80);
}

#[test]
fn kaldi_fbank_matches_reference() {
    let (_, audio) = read_npy("audio_16k.npy");
    let (golden_shape, golden) = read_npy("campplus_fbank.npy");
    let fbank = kaldi_fbank(&audio).unwrap();
    assert_eq!(fbank.len(), golden_shape[0]);
    assert_eq!(fbank[0].len(), golden_shape[1]);
    let flat: Vec<f32> = fbank.into_iter().flatten().collect();
    assert_close(&flat, &golden, 1e-5, "kaldi fbank");
}

#[test]
fn campplus_embedding_matches_reference() {
    let model = load_model();
    let campplus = model.campplus.as_ref().unwrap();
    let (_, audio) = read_npy("audio_16k.npy");
    let (_, golden) = read_npy("embedding.npy");
    let embedding = campplus.inference(&audio).unwrap();
    assert_eq!(embedding.len(), golden.len());
    // Random-weight amplification through the CAM stack makes the
    // embedding ~1e6; the honest relative gate follows the scale.
    assert_close(&embedding, &golden, 1e-3, "campplus embedding");
}

#[test]
fn chatterbox_prompt_mel_matches_reference() {
    let (_, audio) = read_npy("audio_24k.npy");
    let (golden_shape, golden) = read_npy("prompt_mel.npy");
    let mel = super::chatterbox_mel(&audio, 80).unwrap();
    assert_eq!(mel.len(), golden_shape[0]);
    assert_eq!(mel[0].len(), golden_shape[1]);
    let flat: Vec<f32> = mel.into_iter().flatten().collect();
    assert_close(&flat, &golden, 1e-4, "chatterbox prompt mel");
}

#[test]
fn prepare_prompt_matches_reference() {
    let model = load_model();
    let (_, audio_24k) = read_npy("audio_24k.npy");
    let (_, embedding) = read_npy("embedding.npy");
    let prompt_tokens = read_i32_npy("prompt_tokens.npy");
    let (_, golden_feat) = read_npy("prompt_feat.npy");
    let prompt = model
        .prepare_prompt(&[0.0; 400], &audio_24k, &prompt_tokens, Some(embedding))
        .unwrap();
    assert_eq!(prompt.prompt_feat.len(), golden_feat.len());
    assert_close(&prompt.prompt_feat, &golden_feat, 1e-4, "prompt_feat");
}

#[test]
fn flow_mel_matches_reference() {
    let mut model = load_model();
    let prompt_tokens = read_i32_npy("prompt_tokens.npy");
    let gen_tokens = read_i32_npy("gen_tokens.npy");
    let (_, embedding) = read_npy("embedding.npy");
    let (_, prompt_feat) = read_npy("prompt_feat.npy");
    let (_, golden) = read_npy("flow_mel.npy");
    let mel = model
        .flow
        .infer(&gen_tokens, &prompt_tokens, &prompt_feat, &embedding, 10)
        .unwrap();
    assert_eq!(mel.len(), golden.len());
    assert_close(&mel, &golden, 1e-4, "flow mel");
}

#[test]
fn hift_f0_matches_reference() {
    let model = load_model();
    let (_, mel) = read_npy("flow_mel.npy");
    let (_, golden) = read_npy("f0.npy");
    let f0 = model.hift.predict_f0(&mel).unwrap();
    assert_eq!(f0.len(), golden.len());
    assert_close(&f0, &golden, 1e-4, "f0");
}

#[test]
fn hift_wav_matches_reference() {
    let model = load_model();
    let (_, mel) = read_npy("flow_mel.npy");
    let (_, golden_raw) = read_npy("hift_wav_raw.npy");
    let (_, golden) = read_npy("hift_wav.npy");
    let traces = read_json("traces.json");
    let draws = load_draws(traces["hift_wav_len"].as_u64().unwrap() as usize);
    let wav = model.hift.infer(&mel, Some(&draws)).unwrap();
    assert_eq!(wav.len(), golden.len());
    // The pre-clip waveform is the sensitive gate; clipping folds
    // saturated samples onto the bound.
    assert_close(&wav, &golden_raw, 1e-3, "hift raw wav");
    let clipped: Vec<f32> = wav.iter().map(|v| v.clamp(-0.99, 0.99)).collect();
    assert_close(&clipped, &golden, 1e-3, "hift clipped wav");
}

#[test]
fn decode_matches_reference() {
    let mut model = load_model();
    let (_, audio_24k) = read_npy("audio_24k.npy");
    let (_, embedding) = read_npy("embedding.npy");
    let prompt_tokens = read_i32_npy("prompt_tokens.npy");
    let gen_tokens = read_i32_npy("gen_tokens.npy");
    let (_, golden_raw) = read_npy("full_wav_raw.npy");
    let (_, golden) = read_npy("full_wav.npy");
    let traces = read_json("traces.json");
    let draws = load_draws(traces["full_wav_len"].as_u64().unwrap() as usize);

    let prompt = model
        .prepare_prompt(&[0.0; 400], &audio_24k, &prompt_tokens, Some(embedding))
        .unwrap();
    let wav = model
        .decode(&gen_tokens, &prompt, 10, Some(&draws))
        .unwrap();
    assert_eq!(wav.len(), golden.len());
    assert_close(&wav, &golden_raw, 1e-3, "decode raw wav");
    let clipped: Vec<f32> = wav.iter().map(|v| v.clamp(-0.99, 0.99)).collect();
    assert_close(&clipped, &golden, 1e-3, "decode clipped wav");
}

#[test]
fn inputs_validate_like_reference() {
    let mut model = load_model();
    let prompt_tokens = read_i32_npy("prompt_tokens.npy");
    let gen_tokens = read_i32_npy("gen_tokens.npy");
    let (_, prompt_feat) = read_npy("prompt_feat.npy");

    // Wrong speaker embedding width is refused.
    let err = model
        .flow
        .infer(&gen_tokens, &prompt_tokens, &prompt_feat, &[0.0; 191], 10)
        .unwrap_err();
    assert!(err.to_string().contains("embedding"), "{err}");

    // Token ids are clipped into the vocabulary, not rejected: an
    // out-of-range id behaves like the reference mx.clip.
    let (_, embedding) = read_npy("embedding.npy");
    let clipped = model
        .flow
        .infer(
            &[i32::MAX, 0, -5],
            &prompt_tokens,
            &prompt_feat,
            &embedding,
            10,
        )
        .unwrap();
    assert_eq!(clipped.len() / 80, 3 * model.flow.up_rate());

    // Sine draws with the wrong length are refused.
    let bad_draws = SineDraws {
        rand_ini: vec![0.0; 9],
        sine_noise: vec![0.0; 10],
    };
    let err = model
        .hift
        .infer(&prompt_feat, Some(&bad_draws))
        .unwrap_err();
    assert!(err.to_string().contains("sine_noise"), "{err}");
}

/// Real-checkpoint smoke gate; opt-in via TURBOSPARK_STEPAUDIO2_MODEL
/// (a directory with flow.safetensors, hift.safetensors,
/// campplus.safetensors). Skipped when absent. Tests never download.
#[test]
fn real_checkpoint_smoke() {
    let Some(root) = std::env::var_os("TURBOSPARK_STEPAUDIO2_MODEL") else {
        eprintln!("skipping: TURBOSPARK_STEPAUDIO2_MODEL not set");
        return;
    };
    let root = PathBuf::from(root);
    let flow_file =
        SafetensorsFile::open(&root.join("flow.safetensors")).expect("flow.safetensors");
    let hift_file =
        SafetensorsFile::open(&root.join("hift.safetensors")).expect("hift.safetensors");
    let mut config = super::StepAudio2Config::reference();
    let mut flow = super::flow::StepAudio2Flow::load(&config, &flow_file).unwrap();
    let hift = super::hift::StepAudio2HiFT::load(&hift_file).unwrap();
    let campplus_file = root.join("campplus.safetensors");
    let campplus = if campplus_file.exists() {
        Some(super::campplus::StepAudio2CampPlus::load(
            &SafetensorsFile::open(&campplus_file).unwrap(),
        ))
    } else {
        None
    };

    // Deterministic decode smoke: zero prompt mel, mid-vocab tokens.
    let prompt_token = vec![3280i32; 6];
    let gen_tokens = vec![3281i32; 4];
    let prompt_feat = vec![0.0f32; 6 * config.up_stride * 80];
    let embedding = campplus
        .map(|_| Vec::new())
        .unwrap_or_else(|| vec![0.0; config.spk_embed_dim]);
    let mel = flow
        .infer(&gen_tokens, &prompt_token, &prompt_feat, &embedding, 2)
        .unwrap();
    assert_eq!(mel.len(), 4 * config.up_stride * 80);
    assert!(mel.iter().all(|v| v.is_finite()));
    let wav = hift.infer(&mel, None).unwrap();
    assert_eq!(wav.len(), 4 * config.up_stride * 480);
    assert!(wav.iter().all(|v| v.is_finite()));
    assert!(wav.iter().all(|v| v.abs() <= 0.99));
    let _ = &mut config;
}
