//! TurboQuant KV-cache codec reference tests
//! ([`turbospark_compute::kv_quant`], [`turbospark_compute::kv_quant_attention`]).
//!
//! Two kinds of case here. The first half is pure math on the codec's own
//! terms: codebook shape, packing, the RHT, the two sign vectors. The
//! second half checks the codec against an ORACLE fixture generated by
//! `scripts/mlx_turboquant_oracle.py`.
//!
//! **THAT ORACLE IS CURRENTLY A NUMPY TRANSLITERATION, NOT A RUN OF
//! mlx-vlm's OWN CODE.** The dev session that wrote this file had no
//! working `mx.eval` (see that script's module docstring for what was
//! tried), so `crates/compute/tests/generated/kv_quant_oracle.rs` was
//! produced with `--numpy-fallback`. Regenerate it WITHOUT that flag on a
//! machine with a working mlx backend before trusting the packed-word and
//! codebook comparisons below as validation against the real codec rather
//! than against a second transcription of the same source.

use turbospark_compute::{
    causal_attention_tq, codebook, dequantize_row, midpoints, pack_lsb_first, packed_words,
    quantize_index, quantize_row, rht_forward, rht_inverse, sign_vector, unpack_lsb_first,
    QuantizedRow, TqTables, KEY_SEED, VALUE_SEED,
};

// A nested module (rather than a bare top-level `include!`) so the
// generated file's full-precision float literals can carry one inner
// `#![allow(clippy::excessive_precision)]` -- an inner attribute is only
// legal at the start of an item's own body, which a bare `include!` at
// module scope is not.
mod oracle {
    #![allow(clippy::excessive_precision)]
    include!("generated/kv_quant_oracle.rs");
}
use oracle::*;

const ROWS_PER_SHAPE: usize = 4;

// ---------------------------------------------------------------------------
// A small deterministic PRNG, local to this test file (no external `rand`
// dependency, matching the rest of this crate's fixtures).
// ---------------------------------------------------------------------------

fn lcg_next(state: &mut u64) -> u64 {
    *state = state
        .wrapping_mul(6364136223846793005)
        .wrapping_add(1442695040888963407);
    *state
}

/// Uniform in `[0, 1)`.
fn lcg_uniform01(state: &mut u64) -> f64 {
    (lcg_next(state) >> 11) as f64 / (1u64 << 53) as f64
}

/// Uniform in `(-1, 1)`.
fn lcg_f32(state: &mut u64) -> f32 {
    (lcg_uniform01(state) * 2.0 - 1.0) as f32
}

/// Standard normal via Box-Muller.
fn random_normal(state: &mut u64) -> f32 {
    let u1 = lcg_uniform01(state).max(1e-12);
    let u2 = lcg_uniform01(state);
    ((-2.0 * u1.ln()).sqrt() * (2.0 * std::f64::consts::PI * u2).cos()) as f32
}

fn random_unit_vector(dim: usize, state: &mut u64) -> Vec<f32> {
    let v: Vec<f32> = (0..dim).map(|_| random_normal(state)).collect();
    let norm: f32 = v.iter().map(|x| x * x).sum::<f32>().sqrt();
    v.iter().map(|x| x / norm).collect()
}

// ---------------------------------------------------------------------------
// Codebook properties.
// ---------------------------------------------------------------------------

#[test]
fn codebook_is_sorted_symmetric_and_bounded() {
    for &dim in &[64usize, 128, 256, 512] {
        for &bits in &[2u8, 3, 4] {
            let cb = codebook(dim, bits);
            assert_eq!(cb.len(), 1usize << bits, "dim={dim} bits={bits}");
            assert!(
                cb.windows(2).all(|w| w[0] < w[1]),
                "codebook not strictly sorted at dim={dim} bits={bits}: {cb:?}"
            );
            for &v in &cb {
                assert!(
                    (-1.0..1.0).contains(&v),
                    "codebook entry {v} out of (-1, 1) at dim={dim} bits={bits}"
                );
            }
            // The density and the 32768-point grid are both exactly
            // symmetric about 0, so the Lloyd-Max fixed point is too -- but
            // the CDF that seeds the iteration is a running sum computed
            // LEFT TO RIGHT, which is not reflection-symmetric, and the two
            // centroids nearest the peak of a sharply-peaked density
            // (dim=64 bits=4's exponent is 30.5) can land up to a couple of
            // grid cells (2/32768 ~= 6e-5 each) apart from their mirror
            // after exactly 100 iterations. Observed 1.2e-4 at exactly that
            // shape. The tolerance below is set above that discretization
            // floor rather than at the ~1e-6 a fully converged, infinite-
            // precision fixed point would allow.
            let n = cb.len();
            for i in 0..n {
                assert!(
                    (cb[i] + cb[n - 1 - i]).abs() < 3e-4,
                    "codebook not symmetric at dim={dim} bits={bits} i={i}: {} vs {}",
                    cb[i],
                    cb[n - 1 - i]
                );
            }
        }
    }
}

/// [`quantize_index`]'s "count of midpoints exceeded" must agree with a
/// brute-force nearest-centroid search over the same codebook -- the two
/// are definitionally the same rule for a 1-D SORTED codebook, and this
/// pins that [`quantize_index`] actually implements it (mutation: comparing
/// against codebook entries directly, or an off-by-one in the count).
#[test]
fn quantize_index_matches_nearest_centroid() {
    for &dim in &[64usize, 256] {
        for &bits in &[2u8, 4] {
            let cb = codebook(dim, bits);
            let mp = midpoints(&cb);
            let mut state = 12345u64;
            for _ in 0..2000 {
                let x = lcg_f32(&mut state);
                let idx = quantize_index(x, &mp) as usize;

                let mut best = 0usize;
                let mut best_dist = f32::MAX;
                for (i, &c) in cb.iter().enumerate() {
                    let d = (c - x).abs();
                    if d < best_dist {
                        best_dist = d;
                        best = i;
                    }
                }
                assert_eq!(idx, best, "dim={dim} bits={bits} x={x} codebook={cb:?}");
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Packing.
// ---------------------------------------------------------------------------

/// An 11-element, 3-bit row where element 10 straddles the first/second
/// word boundary: `bit_offset = 30`, so its top bit spills into word 1.
#[test]
fn packing_straddles_word_boundary_at_three_bits() {
    let mut indices = vec![0u32; 11];
    indices[10] = 0b111;
    let packed = pack_lsb_first(&indices, 3);

    assert_eq!(packed.len(), packed_words(11, 3));
    assert_eq!(packed.len(), 2);
    // The low two bits of 7 land at bits 30-31 of word 0; nothing else is set.
    assert_eq!(packed[0], 0b11u32 << 30);
    // The spilled top bit of 7 lands at bit 0 of word 1.
    assert_eq!(packed[1], 1);

    assert_eq!(unpack_lsb_first(&packed, 3, 11), indices);
}

/// An index that does not fit in `bits` corrupts its neighbours silently
/// (the excess bits OR into the next field), so it must be refused by name
/// rather than packed.
#[test]
#[should_panic(expected = "does not fit")]
fn pack_lsb_first_refuses_an_out_of_range_index() {
    let _ = pack_lsb_first(&[0, 1, 4], 2); // 4 needs 3 bits, not 2
}

/// `bits` above 16 is outside anything this codec's allowed bit widths
/// (2..4) ever reach, and `1u32 << 32` overflows in `unpack_lsb_first`'s
/// mask computation.
#[test]
#[should_panic(expected = "must be in 1..=16")]
fn pack_lsb_first_refuses_bits_above_sixteen() {
    let _ = pack_lsb_first(&[0, 1, 2], 17);
}

#[test]
#[should_panic(expected = "must be in 1..=16")]
fn unpack_lsb_first_refuses_bits_above_sixteen() {
    let _ = unpack_lsb_first(&[0u32], 17, 1);
}

/// `causal_attention_tq` sinks must be exactly one per query head, the same
/// contract [`causal_attention_with_sinks`] enforces.
#[test]
#[should_panic(expected = "sinks.len()")]
fn causal_attention_tq_refuses_wrong_sink_count() {
    const DIM: usize = 64;
    let k_tables = TqTables::new(DIM, 3, KEY_SEED);
    let v_tables = TqTables::new(DIM, 3, VALUE_SEED);
    let q = vec![0.0f32; DIM * 2]; // 2 query heads
    let row = quantize_row(&vec![0.0f32; DIM], &k_tables.signs, &k_tables.midpoints, 3);
    let k_rows = [row.clone()];
    let v_rows = [row];
    let sinks = [0.0f32]; // wrong: must have one entry per q head (2)
    let _ = causal_attention_tq(
        &q,
        &k_rows,
        &v_rows,
        DIM,
        2,
        1,
        1,
        None,
        Some(&sinks),
        &k_tables,
        &v_tables,
    );
}

#[test]
fn pack_unpack_round_trips_at_every_width_and_length() {
    let mut state = 999u64;
    for &bits in &[2u8, 3, 4] {
        for &len in &[64usize, 128, 256, 512] {
            let indices: Vec<u32> = (0..len)
                .map(|_| (lcg_next(&mut state) as u32) & ((1u32 << bits) - 1))
                .collect();
            let packed = pack_lsb_first(&indices, bits);
            assert_eq!(
                packed.len(),
                packed_words(len, bits),
                "bits={bits} len={len}"
            );
            let back = unpack_lsb_first(&packed, bits, len);
            assert_eq!(back, indices, "bits={bits} len={len}");
        }
    }
}

// ---------------------------------------------------------------------------
// RHT.
// ---------------------------------------------------------------------------

#[test]
fn rht_inverse_undoes_forward_and_preserves_norm() {
    let mut state = 42u64;
    for &dim in &[64usize, 128, 256, 512] {
        let x: Vec<f32> = (0..dim).map(|_| lcg_f32(&mut state)).collect();
        let signs = sign_vector(dim, KEY_SEED);

        let rotated = rht_forward(&x, &signs);
        let back = rht_inverse(&rotated, &signs);
        for i in 0..dim {
            assert!(
                (x[i] - back[i]).abs() < 1e-4,
                "dim={dim} i={i}: {} vs {}",
                x[i],
                back[i]
            );
        }

        let norm_x: f32 = x.iter().map(|v| v * v).sum::<f32>().sqrt();
        let norm_rotated: f32 = rotated.iter().map(|v| v * v).sum::<f32>().sqrt();
        assert!(
            (norm_x - norm_rotated).abs() < 1e-3,
            "dim={dim}: norm {norm_x} moved to {norm_rotated} under a supposedly orthogonal transform"
        );
    }
}

// ---------------------------------------------------------------------------
// Sign vectors.
// ---------------------------------------------------------------------------

#[test]
fn key_and_value_sign_vectors_differ() {
    for &dim in &[64usize, 128, 256, 512] {
        let k = sign_vector(dim, KEY_SEED);
        let v = sign_vector(dim, VALUE_SEED);
        let differing = k.iter().zip(&v).filter(|(a, b)| a != b).count();
        assert!(
            differing > dim / 4,
            "K and V sign vectors too similar at dim={dim}: only {differing} of {dim} differ"
        );
    }
}

// ---------------------------------------------------------------------------
// Distortion, against mlx-vlm's own recorded figures
// (`test_turboquant_mse_matches_paper_small_bit_distortions`).
// ---------------------------------------------------------------------------

#[test]
fn distortion_on_unit_vectors_matches_mlx_vlm_paper_figures() {
    const DIM: usize = 64;
    const COUNT: usize = 256;
    const SEED: u64 = 0;

    let mut state = 7u64;
    let vectors: Vec<Vec<f32>> = (0..COUNT)
        .map(|_| random_unit_vector(DIM, &mut state))
        .collect();

    // (bits, expected mse); tolerance mirrors mlx-vlm's own
    // `pytest.approx(target, rel=0.25, abs=0.02)`.
    let expected: [(u8, f32); 3] = [(1, 0.36), (2, 0.117), (3, 0.03)];
    for (bits, target) in expected {
        let cb = codebook(DIM, bits);
        let mp = midpoints(&cb);
        let signs = sign_vector(DIM, SEED);

        let mut mse_sum = 0f64;
        for v in &vectors {
            let row = quantize_row(v, &signs, &mp, bits);
            let recon = dequantize_row(&row, &signs, &cb, bits, DIM);
            let sq: f32 = v.iter().zip(&recon).map(|(a, b)| (a - b) * (a - b)).sum();
            mse_sum += sq as f64;
        }
        let mse = (mse_sum / COUNT as f64) as f32;
        let tol = (target * 0.25).max(0.02);
        assert!(
            (mse - target).abs() <= tol,
            "bits={bits}: mse={mse}, expected {target} +/- {tol}"
        );
    }
}

// ---------------------------------------------------------------------------
// Sinks: denominator only, never the numerator.
// ---------------------------------------------------------------------------

#[test]
fn sinks_enter_the_denominator_only() {
    const DIM: usize = 64;
    let mut state = 55u64;
    let q: Vec<f32> = (0..DIM).map(|_| lcg_f32(&mut state)).collect();
    let seq_len = 6;
    let k_tables = TqTables::new(DIM, 3, KEY_SEED);
    let v_tables = TqTables::new(DIM, 4, VALUE_SEED);

    let mut k_rows = Vec::new();
    let mut v_rows = Vec::new();
    for _ in 0..seq_len {
        let kv: Vec<f32> = (0..DIM).map(|_| lcg_f32(&mut state)).collect();
        k_rows.push(quantize_row(&kv, &k_tables.signs, &k_tables.midpoints, 3));
        let vv: Vec<f32> = (0..DIM).map(|_| lcg_f32(&mut state)).collect();
        v_rows.push(quantize_row(&vv, &v_tables.signs, &v_tables.midpoints, 4));
    }

    let no_sink = causal_attention_tq(
        &q, &k_rows, &v_rows, DIM, 1, 1, seq_len, None, None, &k_tables, &v_tables,
    );
    let with_sink = causal_attention_tq(
        &q,
        &k_rows,
        &v_rows,
        DIM,
        1,
        1,
        seq_len,
        None,
        Some(&[10.0]),
        &k_tables,
        &v_tables,
    );

    // A large sink logit dominates the softmax denominator and shrinks
    // every real weight, so the output should shrink toward zero rather
    // than move toward some extra "value" (there is none) -- the tell that
    // it landed in the numerator would be the output moving toward an
    // unrelated fixed direction instead of uniformly shrinking.
    let no_sink_norm: f32 = no_sink.iter().map(|v| v * v).sum::<f32>().sqrt();
    let with_sink_norm: f32 = with_sink.iter().map(|v| v * v).sum::<f32>().sqrt();
    assert!(
        with_sink_norm < no_sink_norm * 0.5,
        "a dominant sink should shrink the output toward zero: {no_sink_norm} -> {with_sink_norm}"
    );
}

#[test]
fn identity_causal_attention_tq_matches_manual_dequantized_computation() {
    const DIM: usize = 64;
    let mut state = 321u64;
    let seq_len = 5;
    let k_tables = TqTables::new(DIM, 4, KEY_SEED);
    let v_tables = TqTables::new(DIM, 4, VALUE_SEED);

    let q: Vec<f32> = (0..DIM).map(|_| lcg_f32(&mut state)).collect();
    let mut k_raw = Vec::new();
    let mut v_raw = Vec::new();
    let mut k_rows = Vec::new();
    let mut v_rows = Vec::new();
    for _ in 0..seq_len {
        let kv: Vec<f32> = (0..DIM).map(|_| lcg_f32(&mut state)).collect();
        k_rows.push(quantize_row(&kv, &k_tables.signs, &k_tables.midpoints, 4));
        k_raw.push(kv);
        let vv: Vec<f32> = (0..DIM).map(|_| lcg_f32(&mut state)).collect();
        v_rows.push(quantize_row(&vv, &v_tables.signs, &v_tables.midpoints, 4));
        v_raw.push(vv);
    }

    let out = causal_attention_tq(
        &q, &k_rows, &v_rows, DIM, 1, 1, seq_len, None, None, &k_tables, &v_tables,
    );

    // Manual reference: dequantize every row up front, then run plain
    // softmax attention over the RECONSTRUCTED (not original) K/V -- this
    // is what the codec's score/weighted_sum are equivalent to
    // mathematically, and pins that `causal_attention_tq` is not doing
    // something structurally different (e.g. mixing K's and V's rotation).
    let k_dequant: Vec<f32> = k_rows
        .iter()
        .flat_map(|r| dequantize_row(r, &k_tables.signs, &k_tables.codebook, 4, DIM))
        .collect();
    let v_dequant: Vec<f32> = v_rows
        .iter()
        .flat_map(|r| dequantize_row(r, &v_tables.signs, &v_tables.codebook, 4, DIM))
        .collect();
    let reference = turbospark_compute::causal_attention(
        &q, &k_dequant, &v_dequant, DIM, 1, 1, seq_len, None, None,
    );

    for i in 0..DIM {
        assert!(
            (out[i] - reference[i]).abs() < 1e-3,
            "index {i}: {} vs {}",
            out[i],
            reference[i]
        );
    }
}

// ---------------------------------------------------------------------------
// Oracle-backed checks. See this file's module doc for the numpy-fallback
// caveat.
// ---------------------------------------------------------------------------

/// Checks the codec's MATH (codebook, packing) against the oracle at one
/// shape, feeding the ORACLE's own sign vector into [`quantize_row`] rather
/// than regenerating one with [`sign_vector`]. The two sign generators are
/// deliberately different algorithms (splitmix64 here, numpy's PCG64 in the
/// oracle -- see `kv_quant::sign_vector`'s doc), so comparing them would
/// only ever fail; what has to agree is what each generator's own signs
/// round-trip to.
#[allow(clippy::too_many_arguments)]
fn check_oracle_shape(
    dim: usize,
    bits: u8,
    signs: &[f32],
    oracle_codebook: &[f32],
    input_rows: &[f32],
    oracle_norms: &[f32],
    oracle_packed: &[u32],
    packed_width: usize,
) {
    assert_eq!(
        packed_words(dim, bits),
        packed_width,
        "dim={dim} bits={bits}"
    );

    let our_codebook = codebook(dim, bits);
    assert_eq!(
        our_codebook.len(),
        oracle_codebook.len(),
        "dim={dim} bits={bits}"
    );
    // `codebook()` runs its Lloyd-Max loop in f64 (its own doc explains
    // why); mlx-vlm's `_codebook` runs the same 100 iterations with a
    // `np.float32` grid throughout, confirmed by reading `_beta_pdf`'s
    // dtype handling. Over 100 iterations that is enough to separate the
    // two by more than machine epsilon -- observed up to 5.3e-5 here, which
    // is what sets this tolerance rather than the tighter one the doc
    // comment above once assumed.
    for (i, (a, b)) in our_codebook.iter().zip(oracle_codebook).enumerate() {
        assert!(
            (a - b).abs() < 1e-4,
            "codebook[{i}] mismatch at dim={dim} bits={bits}: {a} vs {b}"
        );
    }
    let mp = midpoints(&our_codebook);

    for r in 0..ROWS_PER_SHAPE {
        let x = &input_rows[r * dim..(r + 1) * dim];
        let row = quantize_row(x, signs, &mp, bits);

        let expected_words = &oracle_packed[r * packed_width..(r + 1) * packed_width];
        assert_eq!(
            row.words, expected_words,
            "packed words mismatch dim={dim} bits={bits} row={r}"
        );

        let oracle_norm = oracle_norms[r];
        let rel = (row.norm - oracle_norm).abs() / oracle_norm.max(1e-6);
        assert!(
            rel < 2f32.powi(-11),
            "norm mismatch dim={dim} bits={bits} row={r}: {} vs oracle {oracle_norm} (rel {rel})",
            row.norm
        );

        let dequant = dequantize_row(&row, signs, &our_codebook, bits, dim);
        assert_eq!(dequant.len(), dim);
    }
}

#[test]
fn quantize_row_matches_oracle_d64_b2() {
    check_oracle_shape(
        64,
        2,
        &D64B2_SIGNS,
        &D64B2_CODEBOOK,
        &D64B2_INPUT_ROWS,
        &D64B2_NORMS,
        &D64B2_PACKED,
        D64B2_PACKED_WIDTH,
    );
}

#[test]
fn quantize_row_matches_oracle_d64_b3() {
    check_oracle_shape(
        64,
        3,
        &D64B3_SIGNS,
        &D64B3_CODEBOOK,
        &D64B3_INPUT_ROWS,
        &D64B3_NORMS,
        &D64B3_PACKED,
        D64B3_PACKED_WIDTH,
    );
}

#[test]
fn quantize_row_matches_oracle_d128_b4() {
    check_oracle_shape(
        128,
        4,
        &D128B4_SIGNS,
        &D128B4_CODEBOOK,
        &D128B4_INPUT_ROWS,
        &D128B4_NORMS,
        &D128B4_PACKED,
        D128B4_PACKED_WIDTH,
    );
}

#[test]
fn quantize_row_matches_oracle_d256_b3() {
    check_oracle_shape(
        256,
        3,
        &D256B3_SIGNS,
        &D256B3_CODEBOOK,
        &D256B3_INPUT_ROWS,
        &D256B3_NORMS,
        &D256B3_PACKED,
        D256B3_PACKED_WIDTH,
    );
}

// `QuantizedRow` is otherwise only constructed inside `quantize_row`; touch
// it directly once so a future refactor cannot silently drop a field
// without a compile error here.
#[test]
fn quantized_row_fields_are_reachable() {
    let row = QuantizedRow {
        norm: 1.0,
        words: vec![0, 1],
    };
    assert_eq!(row.norm, 1.0);
    assert_eq!(row.words, vec![0, 1]);
}
