//! GGUF Q2_K reference decode and a layout-only encoder for test fixtures.
//!
//! A Q2_K superblock carries 16 one-byte scale/min pairs and 64 bytes of
//! two-bit values.  Each byte holds four elements 32 apart.  The format is
//! asymmetric: `w = d * scale * q - dmin * min`.

use foundation::LogitValue as F16;

pub const Q2_K_BLOCK_ELEMS: usize = 256;
pub const Q2_K_SUB_ELEMS: usize = 16;
pub const Q2_K_BLOCK_BYTES: usize = 84;
const SCALES_AT: usize = 0;
const QUANTS_AT: usize = 16;
const D_AT: usize = 80;
const DMIN_AT: usize = 82;

fn f16_at(bytes: &[u8], at: usize) -> f32 {
    f32::from(F16::from_bits(u16::from_le_bytes([
        bytes[at],
        bytes[at + 1],
    ])))
}

/// Dequantizes whole Q2_K superblocks.
pub fn dequantize_q2_k(blocks: &[u8], n: usize) -> Vec<f32> {
    assert_eq!(n % Q2_K_BLOCK_ELEMS, 0);
    assert!(blocks.len() >= n / Q2_K_BLOCK_ELEMS * Q2_K_BLOCK_BYTES);
    let mut out = vec![0.0; n];
    for b in 0..n / Q2_K_BLOCK_ELEMS {
        let blk = &blocks[b * Q2_K_BLOCK_BYTES..][..Q2_K_BLOCK_BYTES];
        let d = f16_at(blk, D_AT);
        let dmin = f16_at(blk, DMIN_AT);
        for half in 0..2 {
            for group in 0..4 {
                let shift = 2 * group;
                for segment in 0..2 {
                    let sc = blk[SCALES_AT + half * 8 + group * 2 + segment];
                    let dl = d * (sc & 15) as f32;
                    let ml = dmin * (sc >> 4) as f32;
                    for lane in 0..16 {
                        let q = blk[QUANTS_AT + half * 32 + segment * 16 + lane];
                        let at =
                            b * Q2_K_BLOCK_ELEMS + half * 128 + group * 32 + segment * 16 + lane;
                        out[at] = dl * ((q >> shift) & 3) as f32 - ml;
                    }
                }
            }
        }
    }
    out
}

/// Fixture encoder. It deliberately uses a coarse shared super-scale; real
/// GGUF bytes are copied, never generated by this port.
pub fn quantize_q2_k(row: &[f32]) -> Vec<u8> {
    assert_eq!(row.len() % Q2_K_BLOCK_ELEMS, 0);
    let mut out = Vec::with_capacity(row.len() / Q2_K_BLOCK_ELEMS * Q2_K_BLOCK_BYTES);
    for values in row.chunks_exact(Q2_K_BLOCK_ELEMS) {
        let max = values.iter().copied().fold(0.0_f32, |a, x| a.max(x.abs()));
        let d = if max == 0.0 { 0.0 } else { max / 45.0 };
        let d16 = F16::from_f32(d);
        let mut blk = [0u8; Q2_K_BLOCK_BYTES];
        for sub in 0..16 {
            let slice = &values[sub * Q2_K_SUB_ELEMS..][..Q2_K_SUB_ELEMS];
            let lo = slice.iter().copied().fold(0.0_f32, f32::min).min(0.0);
            let hi = slice.iter().copied().fold(0.0_f32, f32::max).max(0.0);
            let scale = if d == 0.0 {
                0
            } else {
                ((hi - lo) / (3.0 * d)).round().clamp(0.0, 15.0) as u8
            };
            let min = if d == 0.0 {
                0
            } else {
                ((-lo) / d).round().clamp(0.0, 15.0) as u8
            };
            let byte = scale | (min << 4);
            blk[sub] = byte;
        }
        for (e, &value) in values.iter().enumerate() {
            let sub = e / Q2_K_SUB_ELEMS;
            let scale = blk[sub] & 15;
            let min = blk[sub] >> 4;
            let q = if scale == 0 || d == 0.0 {
                0
            } else {
                ((value / d + min as f32) / scale as f32)
                    .round()
                    .clamp(0.0, 3.0) as u8
            };
            let half = e / 128;
            let within = e % 128;
            let group = within / 32;
            let segment = (within % 32) / 16;
            let lane = within % 16;
            blk[QUANTS_AT + half * 32 + segment * 16 + lane] |= q << (2 * group);
        }
        blk[D_AT..D_AT + 2].copy_from_slice(&d16.to_bits().to_le_bytes());
        blk[DMIN_AT..DMIN_AT + 2].copy_from_slice(&d16.to_bits().to_le_bytes());
        out.extend_from_slice(&blk);
    }
    out
}

pub fn dequant_q2_k_gemv(weight_rows: &[&[u8]], x: &[f32]) -> Vec<f32> {
    weight_rows
        .iter()
        .map(|row| {
            dequantize_q2_k(row, x.len())
                .into_iter()
                .zip(x)
                .map(|(w, x)| w * x)
                .sum()
        })
        .collect()
}
