//! Fixture parity tests for the Vocos port.
//!
//! Fixtures live in `testdata/vocos/`, regenerated by
//! `tools/gen_vocos_fixtures.py` against the pinned mlx-audio commit.
//! The golden mel features pin the whisper-style front end (symmetric
//! Hann, centered reflect STFT, final frame dropped, HTK mel) and the
//! golden audio pins the ConvNeXt backbone plus the window-sum iSTFT.
//! A local checkpoint directory can be pointed at via
//! TURBOSPARK_VOCOS_MODEL and is skipped when absent. Tests never
//! download.

use std::path::{Path, PathBuf};

use super::{Vocos, VocosConfig};
use turbospark_model_io::safetensors::SafetensorsFile;

fn testdata(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata/vocos")
        .join(name)
}

fn read_json(name: &str) -> serde_json::Value {
    let text = std::fs::read_to_string(testdata(name)).expect(name);
    serde_json::from_str(&text).expect(name)
}

fn read_npy(name: &str) -> (Vec<usize>, Vec<f32>) {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    let data = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (shape, data)
}

#[allow(dead_code)]
fn floats(value: &serde_json::Value) -> Vec<f32> {
    value
        .as_array()
        .expect("float array")
        .iter()
        .map(|v| v.as_f64().expect("f64") as f32)
        .collect()
}

fn max_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(
        a.len(),
        b.len(),
        "length mismatch: {} vs {}",
        a.len(),
        b.len()
    );
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
}

#[test]
fn yaml_config_parses() {
    let text = std::fs::read_to_string(testdata("config.yaml")).expect("config");
    let config = VocosConfig::from_yaml(&text).unwrap();
    assert_eq!(config.backbone.input_channels, 20);
    assert_eq!(config.backbone.dim, 32);
    assert_eq!(config.backbone.num_layers, 4);
    assert!(config.backbone.adanorm_num_embeddings.is_none());
    assert_eq!(config.head.n_fft, 256);
    assert_eq!(config.head.hop_length, 64);
    let super::VocosFeatureConfig::Mel(mel) = &config.feature_extractor else {
        panic!("expected the mel front end");
    };
    assert_eq!(mel.n_fft, 256);
    assert_eq!(mel.n_mels, 20);
    assert_eq!(mel.padding, "center");
}

#[test]
fn tiny_end_to_end_matches_reference() {
    let text = std::fs::read_to_string(testdata("config.yaml")).expect("config");
    let config = VocosConfig::from_yaml(&text).unwrap();
    let file = SafetensorsFile::open(&testdata("tiny_weights.safetensors")).expect("weights");
    let model = Vocos::load(config, &file).unwrap();
    let traces = read_json("traces.json");

    for tag in ["a", "b"] {
        let (mel_shape, golden_mel) = read_npy(&format!("{tag}_mel.npy"));
        let n_mels = mel_shape[2];
        let frames = mel_shape[1];
        assert_eq!(n_mels, model.config.backbone.input_channels);
        // (1, T, C) channels-last -> [C, T]
        let mut mel = vec![0.0f32; n_mels * frames];
        for t in 0..frames {
            for c in 0..n_mels {
                mel[c * frames + t] = golden_mel[t * n_mels + c];
            }
        }
        let audio = model.decode(&mel, frames).unwrap();
        let (_, golden_audio) = read_npy(&format!("{tag}_audio.npy"));
        assert_eq!(
            audio.len() as i64,
            traces[format!("{tag}_audio_len").as_str()]
                .as_i64()
                .unwrap()
        );
        assert_eq!(audio.len(), golden_audio.len());
        let diff = max_diff(&audio, &golden_audio);
        eprintln!("DEBUG {tag} audio diff {diff}");
        let ratio = audio[audio.len() / 2] / golden_audio[golden_audio.len() / 2];
        eprintln!("DEBUG {tag} mid ratio {ratio}");
        assert!(diff < 1e-4, "{tag} audio diff {diff}");
    }
}

#[test]
fn mel_front_end_matches_reference() {
    // Reconstruct the generator wave from a seeded RNG equivalent: the
    // generator used numpy default_rng(29); instead of reimplementing
    // Philox, the wave is stored alongside as a npy fixture.
    let text = std::fs::read_to_string(testdata("config.yaml")).expect("config");
    let config = VocosConfig::from_yaml(&text).unwrap();
    let file = SafetensorsFile::open(&testdata("tiny_weights.safetensors")).expect("weights");
    let model = Vocos::load(config, &file).unwrap();
    for tag in ["a", "b"] {
        let (_, wave) = read_npy(&format!("{tag}_wave.npy"));
        let (features, frames) = model.mel_features(&wave).unwrap();
        let (mel_shape, golden_mel) = read_npy(&format!("{tag}_mel.npy"));
        assert_eq!(frames as i64, mel_shape[1] as i64);
        // (1, T, C) -> [C, T]
        let n_mels = model.config.backbone.input_channels;
        let mut golden = vec![0.0f32; n_mels * frames];
        for t in 0..frames {
            for c in 0..n_mels {
                golden[c * frames + t] = golden_mel[t * n_mels + c];
            }
        }
        assert_eq!(features.len(), golden.len());
        assert!(max_diff(&features, &golden) < 1e-4, "{tag} mel diff");
    }
}

/// Real-checkpoint gate; opt-in via TURBOSPARK_VOCOS_MODEL pointing at
/// a vocos checkpoint directory (config.yaml + model.safetensors).
/// Skips when unset.
#[test]
fn real_checkpoint_gate() {
    let Ok(dir) = std::env::var("TURBOSPARK_VOCOS_MODEL") else {
        eprintln!("skipping: TURBOSPARK_VOCOS_MODEL not set");
        return;
    };
    let model = Vocos::open(Path::new(&dir)).unwrap();
    let cfg = match &model.config.feature_extractor {
        super::VocosFeatureConfig::Mel(mel) => mel.clone(),
        _ => {
            eprintln!("skipping: encodec front end needs an encodec checkpoint");
            return;
        }
    };
    let wave: Vec<f32> = (0..cfg.sample_rate as usize)
        .map(|i| ((i as f32) * 220.0 * std::f32::consts::TAU / cfg.sample_rate as f32).sin() * 0.3)
        .collect();
    let (features, frames) = model.mel_features(&wave).unwrap();
    let audio = model.decode(&features, frames).unwrap();
    assert!(audio.iter().all(|v| v.is_finite()));
}
