//! Fixture parity tests for the SAM-Audio port.
//!
//! Fixtures live in `testdata/sam_audio/`, regenerated by
//! `tools/gen_sam_audio_fixtures.py` against the pinned mlx-audio
//! commit. Tests never download; the T5 tokenizer is out of scope and
//! tests feed token ids directly.

use std::path::{Path, PathBuf};

use super::{OdeOptions, SamAudio, SamAudioConfig};
use turbospark_model_io::safetensors::SafetensorsFile;

fn testdata(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata/sam_audio")
        .join(name)
}

fn read_json(name: &str) -> serde_json::Value {
    let text = std::fs::read_to_string(testdata(name)).expect(name);
    serde_json::from_str(&text).expect(name)
}

fn read_npy(name: &str) -> (Vec<usize>, Vec<f32>) {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    let data = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (shape, data)
}

fn read_npy_i32(name: &str) -> (Vec<usize>, Vec<i32>) {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    let data = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| i32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (shape, data)
}

fn max_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(
        a.len(),
        b.len(),
        "length mismatch {} vs {}",
        a.len(),
        b.len()
    );
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
}

fn load_model() -> SamAudio {
    let config = SamAudioConfig::from_json(&read_json("config.json")).unwrap();
    let file = SafetensorsFile::open(&testdata("tiny_weights.safetensors")).expect("weights");
    let codec = SafetensorsFile::open(&testdata("tiny_codec.safetensors")).expect("codec");
    SamAudio::load(config, &file, &codec).unwrap()
}

#[test]
fn config_parses() {
    let config = SamAudioConfig::from_json(&read_json("config.json")).unwrap();
    assert_eq!(config.in_channels, 48);
    assert_eq!(config.transformer.dim, 64);
    assert_eq!(config.transformer.n_heads, 4);
    assert_eq!(config.transformer.n_layers, 2);
    assert_eq!(config.text_encoder.d_model, 32);
    assert_eq!(config.text_encoder.num_layers, 2);
}

#[test]
fn t5_encoding_matches_reference() {
    let model = load_model();
    let (_, tokens_i32) = read_npy_i32("tokens.npy");
    let (_, mask) = read_npy("token_mask.npy");
    let features = model.encode_text(&tokens_i32, &mask);
    let (gshape, golden) = read_npy("text_features.npy");
    assert_eq!(features.len(), gshape.iter().product::<usize>());
    let diff = max_diff(&features, &golden);
    eprintln!("text features diff {diff}");
    assert!(diff < 5e-4, "text features diff {diff}");
}

#[test]
fn audio_features_match_reference() {
    let model = load_model();
    let (_, wave) = read_npy("wave.npy");
    let features = model.audio_features(&wave).unwrap();
    let (fshape, golden) = read_npy("audio_features.npy");
    assert_eq!(features.len(), fshape.iter().product::<usize>());
    let diff = max_diff(&features, &golden);
    eprintln!("audio features diff {diff}");
    assert!(diff < 1e-4, "audio features diff {diff}");
}

#[test]
fn velocity_matches_reference() {
    let model = load_model();
    let (ashape, features) = read_npy("audio_features.npy");
    let (tshape, golden_text) = read_npy("text_features.npy");
    let (_, tokens) = read_npy("tokens.npy");
    let (_, mask) = read_npy("token_mask.npy");
    let ids: Vec<i32> = tokens.iter().map(|&v| v as i32).collect();
    let frames = ashape[1];
    // Reference noisy input was default_rng(77) over the feature shape.
    let mut state: u64 = 0x853c_49e6_748f_ea9b;
    let mut noise = vec![0.0f32; features.len()];
    // The exact reference noise is not reproducible without numpy's
    // PCG64; store it instead when present.
    if testdata("noise.npy").exists() {
        let (_, n) = read_npy("noise.npy");
        noise = n;
    } else {
        for value in &mut noise {
            state ^= state << 13;
            state ^= state >> 7;
            state ^= state << 17;
            *value = (state >> 40) as f32 / (1u32 << 24) as f32 - 1.0;
        }
    }
    let velocity = model.velocity(
        &noise,
        &features,
        &golden_text,
        tshape[1],
        0.25,
        Some(&mask),
        None,
        None,
    );
    let (_, golden) = read_npy("velocity.npy");
    let diff = max_diff(&velocity, &golden);
    eprintln!("velocity diff {diff}");
    assert!(diff < 5e-3, "velocity diff {diff}");
    let _ = ids;
}

#[test]
fn separation_matches_reference() {
    let model = load_model();
    let (_, wave) = read_npy("wave.npy");
    let (_, tokens_i32) = read_npy_i32("tokens.npy");
    let (_, mask) = read_npy("token_mask.npy");
    let ids = tokens_i32;
    let (ashape, _) = read_npy("audio_features.npy");
    let frames = ashape[1];
    let (_, noise) = read_npy("noise.npy");
    let (target, residual) = model
        .separate(
            &wave,
            &ids,
            &mask,
            &noise,
            OdeOptions {
                midpoint: true,
                step_size: 2.0 / 16.0,
            },
        )
        .unwrap();
    let (_, golden_target) = read_npy("target.npy");
    let (_, golden_residual) = read_npy("residual.npy");
    let peak = golden_target
        .iter()
        .chain(&golden_residual)
        .fold(0.0f32, |a, &v| a.max(v.abs()))
        .max(1e-6);
    let diff = max_diff(&target, &golden_target);
    eprintln!("target diff {diff} peak {peak}");
    assert!(diff < 5e-2, "target diff {diff} peak {peak}");
    let diff = max_diff(&residual, &golden_residual);
    eprintln!("residual diff {diff} peak {peak}");
    assert!(diff < 5e-2, "residual diff {diff} peak {peak}");
    let _ = (ashape, frames);
}

#[test]
fn probe_t5_stages() {
    let model = load_model();
    let (_, tokens_i32) = read_npy_i32("tokens.npy");
    let (_, mask) = read_npy("token_mask.npy");
    let enc = &model.text_encoder;
    let seq = tokens_i32.len();
    let mut h = vec![0.0f32; seq * enc.d_model];
    for (t, &id) in tokens_i32.iter().enumerate() {
        let id = id.clamp(0, enc.vocab as i32 - 1) as usize;
        h[t * enc.d_model..(t + 1) * enc.d_model]
            .copy_from_slice(&enc.shared[id * enc.d_model..(id + 1) * enc.d_model]);
    }
    eprintln!("emb row0[:4]: {:?}", &h[0..4]);
    let bias = enc.blocks[0].attn.relative_bias.as_ref().map(|table| {
        let mut bias = vec![0.0f32; seq * seq * enc.n_heads];
        for qi in 0..seq {
            for ki in 0..seq {
                let bucket = enc.relative_bucket(ki as isize - qi as isize);
                for head in 0..enc.n_heads {
                    bias[(qi * seq + ki) * enc.n_heads + head] =
                        table.weight[bucket * enc.n_heads + head];
                }
            }
        }
        bias
    });
    eprintln!("bias[0,0,:4]: {:?}", &bias.as_ref().unwrap()[0..4]);
    let buckets: Vec<usize> = (0..seq)
        .map(|ki| enc.relative_bucket(ki as isize - 0))
        .collect();
    eprintln!("bucket row0: {:?}", buckets);
    let block = &enc.blocks[0];
    let mut normed = h.clone();
    super::t5_rms(&mut normed, &block.attn_norm, enc.eps);
    eprintln!("normed row0[:4]: {:?}", &normed[0..4]);
    let attn_out = block
        .attn
        .forward(&normed, seq, bias.as_deref(), &mask, enc);
    eprintln!("attn row0[:4]: {:?}", &attn_out[0..4]);
}

#[test]
fn dit_stage_traces_match_reference() {
    let model = load_model();
    let (ashape, features) = read_npy("audio_features.npy");
    let (_, noise) = read_npy("noise.npy");
    let frames = ashape[1];
    let _ = frames;
    let channels = model.codec.config.codebook_dim;
    // aligned = proj(concat([noisy, zeros, features]))
    let in_ch = model.config.in_channels;
    let mut concat = vec![0.0f32; frames * in_ch];
    for f in 0..frames {
        concat[f * in_ch..f * in_ch + 2 * channels]
            .copy_from_slice(&noise[f * 2 * channels..(f + 1) * 2 * channels]);
        concat[(f + 1) * in_ch - 2 * channels..(f + 1) * in_ch]
            .copy_from_slice(&features[f * 2 * channels..(f + 1) * 2 * channels]);
    }
    let aligned = model.proj.run(&concat, frames);
    let (_, golden_aligned) = read_npy("aligned.npy");
    eprintln!("aligned diff {}", max_diff(&aligned, &golden_aligned));

    let (tshape, golden_text) = read_npy("text_features.npy");
    let memory_projected = model.memory_proj.run(&golden_text, tshape[1]);
    let dim = model.transformer.dim;
    let half = model.t_freqs.len();
    let mut t_emb = vec![0.0f32; dim];
    let time = 0.25f32;
    for (i, &freq) in model.t_freqs.iter().enumerate() {
        let arg = time * freq;
        t_emb[i] = arg.cos();
        t_emb[half + i] = arg.sin();
    }
    let mut memory = vec![0.0f32; tshape[1] * dim];
    for t in 0..tshape[1] {
        for d in 0..dim {
            memory[t * dim + d] = memory_projected[t * dim + d] + t_emb[d];
        }
    }
    let (_, golden_memory) = read_npy("memory.npy");
    eprintln!("memory diff {}", max_diff(&memory, &golden_memory));

    // t path.
    let t_freq_in = model.transformer.timestep_embedding(time);
    let t_e = model.transformer.t_embedder.run(&t_freq_in, 1);
    let mut t0 = t_e.clone();
    crate::ops::silu(&mut t0);
    let t0 = model.transformer.t_block.run(&t0, 1);
    let (_, golden_t0) = read_npy("t0.npy");
    eprintln!("t0 diff {}", max_diff(&t0, &golden_t0));

    // Patcher output on aligned (transposed).
    let mut cf = vec![0.0f32; dim * frames];
    for t in 0..frames {
        for c in 0..dim {
            cf[c * frames + t] = aligned[t * dim + c];
        }
    }
    let patched = model.transformer.x_embedder.forward(&cf, frames);
    let mut h = vec![0.0f32; dim * frames];
    for t in 0..frames {
        for c in 0..dim {
            h[t * dim + c] = patched[c * frames + t];
        }
    }
    eprintln!("patched row0[:4]: {:?}", &h[0..4]);
}
