//! Fixture parity tests for the MiMo audio tokenizer port.
//!
//! Fixtures live in `testdata/mimo_audio_tokenizer/`, regenerated by
//! `tools/gen_mimo_fixtures.py` against the pinned mlx-audio commit.
//! Gates: the HTK log-mel front end, encoder hidden states, RVQ codes
//! (exact, with margins), and the full codes-to-waveform decode. A
//! real checkpoint can be pointed at via
//! TURBOSPARK_MIMO_AUDIO_TOKENIZER_MODEL and is skipped when absent.
//! Tests never download.

use std::path::{Path, PathBuf};

use super::{MiMoAudioTokenizer, MimoConfig};
use turbospark_model_io::safetensors::SafetensorsFile;

fn testdata(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata/mimo_audio_tokenizer")
        .join(name)
}

fn read_json(name: &str) -> serde_json::Value {
    let text = std::fs::read_to_string(testdata(name)).expect(name);
    serde_json::from_str(&text).expect(name)
}

fn read_npy(name: &str) -> (Vec<usize>, Vec<f32>) {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    assert!(header.contains("<f4"), "{name} must be f32");
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    let data = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (shape, data)
}

fn read_codes(name: &str) -> Vec<Vec<i32>> {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    assert!(header.contains("<i4"), "{name} must be int32");
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    assert_eq!(shape.len(), 2, "{name} must be [books, frames]");
    let data: Vec<i32> = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| i32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    let (books, frames) = (shape[0], shape[1]);
    (0..books)
        .map(|b| data[b * frames..(b + 1) * frames].to_vec())
        .collect()
}

fn rel_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(a.len(), b.len());
    let max = b.iter().fold(0.0f32, |acc, v| acc.max(v.abs()));
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
        / max
}

fn load_tiny() -> MiMoAudioTokenizer {
    let config = read_json("tiny_config.json");
    let config = MimoConfig::from_json(&config).expect("config");
    let file = SafetensorsFile::open(&testdata("tiny_weights.safetensors")).expect("weights");
    MiMoAudioTokenizer::load(config, &file).expect("load")
}

#[test]
fn config_defaults_match_reference() {
    let config = MimoConfig::from_json(&serde_json::json!({})).unwrap();
    assert_eq!(config.d_model, 1280);
    assert_eq!(config.n_mels, 128);
    assert_eq!(config.sampling_rate, 24_000);
    assert_eq!(config.nfft, 960);
    assert_eq!(config.hop_length, 240);
    assert_eq!(config.avg_pooler, 2);
    assert_eq!(config.encoder_layers, 32);
    assert_eq!(config.encoder_skip_layer_id, Some(3));
    assert_eq!(config.decoder_layers, 32);
    assert_eq!(config.vocoder_num_layers, 16);
    assert_eq!(config.vocoder_attn_window, (40, 10));
    assert_eq!(config.num_quantizers, 20);
    assert_eq!(config.codebook_size.len(), 20);
    assert_eq!(&config.codebook_size[..2], &[1024, 1024]);
    assert!(config.codebook_size[2..].iter().all(|&s| s == 128));
    assert_eq!(config.downsample_rate(), 960);
}

#[test]
fn config_validates_like_reference() {
    // codebook_size must cover every quantizer.
    let err = MimoConfig::from_json(&serde_json::json!({
        "num_quantizers": 4,
        "codebook_size": [8, 8, 8],
    }))
    .unwrap_err();
    assert!(err.to_string().contains("codebook_size"), "{err}");
    // Odd head dims are refused.
    let err = MimoConfig::from_json(&serde_json::json!({
        "d_model": 30,
        "encoder_attention_heads": 4,
        "decoder_attention_heads": 4,
        "vocoder_dim": 16,
        "vocoder_attention_heads": 2,
    }))
    .unwrap_err();
    assert!(err.to_string().contains("even head"), "{err}");
}

#[test]
fn log_mel_matches_reference() {
    let model = load_tiny();
    let (_, wave) = read_npy("wave.npy");
    let (mel_shape, golden) = read_npy("mel_golden.npy");
    let mel = model.log_mel_spectrogram(&wave).unwrap();
    assert_eq!(mel.len(), mel_shape[0]);
    assert_eq!(mel[0].len(), mel_shape[1]);
    let flat: Vec<f32> = mel.into_iter().flatten().collect();
    let max = golden.iter().fold(0.0f32, |a, v| a.max(v.abs()));
    let diff = flat
        .iter()
        .zip(&golden)
        .map(|(a, b)| (a - b).abs())
        .fold(0.0f32, f32::max);
    assert!(diff / max < 1e-6, "log-mel rel diff {}", diff / max);
}

#[test]
fn encode_hidden_and_codes_match_reference() {
    let model = load_tiny();
    let traces = read_json("traces.json");
    let (mel_shape, mel_data) = read_npy("mel_golden.npy");
    let (frames, n_mels) = (mel_shape[0], mel_shape[1]);
    let mels: Vec<Vec<f32>> = (0..frames)
        .map(|t| mel_data[t * n_mels..(t + 1) * n_mels].to_vec())
        .collect();

    // Hidden states first: codes are meaningless if the encoder
    // diverges.
    let hidden = model.encode_features(&mels, frames).unwrap();
    let (h_shape, golden_hidden) = read_npy("hidden.npy");
    assert_eq!(
        h_shape,
        vec![hidden.len() / model.config.d_model, model.config.d_model]
    );
    let rel = rel_diff(&hidden, &golden_hidden);
    assert!(rel < 1e-5, "hidden rel diff {rel}");

    let codes = model.encode_mels(&mels, frames).unwrap();
    let golden_codes = read_codes("codes.npy");
    assert_eq!(codes.len(), golden_codes.len());
    for (b, (mine, golden)) in codes.iter().zip(&golden_codes).enumerate() {
        assert_eq!(mine, golden, "book {b}");
    }
    let margin = traces["rvq_min_margin"].as_f64().unwrap();
    assert!(margin > 1e-4, "rvq margin {margin}");
}

#[test]
fn decode_matches_reference() {
    let model = load_tiny();
    let (_, golden) = read_npy("decoded.npy");
    let codes = read_codes("codes.npy");
    let audio = model.decode(&codes).unwrap();
    assert_eq!(audio.len(), golden.len());
    let rel = rel_diff(&audio, &golden);
    assert!(rel < 1e-4, "decode rel diff {rel}");
    assert_eq!(audio.len(), codes[0].len() * model.config.downsample_rate());
}

#[test]
fn decode_validates_codes() {
    let model = load_tiny();
    // Too many books.
    let too_many = vec![vec![0i32; 2]; model.config.num_quantizers + 1];
    assert!(model.decode(&too_many).is_err());
    // Code outside its own book (book 2 holds 5 entries).
    let bad = vec![vec![0i32; 2], vec![0i32; 2], vec![9, 9]];
    assert!(model.decode(&bad).is_err());
}

/// Real-checkpoint gate; opt-in via TURBOSPARK_MIMO_AUDIO_TOKENIZER_MODEL
/// pointing at a directory with config.json + model.safetensors.
/// Skips when unset.
#[test]
fn real_checkpoint_gate() {
    let Ok(dir) = std::env::var("TURBOSPARK_MIMO_AUDIO_TOKENIZER_MODEL") else {
        eprintln!("skipping: TURBOSPARK_MIMO_AUDIO_TOKENIZER_MODEL not set");
        return;
    };
    let model = MiMoAudioTokenizer::open(Path::new(&dir)).unwrap();
    let codes: Vec<Vec<i32>> = (0..model.config.num_quantizers)
        .map(|b| {
            (0..3)
                .map(|t| ((b * 7 + t) % model.config.codebook_size[b]) as i32)
                .collect()
        })
        .collect();
    let audio = model.decode(&codes).unwrap();
    assert_eq!(audio.len(), 3 * model.config.downsample_rate());
    assert!(audio.iter().all(|v| v.is_finite()));
}
