//! Fixture parity tests for the Mel-Band RoFormer port.
//!
//! Fixtures live in `testdata/mel_roformer/`, regenerated by
//! `tools/gen_mel_roformer_fixtures.py` against the pinned mlx-audio
//! commit. Tests never download.

use std::path::{Path, PathBuf};

use super::{MelRoFormer, MelRoFormerConfig};
use turbospark_model_io::safetensors::SafetensorsFile;

fn testdata(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata/mel_roformer")
        .join(name)
}

fn read_json(name: &str) -> serde_json::Value {
    let text = std::fs::read_to_string(testdata(name)).expect(name);
    serde_json::from_str(&text).expect(name)
}

fn read_npy(name: &str) -> (Vec<usize>, Vec<f32>) {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    let data = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (shape, data)
}

fn max_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(
        a.len(),
        b.len(),
        "length mismatch {} vs {}",
        a.len(),
        b.len()
    );
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
}

fn load_model() -> MelRoFormer {
    let config = MelRoFormerConfig::from_json(&read_json("config.json")).unwrap();
    let file = SafetensorsFile::open(&testdata("tiny_weights.safetensors")).expect("weights");
    MelRoFormer::load(config, &file).unwrap()
}

#[test]
fn config_parses() {
    let config = MelRoFormerConfig::from_json(&read_json("config.json")).unwrap();
    assert_eq!(config.dim, 32);
    assert_eq!(config.depth, 2);
    assert_eq!(config.heads, 2);
    assert_eq!(config.dim_head, 16);
    assert_eq!(config.num_bands, 24);
    assert_eq!(config.n_fft, 512);
    assert_eq!(config.hop_length, 128);
    assert_eq!(config.freq_bins(), 257);
}

#[test]
fn band_geometry_matches_reference() {
    let config = MelRoFormerConfig::from_json(&read_json("config.json")).unwrap();
    let model = load_model();
    let traces = read_json("traces.json");
    let geometry = &model.band_split.geometry;
    assert_eq!(geometry.band_dims.len(), config.num_bands);
    let golden_dims: Vec<usize> = traces["band_dims"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();
    assert_eq!(geometry.band_dims, golden_dims);
    for (band, indices) in geometry.freq_indices.iter().enumerate() {
        let golden: Vec<usize> = traces[format!("band_{band}_indices").as_str()]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as usize)
            .collect();
        assert_eq!(*indices, golden, "band {band} indices");
    }
}

#[test]
fn stft_matches_reference() {
    let model = load_model();
    let (_, wave) = read_npy("wave.npy");
    let samples = wave.len() / 2;
    let (stft_shape, golden_real) = read_npy("stft_real.npy");
    let (_, golden_imag) = read_npy("stft_imag.npy");
    // Golden layout is [channels, freq, frames] (freq-major planes).
    let freq_bins = stft_shape[1];
    let frames = stft_shape[2];
    let plane = freq_bins * frames;
    for channel in 0..2 {
        let signal: Vec<f32> = wave[channel * samples..(channel + 1) * samples].to_vec();
        let spectra = model.stft_reflect(&signal).unwrap();
        assert_eq!(spectra.len(), frames);
        // Flatten frame-major for comparison against the transposed plane.
        let mut real = Vec::with_capacity(frames * freq_bins);
        let mut imag = Vec::with_capacity(frames * freq_bins);
        for t in 0..frames {
            for value in &spectra[t] {
                real.push(value.re);
                imag.push(value.im);
            }
        }
        let mut gr = vec![0.0f32; plane];
        let mut gi = vec![0.0f32; plane];
        for b in 0..freq_bins {
            for t in 0..frames {
                gr[t * freq_bins + b] = golden_real[channel * plane + b * frames + t];
                gi[t * freq_bins + b] = golden_imag[channel * plane + b * frames + t];
            }
        }
        let gr = &gr;
        let gi = &gi;
        let peak = gr
            .iter()
            .chain(gi)
            .fold(0.0f32, |a, &v| a.max(v.abs()))
            .max(1.0);
        let diff = max_diff(&real, gr);
        eprintln!("stft ch{channel} real diff {diff} peak {peak}");
        assert!(diff < 1e-3 * peak, "stft ch{channel} real diff {diff}");
        let diff = max_diff(&imag, gi);
        assert!(diff < 1e-3 * peak, "stft ch{channel} imag diff {diff}");
    }
}

#[test]
fn band_split_matches_reference() {
    let model = load_model();
    let (_, wave) = read_npy("wave.npy");
    let samples = wave.len() / 2;
    let (stft_shape, golden_real) = read_npy("stft_real.npy");
    let (_, golden_imag) = read_npy("stft_imag.npy");
    let freq_bins = stft_shape[1];
    let frames = stft_shape[2];
    // Rebuild the CaC representation from the golden STFT
    // ([channels, freq, frames] planes).
    let plane = freq_bins * frames;
    let mut stft_repr = vec![0.0f32; freq_bins * 2 * frames * 2];
    for b in 0..freq_bins {
        for t in 0..frames {
            stft_repr[((b * 2) * frames + t) * 2] = golden_real[b * frames + t];
            stft_repr[((b * 2) * frames + t) * 2 + 1] = golden_imag[b * frames + t];
            stft_repr[((b * 2 + 1) * frames + t) * 2] = golden_real[plane + b * frames + t];
            stft_repr[((b * 2 + 1) * frames + t) * 2 + 1] = golden_imag[plane + b * frames + t];
        }
    }
    let config = &model.config;
    let bands = model.band_split.split(&stft_repr, frames, config.dim);
    let (bands_shape, golden_bands) = read_npy("bands.npy");
    assert_eq!(bands.len(), bands_shape.iter().product::<usize>());
    let diff = max_diff(&bands, &golden_bands);
    eprintln!("bands diff {diff}");
    assert!(diff < 5e-4, "bands diff {diff}");
}

#[test]
fn separation_matches_reference() {
    let model = load_model();
    let (_, wave) = read_npy("wave.npy");
    let separated = model.forward(&wave).unwrap();
    let (sep_shape, golden) = read_npy("separated.npy");
    assert_eq!(separated.len(), sep_shape.iter().product::<usize>());
    let peak = golden.iter().fold(0.0f32, |a, &v| a.max(v.abs())).max(1e-6);
    let diff = max_diff(&separated, &golden);
    eprintln!("separated diff {diff} peak {peak}");
    assert!(diff < 5e-3, "separated diff {diff} peak {peak}");
    assert!(separated.iter().all(|v| v.is_finite()));
}

/// The real preset configs must parse and validate (geometry only; the
/// checkpoints themselves are not installed for this gate).
#[test]
fn preset_configs_parse() {
    let json = serde_json::json!({
        "dim": 384, "depth": 6, "heads": 8, "dim_head": 64,
        "num_bands": 60, "n_fft": 2048, "hop_length": 441,
        "sample_rate": 44100, "checkpoint_family": "kim_vocal_2"
    });
    let config = MelRoFormerConfig::from_json(&json).unwrap();
    assert_eq!(config.depth, 6);
    assert_eq!(config.freq_bins(), 1025);
}

#[test]
fn transformer_stage_matches_reference() {
    let model = load_model();
    let (_, wave) = read_npy("wave.npy");
    let samples = wave.len() / 2;
    let (stft_shape, golden_real) = read_npy("stft_real.npy");
    let (_, golden_imag) = read_npy("stft_imag.npy");
    let freq_bins = stft_shape[1];
    let frames = stft_shape[2];
    let plane = freq_bins * frames;
    let mut stft_repr = vec![0.0f32; freq_bins * 2 * frames * 2];
    for b in 0..freq_bins {
        for t in 0..frames {
            stft_repr[((b * 2) * frames + t) * 2] = golden_real[b * frames + t];
            stft_repr[((b * 2) * frames + t) * 2 + 1] = golden_imag[b * frames + t];
            stft_repr[((b * 2 + 1) * frames + t) * 2] = golden_real[plane + b * frames + t];
            stft_repr[((b * 2 + 1) * frames + t) * 2 + 1] = golden_imag[plane + b * frames + t];
        }
    }
    let config = &model.config;
    let num_bands = model.band_split.geometry.band_dims.len();
    let mut x = model.band_split.split(&stft_repr, frames, config.dim);
    for pair in &model.layers {
        let mut time_in = vec![0.0f32; num_bands * frames * config.dim];
        for t in 0..frames {
            for b in 0..num_bands {
                let src = (t * num_bands + b) * config.dim;
                let dst = (b * frames + t) * config.dim;
                time_in[dst..dst + config.dim].copy_from_slice(&x[src..src + config.dim]);
            }
        }
        let time_out = pair[0].forward(&time_in, num_bands, frames);
        for t in 0..frames {
            for b in 0..num_bands {
                let src = (b * frames + t) * config.dim;
                let dst = (t * num_bands + b) * config.dim;
                x[dst..dst + config.dim].copy_from_slice(&time_out[src..src + config.dim]);
            }
        }
        let freq_out = pair[1].forward(&x, frames, num_bands);
        x = freq_out;
    }
    let (tshape, golden) = read_npy("transformer_out.npy");
    assert_eq!(x.len(), tshape.iter().product::<usize>());
    let diff = max_diff(&x, &golden);
    eprintln!("transformer out diff {diff}");
    let _ = samples;
    assert!(diff < 1e-3, "transformer diff {diff}");
}

#[test]
fn mask_and_merge_match_reference() {
    let model = load_model();
    let (tshape, transformer_out) = read_npy("transformer_out.npy");
    let frames = tshape[0];
    let num_bands = tshape[1];
    let dim = tshape[2];
    let masks = model
        .mask_estimator
        .forward(&transformer_out, frames, num_bands, dim);
    for tag in [0usize, 5, num_bands - 1] {
        let (mshape, golden) = read_npy(&format!("mask_band_{tag}.npy"));
        let diff = max_diff(&masks[tag], &golden);
        eprintln!("mask band {tag} diff {diff} (shape {:?})", mshape);
        assert!(diff < 1e-4, "mask band {tag} diff {diff}");
    }
    let full_mask = model.band_split.merge(&masks, frames);
    let (fshape, golden_full) = read_npy("full_mask.npy");
    assert_eq!(full_mask.len(), fshape.iter().product::<usize>());
    let diff = max_diff(&full_mask, &golden_full);
    eprintln!("full mask diff {diff}");
    assert!(diff < 1e-4, "full mask diff {diff}");
}
