//! Fixture parity tests for the BigVGAN port.
//!
//! Fixtures live in `testdata/bigvgan/`, regenerated by
//! `tools/gen_bigvgan_fixtures.py` against the pinned mlx-audio commit.
//! The golden waveforms exercise the weight-norm stack, the transposed
//! convs, the resblock mean, and the anti-aliased snake-beta path with
//! its checkpointed kaiser filters. A local checkpoint directory can
//! be pointed at via TURBOSPARK_BIGVGAN_MODEL and is skipped when
//! absent. Tests never download.

use std::path::{Path, PathBuf};

use super::BigvganConfig;
use crate::codec::bigvgan::Bigvgan;
use turbospark_model_io::safetensors::SafetensorsFile;

fn testdata(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata/bigvgan")
        .join(name)
}

fn read_json(name: &str) -> serde_json::Value {
    let text = std::fs::read_to_string(testdata(name)).expect(name);
    serde_json::from_str(&text).expect(name)
}

fn read_npy(name: &str) -> (Vec<usize>, Vec<f32>) {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    let data = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (shape, data)
}

fn max_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(
        a.len(),
        b.len(),
        "length mismatch: {} vs {}",
        a.len(),
        b.len()
    );
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
}

fn load_tiny() -> Bigvgan {
    let config = read_json("tiny_config.json");
    let config = BigvganConfig::from_json(&config).expect("config parses");
    let file = SafetensorsFile::open(&testdata("tiny_weights.safetensors")).expect("weights open");
    Bigvgan::load(config, &file).expect("load")
}

#[test]
fn snake_activation_is_refused() {
    let mut config = read_json("tiny_config.json");
    config["activation"] = serde_json::json!("snake");
    let config = BigvganConfig::from_json(&config).unwrap();
    let file = SafetensorsFile::open(&testdata("tiny_weights.safetensors")).unwrap();
    let Err(err) = Bigvgan::load(config, &file) else {
        panic!("snake activation must be refused");
    };
    assert!(err.to_string().contains("snakebeta"), "{err}");
}

#[test]
fn tiny_end_to_end_matches_reference() {
    let model = load_tiny();
    let traces = read_json("traces.json");
    for tag in ["a", "b"] {
        let (mel_shape, mel) = read_npy(&format!("{tag}_mel.npy"));
        assert_eq!(mel_shape, vec![1, model.config.num_mels, mel_shape[2]]);
        let frames = mel_shape[2];
        let audio = model.forward(&mel, frames).unwrap();
        let (_, golden) = read_npy(&format!("{tag}_audio.npy"));
        assert_eq!(
            audio.len() as i64,
            traces[format!("{tag}_audio_len").as_str()]
                .as_i64()
                .unwrap()
        );
        assert_eq!(audio.len(), golden.len());
        assert!(
            max_diff(&audio, &golden) < 1e-4,
            "{tag} audio diff {}",
            max_diff(&audio, &golden)
        );
        assert!(audio.iter().all(|v| v.abs() <= 1.0));
    }
}

/// Real-checkpoint gate; opt-in via TURBOSPARK_BIGVGAN_MODEL pointing
/// at a directory with config.json + model.safetensors. Skips when
/// unset.
#[test]
fn real_checkpoint_gate() {
    let Ok(dir) = std::env::var("TURBOSPARK_BIGVGAN_MODEL") else {
        eprintln!("skipping: TURBOSPARK_BIGVGAN_MODEL not set");
        return;
    };
    let model = Bigvgan::open(std::path::Path::new(&dir)).unwrap();
    let (mel_shape, _mel) = read_npy("a_mel.npy");
    let mels = model.config.num_mels;
    assert_eq!(mel_shape[1], mels);
    // Reuse the fixture mel widths when they disagree with the real
    // config: build a deterministic mel-shaped input instead.
    let frames = mel_shape[2];
    let input: Vec<f32> = (0..mels * frames)
        .map(|i| ((i % frames) as f32 * 0.05).sin())
        .collect();
    let audio = model.forward(&input, frames).unwrap();
    let expected = frames * model.config.upsample_rates.iter().product::<usize>();
    assert_eq!(audio.len(), expected);
    assert!(audio.iter().all(|v| v.is_finite()));
}
