//! Fixture parity tests for the DACVAE port.
//!
//! Fixtures live in `testdata/dacvae/`, regenerated by
//! `tools/gen_dacvae_fixtures.py` against the pinned mlx-audio commit.
//! The non-watermark batch encode/decode contract is gated end to end.
//! A real checkpoint directory can be pointed at via
//! TURBOSPARK_DACVAE_MODEL and is skipped when absent. Tests never
//! download.

use std::path::{Path, PathBuf};

use super::{Dacvae, DacvaeConfig};
use turbospark_model_io::safetensors::SafetensorsFile;

fn testdata(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata/dacvae")
        .join(name)
}

fn read_json(name: &str) -> serde_json::Value {
    let text = std::fs::read_to_string(testdata(name)).expect(name);
    serde_json::from_str(&text).expect(name)
}

fn read_npy(name: &str) -> (Vec<usize>, Vec<f32>) {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    let data = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (shape, data)
}

fn max_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(
        a.len(),
        b.len(),
        "length mismatch: {} vs {}",
        a.len(),
        b.len()
    );
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
}

fn load_tiny() -> Dacvae {
    let config = read_json("tiny_config.json");
    let config = DacvaeConfig::from_json(&config).expect("config parses");
    let file = SafetensorsFile::open(&testdata("tiny_weights.safetensors")).expect("weights open");
    Dacvae::load(config, &file).expect("load")
}

#[test]
fn config_defaults_match_reference() {
    let config = DacvaeConfig::from_json(&serde_json::json!({})).unwrap();
    assert_eq!(config.encoder_dim, 64);
    assert_eq!(config.encoder_rates, vec![2, 8, 10, 12]);
    assert_eq!(config.latent_dim, 1024);
    assert_eq!(config.decoder_dim, 1536);
    assert_eq!(config.decoder_rates, vec![12, 10, 8, 2]);
    assert_eq!(config.codebook_dim, 128);
    assert_eq!(config.sample_rate, 48000);
    assert_eq!(config.hop_length(), 1920);
}

#[test]
fn tiny_end_to_end_matches_reference() {
    let model = load_tiny();
    let traces = read_json("traces.json");
    for tag in ["a", "b"] {
        let (_, wave) = read_npy(&format!("{tag}_wave.npy"));
        let latents = model.encode(&wave).unwrap();
        let (l_shape, golden_latents) = read_npy(&format!("{tag}_latents.npy"));
        // Python latents (B, codebook_dim, frames) == channel-major.
        assert_eq!(l_shape, vec![1, model.config.codebook_dim, l_shape[2]]);
        assert_eq!(latents.len(), golden_latents.len());
        let rel = max_diff(&latents, &golden_latents)
            / golden_latents.iter().fold(0.0f32, |a, v| a.max(v.abs()));
        assert!(rel < 1e-5, "{tag} latents relative diff {rel}");

        assert_eq!(
            model.padded_len(wave.len()) as i64,
            traces[format!("{tag}_audio_len").as_str()]
                .as_i64()
                .unwrap()
        );
        let audio = model.decode(&latents).unwrap();
        let (_, golden_audio) = read_npy(&format!("{tag}_audio.npy"));
        assert_eq!(audio.len(), golden_audio.len());
        let rel = max_diff(&audio, &golden_audio)
            / golden_audio.iter().fold(0.0f32, |a, v| a.max(v.abs()));
        assert!(rel < 1e-5, "{tag} audio relative diff {rel}");
        assert!(audio.iter().all(|v| v.abs() <= 1.0 + 1e-5));
    }
}

/// Real-checkpoint gate; opt-in via TURBOSPARK_DACVAE_MODEL pointing
/// at a directory with config.json + model.safetensors. Skips when
/// unset.
#[test]
fn real_checkpoint_gate() {
    let Ok(dir) = std::env::var("TURBOSPARK_DACVAE_MODEL") else {
        eprintln!("skipping: TURBOSPARK_DACVAE_MODEL not set");
        return;
    };
    let model = Dacvae::open(Path::new(&dir)).unwrap();
    let wave: Vec<f32> = (0..model.config.hop_length() * 2)
        .map(|i| ((i as f32) * 220.0 * std::f32::consts::TAU / 48000.0).sin() * 0.2)
        .collect();
    let latents = model.encode(&wave).unwrap();
    assert_eq!(latents.len() / model.config.codebook_dim, 2);
    let audio = model.decode(&latents).unwrap();
    assert_eq!(audio.len(), model.padded_len(wave.len()));
    assert!(audio.iter().all(|v| v.is_finite()));
}
