//! Fixture parity tests for the Mimi codec port.
//!
//! Fixtures live in `testdata/mimi/`, regenerated by
//! `tools/gen_mimi_fixtures.py` against the pinned mlx-audio commit.
//! Codes are exact-equality gates protected by recorded half-norm
//! distance margins; tensors are float-tolerant. A real checkpoint
//! (the kyutai tokenizer safetensors) can be pointed at via
//! TURBOSPARK_MIMI_MODEL and is skipped when absent; tests never
//! download.

use std::path::{Path, PathBuf};

use super::{Mimi, MimiConfig};
use turbospark_model_io::safetensors::SafetensorsFile;

fn testdata(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata/mimi")
        .join(name)
}

fn read_json(name: &str) -> serde_json::Value {
    let text = std::fs::read_to_string(testdata(name)).expect(name);
    serde_json::from_str(&text).expect(name)
}

fn read_npy(name: &str) -> (Vec<usize>, Vec<f32>) {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    let data = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (shape, data)
}

fn read_npy_abs(name: &str) -> (Vec<usize>, Vec<f32>) {
    let bytes = std::fs::read(name).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    let data = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (shape, data)
}

fn floats(value: &serde_json::Value) -> Vec<f32> {
    value
        .as_array()
        .expect("float array")
        .iter()
        .map(|v| v.as_f64().expect("f64") as f32)
        .collect()
}

fn code_levels(value: &serde_json::Value) -> Vec<Vec<i32>> {
    value
        .as_array()
        .expect("levels")
        .iter()
        .map(|level| {
            level
                .as_array()
                .expect("level")
                .iter()
                .map(|v| v.as_i64().expect("i64") as i32)
                .collect()
        })
        .collect()
}

fn max_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(
        a.len(),
        b.len(),
        "length mismatch: {} vs {}",
        a.len(),
        b.len()
    );
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
}

fn load_tiny() -> Mimi {
    let config = read_json("tiny_config.json");
    let config = MimiConfig::from_json(&config).expect("config parses");
    let file = SafetensorsFile::open(&testdata("tiny_weights.safetensors")).expect("weights open");
    Mimi::load(config, &file).expect("load")
}

/// Golden codes live as (B, nq, T); flatten to per-level vectors.
fn golden_codes(tag: &str) -> Vec<Vec<i32>> {
    let (shape, data) = read_npy(&format!("{tag}_codes.npy"));
    let nq = shape[1];
    let frames = shape[2];
    (0..nq)
        .map(|level| {
            (0..frames)
                .map(|f| data[level * frames + f] as i32)
                .collect()
        })
        .collect()
}

#[test]
fn mimi_202407_factory_defaults() {
    let config = MimiConfig::mimi_202407(32);
    assert_eq!(config.seanet.dimension, 512);
    assert_eq!(config.seanet.nfilters, 64);
    assert_eq!(config.seanet.ratios, vec![8, 6, 5, 4]);
    assert_eq!(config.seanet.ksize, 7);
    assert_eq!(config.seanet.last_ksize, 3);
    assert!(config.seanet.causal);
    assert!(config.seanet.true_skip);
    assert_eq!(config.transformer.num_heads, 8);
    assert_eq!(config.transformer.num_layers, 8);
    assert_eq!(config.transformer.context, 250);
    assert_eq!(config.transformer.dim_feedforward, 2048);
    assert_eq!(config.quantizer_bins, 2048);
    assert_eq!(config.quantizer_dim, 256);
    // frame rate: 24000 / (8*6*5*4) = 25 encoder fps, / 2 downsample.
    let encoder_fps = config.sample_rate / config.seanet.ratios.iter().product::<usize>() as f32;
    assert_eq!((encoder_fps / config.frame_rate) as usize, 2);
}

#[test]
fn tiny_end_to_end_matches_reference() {
    let model = load_tiny();
    let traces = read_json("traces.json");

    for tag in ["a", "b"] {
        let (wave_shape, wave) = read_npy(&format!("{tag}_wave.npy"));
        assert_eq!(wave_shape.len(), 1);
        let codes = model.encode(&wave).unwrap();
        let golden_codes = golden_codes(tag);
        assert_eq!(codes.len(), golden_codes.len());
        for (got, want) in codes.iter().zip(&golden_codes) {
            assert_eq!(got, want, "{tag} code level mismatch");
        }

        // Margins keep the exact-index gates honest (first codebook).
        let best = traces[format!("{tag}_vq_margins")]["best"]
            .as_array()
            .unwrap();
        let second = traces[format!("{tag}_vq_margins")]["second"]
            .as_array()
            .unwrap();
        for (b, s) in best.iter().zip(second) {
            let b = b.as_f64().unwrap();
            let s = s.as_f64().unwrap();
            assert!(s - b > 1e-6, "{tag} margin {s} - {b} too small");
        }

        let audio = model.decode(&codes).unwrap();
        let (_, golden_audio) = read_npy(&format!("{tag}_audio.npy"));
        assert_eq!(
            audio.len() as i64,
            traces[format!("{tag}_audio_len").as_str()]
                .as_i64()
                .unwrap()
        );
        assert_eq!(audio.len(), golden_audio.len());
        // The random-weight tiny decoder amplifies latents to ~1e10, so
        // the waveform gate is relative (absolute f32 error at that
        // scale is orders of magnitude above any fixed tolerance).
        let golden_max = golden_audio.iter().fold(0.0f32, |a, v| a.max(v.abs()));
        let rel = max_diff(&audio, &golden_audio) / golden_max;
        assert!(rel < 1e-4, "{tag} audio relative diff {rel}");
    }
}

#[test]
fn isolated_transformer_matches_reference() {
    let model = load_tiny();
    let (shape, tf_in) = read_npy("tf_in.npy");
    // Python trace input is (B, C, T) NCL == channel-major here.
    assert_eq!(shape, vec![1, model.config.seanet.dimension, 24]);
    let frames = shape[2];
    let out = model.encoder_transformer.forward(&tf_in, frames);
    let (_, golden) = read_npy("tf_out.npy");
    assert_eq!(out.len(), golden.len());
    assert!(
        max_diff(&out, &golden) < 1e-4,
        "transformer diff {}",
        max_diff(&out, &golden)
    );
}

/// Real-checkpoint gate; opt-in via TURBOSPARK_MIMI_MODEL pointing at
/// the kyutai tokenizer safetensors file plus a sidecar config. The
/// full 512-dim model is heavy; this only checks the loader wiring
/// and finite decode on a short input. Skips when unset.
#[test]
fn real_checkpoint_gate() {
    let Ok(path) = std::env::var("TURBOSPARK_MIMI_MODEL") else {
        eprintln!("skipping: TURBOSPARK_MIMI_MODEL not set");
        return;
    };
    let config = MimiConfig::mimi_202407(32);
    let file = SafetensorsFile::open(Path::new(&path)).expect("checkpoint opens");
    let model = Mimi::load(config, &file).expect("loads");
    let wave: Vec<f32> = (0..9600)
        .map(|i| ((i as f32) * 220.0 * std::f32::consts::TAU / 24000.0).sin() * 0.2)
        .collect();
    let codes = model.encode(&wave).unwrap();
    assert_eq!(codes.len(), 32);
    let audio = model.decode(&codes).unwrap();
    assert!(audio.iter().all(|v| v.is_finite()));
    assert!(audio.iter().all(|v| v.abs() <= 1.0 + 1e-4));
}

// ---------------------------------------------------------------------
// Bitwise parity of the flat-output attention (shared rope tables, one
// reused score row) against the original (kept verbatim below).
// ---------------------------------------------------------------------

use super::TransformerLayer;
use crate::ops;

/// MLX `nn.RoPE(traditional=True)`: interleaved pairs rotated with
/// per-pair frequencies `base^(-2i / dim)` at absolute positions
/// `offset..offset + seq`. `x` is `[heads, seq, dim]`.
fn apply_traditional_rope_reference(
    x: &mut [f32],
    heads: usize,
    seq: usize,
    dim: usize,
    offset: usize,
    base: f32,
) {
    let half = dim / 2;
    for head in 0..heads {
        for t in 0..seq {
            let position = (offset + t) as f32;
            let ro = (head * seq + t) * dim;
            for d in 0..half {
                let freq = base.powf(-2.0 * d as f32 / dim as f32);
                let angle = position * freq;
                let (c, s) = (angle.cos(), angle.sin());
                let a = x[ro + 2 * d];
                let b = x[ro + 2 * d + 1];
                x[ro + 2 * d] = a * c - b * s;
                x[ro + 2 * d + 1] = b * c + a * s;
            }
        }
    }
}

fn attention_reference(
    layer: &TransformerLayer,
    x: &[f32],
    frames: usize,
    pos_offset: usize,
) -> Vec<Vec<f32>> {
    let this = layer;
    let d = this.d_model;
    let h = this.heads;
    let hd = this.head_dim;
    // Packed qkv over frames: rows [t][3d].
    let mut qkv = vec![0.0f32; frames * 3 * d];
    for t in 0..frames {
        for o in 0..3 * d {
            let wr = &this.in_proj_w[o * d..(o + 1) * d];
            let mut acc = 0.0f32;
            for c in 0..d {
                acc += x[c * frames + t] * wr[c];
            }
            qkv[t * 3 * d + o] = acc;
        }
    }
    // Split into per-head q/k/v [head, frame, hd].
    let mut q = vec![0.0f32; h * frames * hd];
    let mut k = vec![0.0f32; h * frames * hd];
    let mut v = vec![0.0f32; h * frames * hd];
    for t in 0..frames {
        for head in 0..h {
            for dd in 0..hd {
                let o = (head * hd) + dd;
                q[(head * frames + t) * hd + dd] = qkv[t * 3 * d + o];
                k[(head * frames + t) * hd + dd] = qkv[t * 3 * d + d + o];
                v[(head * frames + t) * hd + dd] = qkv[t * 3 * d + 2 * d + o];
            }
        }
    }
    // Traditional (interleaved) RoPE at the absolute positions:
    // pair (x[2i], x[2i+1]) rotated by position * base^(-2i/hd)
    // (the nn.RoPE(traditional=True) contract).
    apply_traditional_rope_reference(&mut q, h, frames, hd, pos_offset, this.rope_base);
    apply_traditional_rope_reference(&mut k, h, frames, hd, pos_offset, this.rope_base);
    // Causal attention with the context bound.
    let scale = 1.0 / (hd as f32).sqrt();
    let mut out = vec![0.0f32; h * frames * hd];
    for head in 0..h {
        for t in 0..frames {
            let mut scores = vec![0.0f32; t + 1];
            for s in 0..=t {
                let delta = pos_offset + t - (pos_offset + s);
                let allowed = delta < this.context;
                if !allowed {
                    scores[s] = f32::NEG_INFINITY;
                    continue;
                }
                let mut acc = 0.0f32;
                for dd in 0..hd {
                    acc += q[(head * frames + t) * hd + dd] * k[(head * frames + s) * hd + dd];
                }
                scores[s] = acc * scale;
            }
            ops::softmax_row(&mut scores);
            for dd in 0..hd {
                let mut acc = 0.0f32;
                for s in 0..=t {
                    acc += scores[s] * v[(head * frames + s) * hd + dd];
                }
                out[(head * frames + t) * hd + dd] = acc;
            }
        }
    }
    // Concat heads and apply out_proj per frame.
    let mut concat = vec![0.0f32; frames * d];
    for t in 0..frames {
        for head in 0..h {
            for dd in 0..hd {
                concat[t * d + head * hd + dd] = out[(head * frames + t) * hd + dd];
            }
        }
    }
    let mut outs = Vec::with_capacity(frames);
    for t in 0..frames {
        let mut o = vec![0.0f32; d];
        for (oi, ow) in o.iter_mut().enumerate() {
            let wr = &this.out_proj_w[oi * d..(oi + 1) * d];
            let mut acc = 0.0f32;
            for c in 0..d {
                acc += concat[t * d + c] * wr[c];
            }
            *ow = acc;
        }
        outs.push(o);
    }
    outs
}

/// Deterministic xorshift stream with ~1 in 6 exact zeros; avoids a
/// dev-dependency.
struct Rng(u64);

impl Rng {
    fn value(&mut self) -> f32 {
        self.0 ^= self.0 << 13;
        self.0 ^= self.0 >> 7;
        self.0 ^= self.0 << 17;
        let r = self.0;
        if r % 6 == 0 {
            return 0.0;
        }
        (((r >> 8) % 20001) as f32 / 10000.0 - 1.0) * [0.05f32, 0.5, 1.0][((r >> 40) % 3) as usize]
    }

    fn vec(&mut self, n: usize) -> Vec<f32> {
        (0..n).map(|_| self.value()).collect()
    }
}

fn parity_layer(rng: &mut Rng, d: usize, heads: usize, context: usize) -> TransformerLayer {
    TransformerLayer {
        in_proj_w: rng.vec(3 * d * d),
        out_proj_w: rng.vec(d * d),
        norm1_w: Vec::new(),
        norm1_b: Vec::new(),
        norm2_w: Vec::new(),
        norm2_b: Vec::new(),
        linear1_w: Vec::new(),
        linear2_w: Vec::new(),
        layer_scale_1: Vec::new(),
        layer_scale_2: Vec::new(),
        d_model: d,
        heads,
        head_dim: d / heads,
        context,
        rope_base: 10000.0,
    }
}

#[test]
fn attention_matches_original_bitwise() {
    let mut rng = Rng(0x9e37_79b9_7f4a_7c15);
    // (d_model, heads, frames, context, pos_offset): covers a context
    // shorter than the sequence, a context longer than it, one frame,
    // and a nonzero streaming offset.
    for &(d, heads, frames, context, offset) in &[
        (16usize, 2usize, 1usize, 8usize, 0usize),
        (16, 2, 9, 4, 0),
        (32, 4, 13, 100, 0),
        (32, 4, 13, 5, 7),
        (24, 3, 31, 6, 1000),
    ] {
        let layer = parity_layer(&mut rng, d, heads, context);
        let x = rng.vec(d * frames);
        let want = attention_reference(&layer, &x, frames, offset);
        let got = layer.attention(&x, frames, offset);
        assert_eq!(got.len(), frames * d);
        for (t, row) in want.iter().enumerate() {
            for (c, w) in row.iter().enumerate() {
                assert_eq!(
                    got[t * d + c].to_bits(),
                    w.to_bits(),
                    "d={d} heads={heads} frames={frames} ctx={context} off={offset} t={t} c={c}"
                );
            }
        }
    }
}
