//! Fixture parity tests for the Mimi codec port.
//!
//! Fixtures live in `testdata/mimi/`, regenerated by
//! `tools/gen_mimi_fixtures.py` against the pinned mlx-audio commit.
//! Codes are exact-equality gates protected by recorded half-norm
//! distance margins; tensors are float-tolerant. A real checkpoint
//! (the kyutai tokenizer safetensors) can be pointed at via
//! TURBOSPARK_MIMI_MODEL and is skipped when absent; tests never
//! download.

use std::path::{Path, PathBuf};

use super::{Mimi, MimiConfig};
use turbospark_model_io::safetensors::SafetensorsFile;

fn testdata(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata/mimi")
        .join(name)
}

fn read_json(name: &str) -> serde_json::Value {
    let text = std::fs::read_to_string(testdata(name)).expect(name);
    serde_json::from_str(&text).expect(name)
}

fn read_npy(name: &str) -> (Vec<usize>, Vec<f32>) {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    let data = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (shape, data)
}

fn read_npy_abs(name: &str) -> (Vec<usize>, Vec<f32>) {
    let bytes = std::fs::read(name).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    let data = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (shape, data)
}

fn floats(value: &serde_json::Value) -> Vec<f32> {
    value
        .as_array()
        .expect("float array")
        .iter()
        .map(|v| v.as_f64().expect("f64") as f32)
        .collect()
}

fn code_levels(value: &serde_json::Value) -> Vec<Vec<i32>> {
    value
        .as_array()
        .expect("levels")
        .iter()
        .map(|level| {
            level
                .as_array()
                .expect("level")
                .iter()
                .map(|v| v.as_i64().expect("i64") as i32)
                .collect()
        })
        .collect()
}

fn max_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(
        a.len(),
        b.len(),
        "length mismatch: {} vs {}",
        a.len(),
        b.len()
    );
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
}

fn load_tiny() -> Mimi {
    let config = read_json("tiny_config.json");
    let config = MimiConfig::from_json(&config).expect("config parses");
    let file = SafetensorsFile::open(&testdata("tiny_weights.safetensors")).expect("weights open");
    Mimi::load(config, &file).expect("load")
}

/// Golden codes live as (B, nq, T); flatten to per-level vectors.
fn golden_codes(tag: &str) -> Vec<Vec<i32>> {
    let (shape, data) = read_npy(&format!("{tag}_codes.npy"));
    let nq = shape[1];
    let frames = shape[2];
    (0..nq)
        .map(|level| {
            (0..frames)
                .map(|f| data[level * frames + f] as i32)
                .collect()
        })
        .collect()
}

#[test]
fn mimi_202407_factory_defaults() {
    let config = MimiConfig::mimi_202407(32);
    assert_eq!(config.seanet.dimension, 512);
    assert_eq!(config.seanet.nfilters, 64);
    assert_eq!(config.seanet.ratios, vec![8, 6, 5, 4]);
    assert_eq!(config.seanet.ksize, 7);
    assert_eq!(config.seanet.last_ksize, 3);
    assert!(config.seanet.causal);
    assert!(config.seanet.true_skip);
    assert_eq!(config.transformer.num_heads, 8);
    assert_eq!(config.transformer.num_layers, 8);
    assert_eq!(config.transformer.context, 250);
    assert_eq!(config.transformer.dim_feedforward, 2048);
    assert_eq!(config.quantizer_bins, 2048);
    assert_eq!(config.quantizer_dim, 256);
    // frame rate: 24000 / (8*6*5*4) = 25 encoder fps, / 2 downsample.
    let encoder_fps = config.sample_rate / config.seanet.ratios.iter().product::<usize>() as f32;
    assert_eq!((encoder_fps / config.frame_rate) as usize, 2);
}

#[test]
fn tiny_end_to_end_matches_reference() {
    let model = load_tiny();
    let traces = read_json("traces.json");

    for tag in ["a", "b"] {
        let (wave_shape, wave) = read_npy(&format!("{tag}_wave.npy"));
        assert_eq!(wave_shape.len(), 1);
        let codes = model.encode(&wave).unwrap();
        let golden_codes = golden_codes(tag);
        assert_eq!(codes.len(), golden_codes.len());
        for (got, want) in codes.iter().zip(&golden_codes) {
            assert_eq!(got, want, "{tag} code level mismatch");
        }

        // Margins keep the exact-index gates honest (first codebook).
        let best = traces[format!("{tag}_vq_margins")]["best"]
            .as_array()
            .unwrap();
        let second = traces[format!("{tag}_vq_margins")]["second"]
            .as_array()
            .unwrap();
        for (b, s) in best.iter().zip(second) {
            let b = b.as_f64().unwrap();
            let s = s.as_f64().unwrap();
            assert!(s - b > 1e-6, "{tag} margin {s} - {b} too small");
        }

        let audio = model.decode(&codes).unwrap();
        let (_, golden_audio) = read_npy(&format!("{tag}_audio.npy"));
        assert_eq!(
            audio.len() as i64,
            traces[format!("{tag}_audio_len").as_str()]
                .as_i64()
                .unwrap()
        );
        assert_eq!(audio.len(), golden_audio.len());
        // The random-weight tiny decoder amplifies latents to ~1e10, so
        // the waveform gate is relative (absolute f32 error at that
        // scale is orders of magnitude above any fixed tolerance).
        let golden_max = golden_audio.iter().fold(0.0f32, |a, v| a.max(v.abs()));
        let rel = max_diff(&audio, &golden_audio) / golden_max;
        assert!(rel < 1e-4, "{tag} audio relative diff {rel}");
    }
}

#[test]
fn isolated_transformer_matches_reference() {
    let model = load_tiny();
    let (shape, tf_in) = read_npy("tf_in.npy");
    // Python trace input is (B, C, T) NCL == channel-major here.
    assert_eq!(shape, vec![1, model.config.seanet.dimension, 24]);
    let frames = shape[2];
    let out = model.encoder_transformer.forward(&tf_in, frames);
    let (_, golden) = read_npy("tf_out.npy");
    assert_eq!(out.len(), golden.len());
    assert!(
        max_diff(&out, &golden) < 1e-4,
        "transformer diff {}",
        max_diff(&out, &golden)
    );
}

/// Real-checkpoint gate; opt-in via TURBOSPARK_MIMI_MODEL pointing at
/// the kyutai tokenizer safetensors file plus a sidecar config. The
/// full 512-dim model is heavy; this only checks the loader wiring
/// and finite decode on a short input. Skips when unset.
#[test]
fn real_checkpoint_gate() {
    let Ok(path) = std::env::var("TURBOSPARK_MIMI_MODEL") else {
        eprintln!("skipping: TURBOSPARK_MIMI_MODEL not set");
        return;
    };
    let config = MimiConfig::mimi_202407(32);
    let file = SafetensorsFile::open(Path::new(&path)).expect("checkpoint opens");
    let model = Mimi::load(config, &file).expect("loads");
    let wave: Vec<f32> = (0..9600)
        .map(|i| ((i as f32) * 220.0 * std::f32::consts::TAU / 24000.0).sin() * 0.2)
        .collect();
    let codes = model.encode(&wave).unwrap();
    assert_eq!(codes.len(), 32);
    let audio = model.decode(&codes).unwrap();
    assert!(audio.iter().all(|v| v.is_finite()));
    assert!(audio.iter().all(|v| v.abs() <= 1.0 + 1e-4));
}
