//! Fixture parity tests for the EnCodec port.
//!
//! Fixtures live in `testdata/encodec/`, regenerated by
//! `tools/gen_encodec_fixtures.py` against the pinned mlx-audio commit.
//! Codes are exact-equality gates protected by recorded Euclidean
//! distance margins; tensors are float-tolerant. A local checkpoint
//! directory can be pointed at via TURBOSPARK_ENCODEC_MODEL and is
//! skipped when absent. Tests never download.

use std::path::{Path, PathBuf};

use super::{Encodec, EncodecConfig};
use turbospark_model_io::safetensors::SafetensorsFile;

fn testdata(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata/encodec")
        .join(name)
}

fn read_json(name: &str) -> serde_json::Value {
    let text = std::fs::read_to_string(testdata(name)).expect(name);
    serde_json::from_str(&text).expect(name)
}

/// Read a little-endian f32 .npy (the shared testdata convention).
fn read_npy(name: &str) -> (Vec<usize>, Vec<f32>) {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    let data = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (shape, data)
}

fn floats(value: &serde_json::Value) -> Vec<f32> {
    value
        .as_array()
        .expect("float array")
        .iter()
        .map(|v| v.as_f64().expect("f64") as f32)
        .collect()
}

fn code_levels(value: &serde_json::Value) -> Vec<Vec<i32>> {
    value
        .as_array()
        .expect("levels")
        .iter()
        .map(|level| {
            level
                .as_array()
                .expect("level")
                .iter()
                .map(|v| v.as_i64().expect("i64") as i32)
                .collect()
        })
        .collect()
}

fn max_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(
        a.len(),
        b.len(),
        "length mismatch: {} vs {}",
        a.len(),
        b.len()
    );
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
}

fn load_tiny() -> Encodec {
    let config = read_json("tiny_config.json");
    let config = EncodecConfig::from_json(&config).expect("config parses");
    let file = SafetensorsFile::open(&testdata("tiny_weights.safetensors")).expect("weights open");
    Encodec::load(config, &file).expect("load")
}

#[test]
fn config_defaults_match_reference() {
    let config = EncodecConfig::from_json(&serde_json::json!({})).unwrap();
    assert_eq!(config.audio_channels, 1);
    assert_eq!(config.num_filters, 32);
    assert_eq!(config.kernel_size, 7);
    assert_eq!(config.num_residual_layers, 1);
    assert_eq!(config.codebook_size, 1024);
    assert_eq!(config.codebook_dim, 128);
    assert_eq!(config.hidden_size, 128);
    assert_eq!(config.num_lstm_layers, 2);
    assert!(config.use_causal_conv);
    assert!(!config.normalize);
    assert_eq!(config.pad_mode, "reflect");
    assert_eq!(config.norm_type, "weight_norm");
    assert_eq!(config.compress, 2);
    assert_eq!(config.upsampling_ratios, vec![8, 8, 4, 2]);
    assert_eq!(config.sampling_rate, 24000);
    assert_eq!(config.hop_length(), 512);
}

#[test]
fn tiny_end_to_end_matches_reference() {
    let model = load_tiny();
    let traces = read_json("traces.json");
    assert_eq!(
        model.frame_rate() as i64,
        traces["frame_rate"].as_i64().unwrap()
    );
    assert_eq!(
        model.quantizer.num_quantizers as i64,
        traces["num_quantizers"].as_i64().unwrap()
    );

    for (tag, _zq_file, audio_file) in [
        ("a", "a_zq.npy", "a_audio.npy"),
        ("b", "b_zq.npy", "b_audio.npy"),
    ] {
        let wave = floats(&traces[format!("{tag}_wave").as_str()]);
        let codes = model.encode(&wave, None).unwrap();
        let golden_codes = code_levels(&traces[format!("{tag}_codes").as_str()]);
        assert_eq!(codes.len(), golden_codes.len());
        for (got, want) in codes.iter().zip(&golden_codes) {
            assert_eq!(got, want, "{tag} code level mismatch");
        }

        // Second bandwidth selects a deeper residual stack.
        let bw = read_json("tiny_config.json")["target_bandwidths"][1]
            .as_f64()
            .unwrap();
        let codes_bw = model.encode(&wave, Some(bw)).unwrap();
        let golden_bw = code_levels(&traces[format!("{tag}_codes_bw").as_str()]);
        assert_eq!(codes_bw.len(), golden_bw.len());
        for (got, want) in codes_bw.iter().zip(&golden_bw) {
            assert_eq!(got, want, "{tag} bw code level mismatch");
        }

        // Margins keep the exact-index gates honest (level 0).
        let best = traces[format!("{tag}_vq_margins")]["best"]
            .as_array()
            .unwrap();
        let second = traces[format!("{tag}_vq_margins")]["second"]
            .as_array()
            .unwrap();
        for (b, s) in best.iter().zip(second) {
            let b = b.as_f64().unwrap();
            let s = s.as_f64().unwrap();
            assert!(s - b > 1e-5, "{tag} margin {s} - {b} too small");
        }

        // Quantized latents through the public decode path.
        let audio = model.decode_codes(&codes, None).unwrap();
        let (_, golden_audio) = read_npy(audio_file);
        assert_eq!(audio.len(), golden_audio.len());
        assert!(max_diff(&audio, &golden_audio) < 1e-4, "{tag} audio diff");
    }
}

#[test]
fn isolated_lstm_matches_reference() {
    let model = load_tiny();
    let (shape, lstm_in) = read_npy("lstm_in.npy");
    // Python input (1, T, dim) channels-last; the encoder LSTM dim is
    // scaling * num_filters.
    let dim = model.config.num_filters * (1 << model.config.upsampling_ratios.len());
    assert_eq!(shape, vec![1, shape.get(1).copied().unwrap_or(0), dim]);
    let t = shape[1];
    // (B, T, C) -> [C, T]
    let mut x = vec![0.0f32; dim * t];
    for ti in 0..t {
        for ci in 0..dim {
            x[ci * t + ti] = lstm_in[ti * dim + ci];
        }
    }
    // The encoder LSTM is the third-to-last layer.
    let Some(super::EncLayer::Lstm(lstm)) = model.encoder.layers.iter().rev().nth(2) else {
        panic!("encoder LSTM layer not found");
    };
    let out = lstm.forward(&x);
    let (_, golden) = read_npy("lstm_out.npy");
    // [C, T] -> (B, T, C)
    let mut out_t = vec![0.0f32; dim * t];
    for ti in 0..t {
        for ci in 0..dim {
            out_t[ti * dim + ci] = out[ci * t + ti];
        }
    }
    assert_eq!(out_t.len(), golden.len());
    assert!(max_diff(&out_t, &golden) < 1e-5, "lstm diff");
}

/// Real-checkpoint gate; opt-in via TURBOSPARK_ENCODEC_MODEL pointing
/// at a directory with config.json + model.safetensors. Skips when
/// unset. Only sanity properties are asserted (no committed golden for
/// a real EnCodec checkpoint).
#[test]
fn real_checkpoint_gate() {
    let Ok(dir) = std::env::var("TURBOSPARK_ENCODEC_MODEL") else {
        eprintln!("skipping: TURBOSPARK_ENCODEC_MODEL not set");
        return;
    };
    let model = Encodec::open(Path::new(&dir)).unwrap();
    let wave: Vec<f32> = (0..24000)
        .map(|i| ((i as f32) * 440.0 * std::f32::consts::TAU / 24000.0).sin() * 0.3)
        .collect();
    let codes = model.encode(&wave, None).unwrap();
    let audio = model.decode_codes(&codes, None).unwrap();
    assert_eq!(audio.len(), model.config.hop_length() * codes[0].len());
    assert!(audio.iter().all(|v| v.is_finite()));
}

// ---------------------------------------------------------------------
// Bitwise parity of the allocation-trimmed LSTM against the original
// per-step implementation (kept verbatim below).
// ---------------------------------------------------------------------

use super::{stable_sigmoid, Lstm};

#[allow(clippy::needless_range_loop)]
fn lstm_forward_reference(this: &Lstm, x: &[f32]) -> Vec<f32> {
    let t = x.len() / this.in_dim;
    let h = this.hidden;
    // Pre-map inputs: pre_x[t][j] = bias[j] + sum_i x[i, t] * wx[j, i].
    let mut pre_x = vec![0.0f32; t * 4 * h];
    for step in 0..t {
        for j in 0..4 * h {
            let mut acc = this.bias.as_deref().map_or(0.0, |b| b[j]);
            let w_row = &this.wx[j * this.in_dim..(j + 1) * this.in_dim];
            for i in 0..this.in_dim {
                acc += x[i * t + step] * w_row[i];
            }
            pre_x[step * 4 * h + j] = acc;
        }
    }
    let mut out = vec![0.0f32; h * t];
    let mut cell = vec![0.0f32; h];
    // h_pre is the (4H) hidden-side gate input; the reference skips
    // the Wh multiply on step 0 (zeros), which is identical.
    let mut h_pre = vec![0.0f32; 4 * h];
    for step in 0..t {
        if step > 0 {
            // h_pre = h_prev @ wh.T: wh [4H, H], h_prev [H].
            for j in 0..4 * h {
                let mut acc = 0.0f32;
                let w_row = &this.wh[j * h..(j + 1) * h];
                for i in 0..h {
                    acc += out[i * t + step - 1] * w_row[i];
                }
                h_pre[j] = acc;
            }
        }
        // Gates in the kernel's stable form.
        let mut new_hidden = vec![0.0f32; h];
        for i in 0..h {
            let pi = h_pre[i] + pre_x[step * 4 * h + i];
            let pf = h_pre[h + i] + pre_x[step * 4 * h + h + i];
            let pg = h_pre[2 * h + i] + pre_x[step * 4 * h + 2 * h + i];
            let po = h_pre[3 * h + i] + pre_x[step * 4 * h + 3 * h + i];
            let gi = stable_sigmoid(pi);
            let gf = stable_sigmoid(pf);
            let gg = pg.tanh();
            let go = stable_sigmoid(po);
            cell[i] = gf * cell[i] + gi * gg;
            new_hidden[i] = go * cell[i].tanh();
        }
        for i in 0..h {
            out[i * t + step] = new_hidden[i];
        }
    }
    out
}

/// Deterministic xorshift stream with ~1 in 6 exact zeros; avoids a
/// dev-dependency.
struct Rng(u64);

impl Rng {
    fn value(&mut self) -> f32 {
        self.0 ^= self.0 << 13;
        self.0 ^= self.0 >> 7;
        self.0 ^= self.0 << 17;
        let r = self.0;
        if r % 6 == 0 {
            return 0.0;
        }
        (((r >> 8) % 20001) as f32 / 10000.0 - 1.0) * [0.1f32, 1.0, 3.0][((r >> 40) % 3) as usize]
    }

    fn vec(&mut self, n: usize) -> Vec<f32> {
        (0..n).map(|_| self.value()).collect()
    }
}

#[test]
fn lstm_forward_matches_original_over_many_steps_bitwise() {
    let mut rng = Rng(0x2545_f491_4f6c_dd1d);
    for &(dim, steps, with_bias) in &[
        (4usize, 1usize, true),
        (4, 2, false),
        (6, 11, true),
        (16, 25, false),
        (9, 40, true),
    ] {
        let lstm = Lstm {
            wx: rng.vec(4 * dim * dim),
            wh: rng.vec(4 * dim * dim),
            bias: with_bias.then(|| rng.vec(4 * dim)),
            hidden: dim,
            in_dim: dim,
        };
        let x = rng.vec(dim * steps);
        let want = lstm_forward_reference(&lstm, &x);
        let got = lstm.forward(&x);
        assert_eq!(got.len(), want.len());
        for (i, (g, w)) in got.iter().zip(&want).enumerate() {
            assert_eq!(
                g.to_bits(),
                w.to_bits(),
                "dim={dim} steps={steps} bias={with_bias} element {i}: got {g} want {w}"
            );
        }
    }
}
