//! `gpt-oss`'s routed-expert pass (ROADMAP M5).
//!
//! Structurally `families/llama/moe.rs`: top-k experts, no shared expert, so
//! phase 2's residual input is a ZERO buffer and the routed sum is added to
//! the stream afterwards. It is written out rather than shared for one
//! reason, and the reason is the first six lines of the function --
//! **THE ROUTER BIAS IS ADDED HERE**, to the read-back logits, before the
//! top-k sees them.
//!
//! That placement is not incidental. llama.cpp's `SOFTMAX_WEIGHT` gating adds
//! the bias to the logits, selects top-k on the RAW biased logits, then
//! softmaxes over the selected k alone with no renormalization -- which is
//! `router_topk_gemma4`'s existing contract minus Gemma's `per_expert_scale`.
//! Since this port's top-k is already a host-side function of a read-back f32
//! buffer, the add costs no kernel and no dispatch. Adding it after the top-k
//! would select the wrong experts and still produce fluent text; adding it
//! after the softmax would be a different distribution over the right ones.
//!
//! THE CLAMPED SwiGLU AND THE PER-EXPERT BIASES NEED NOTHING FROM THIS FILE.
//! Both ride inside the MXFP4 pair: `encode_moe_phase{1,2}_any` selects
//! `Mxfp4Activation::GPT_OSS` for that layout and derives `has_bias` from
//! `offsets.gate_b != 0`, which is exactly what `moe_offsets_from_layout`
//! writes once the repack walk puts the bias planes in the blob.
//!
//! The slot order is the ROUTER'S RANKING, as in every other family, and that
//! is a correctness constraint rather than a style choice: phase 2 reduces
//! `blob[slot] * routing_w[slot]` in slot-index order and FP addition is not
//! associative, so whatever the slot order depends on, the generated bytes
//! depend on (AGENTS.md Gotcha 27).

use std::time::Instant;

use half::f16;

use crate::families::gptoss::RealGptOssState;
use crate::real_forward_dispatch::{
    encode_moe_phase1_any, encode_moe_phase2_any, router_topk_gemma4,
};
use crate::real_forward_layout::RoutedLayerLayout;
use crate::real_forward_types::{DecodeScratch, PhaseCounters, RealForwardError};
use crate::real_forward_utils::f16_slice_to_le_bytes;

#[allow(clippy::too_many_arguments)]
pub(crate) fn encode_gpt_oss_layer_moe(
    context: &mut gpu::MetalContext,
    pass: &gpu::PassEncoder,
    scratch: &DecodeScratch,
    state: &RealGptOssState,
    streamers: &mut [Option<streaming::PreadExpertStreamer>],
    slot_buffers: &[Vec<gpu::MetalBuffer>],
    routed_blobs: Option<&gpu::RoutedBlobsBuffer>,
    moe_offsets: &[gpu::MoeExpertOffsets],
    routed_layouts: &[RoutedLayerLayout],
    router_hist: &mut Option<crate::router_hist::RouterHistogram>,
    phases: &mut PhaseCounters,
    layer: usize,
    hidden: usize,
    moe_inter: u32,
    num_experts: usize,
    top_k: usize,
) -> Result<(), RealForwardError> {
    let gpu_err = RealForwardError::Gpu;
    let t_router = Instant::now();
    let mut router_logits = gpu::read_f32_buffer(&state.router_logits_f32, num_experts);
    // THE BIAS, BEFORE THE TOP-K. See the module header.
    for (logit, bias) in router_logits.iter_mut().zip(&state.router_bias[layer]) {
        *logit += bias;
    }
    let (selected, route_weights) =
        router_topk_gemma4(&router_logits, top_k, &state.per_expert_ones);
    if let Some(hist) = router_hist.as_mut() {
        hist.record(layer, &selected);
    }
    let streamer = streamers[layer].as_mut().ok_or_else(|| {
        RealForwardError::Unsupported(format!(
            "gpt-oss layer {layer} has no packed-expert streamer"
        ))
    })?;
    let plan = streamer.plan_experts_cached(&selected, &std::collections::HashSet::new());
    phases.expert_requests += plan.experts.len() as u64;
    phases.expert_hits += plan.hits as u64;
    phases.router_nanos += t_router.elapsed().as_nanos() as u64;

    let streamer = streamers[layer]
        .as_mut()
        .expect("streamer presence checked above");
    let t_io = Instant::now();
    let slots = streamer
        .execute_expert_cache_plan(&plan)
        .map_err(|e| RealForwardError::Unsupported(format!("expert stream: {e}")))?;
    phases.expert_io_nanos += t_io.elapsed().as_nanos() as u64;

    let t_bind = Instant::now();
    let ordered: Vec<(usize, f32)> = (0..selected.len())
        .map(|i| (slots[i], route_weights[i]))
        .collect();
    let mut routing16 = vec![f16::from_f32(0.0); gpu::MAX_STREAMED_EXPERTS];
    for (slot, &(_, weight)) in ordered.iter().enumerate() {
        routing16[slot] = f16::from_f32(weight);
    }
    gpu::write_buffer_bytes(&scratch.routing_w, 0, &f16_slice_to_le_bytes(&routing16));

    let layer_slots = &slot_buffers[layer];
    let blob_refs: Vec<(&gpu::MetalBuffer, u64)> = ordered
        .iter()
        .map(|&(slot, _)| (&layer_slots[slot], 0u64))
        .collect();
    let routed = routed_blobs.ok_or_else(|| {
        RealForwardError::Unsupported("install has no routed-blob buffer".to_string())
    })?;
    let offsets = &moe_offsets[layer];
    // `use_silu` is what the two OLDER activations are selected by, and it is
    // dead for this family: the MXFP4 pair takes its activation from
    // `Mxfp4Activation::GPT_OSS` regardless. Passed `true` to match
    // `hidden_activation`, so a layout that somehow resolved to a non-MXFP4
    // kernel gets silu rather than gelu-tanh, which is the nearer wrong
    // answer.
    routed.bind(context, true, &blob_refs).map_err(gpu_err)?;
    phases.bind_nanos += t_bind.elapsed().as_nanos() as u64;

    for &(buffer, _) in &blob_refs {
        pass.use_read_buffer(buffer);
    }

    encode_moe_phase1_any(
        routed_layouts[layer].phase1,
        context,
        pass,
        routed,
        offsets,
        (&state.moe_x, 0),
        (&scratch.moe_acts, 0),
        hidden as u32,
        moe_inter,
        selected.len() as u32,
        true,
    )
    .map_err(gpu_err)?;
    // `zero_hidden` is the residual input: there is no shared expert to carry
    // one, so phase 2's `y = residual + sum(w * expert)` becomes the routed
    // sum alone and the add below is the only place the stream grows. Passing
    // `x` here would add the residual twice.
    encode_moe_phase2_any(
        routed_layouts[layer].phase2,
        context,
        pass,
        routed,
        offsets,
        (&scratch.moe_acts, 0),
        (&scratch.routing_w, 0),
        (&scratch.zero_hidden, 0),
        (&state.h2, 0),
        hidden as u32,
        moe_inter,
        true,
    )
    .map_err(gpu_err)?;
    gpu::encode_residual_add(
        context,
        pass,
        (&scratch.x, 0),
        (&state.h2, 0),
        hidden as u32,
    )
    .map_err(gpu_err)
}
