//! Fixture parity and contract tests for the MiniMax Music 3 port.
//!
//! Fixtures come from `testdata/minimax_music3/`, regenerated by
//! `tools/gen_minimax_music3_fixtures.py` against the pinned mlx-audio
//! commit. Bit-exact gates cover the RNG and every sampled AR
//! codebook; float-tolerant gates cover transformer states and
//! waveforms (different matmul reduction orders). The recorded
//! decision margins in the categorical fixtures keep the exact-token
//! gates honest by proving no draw sits on a rounding knife-edge.

use std::collections::HashMap;
use std::path::Path;

use super::*;
use crate::ops;

fn testdata(name: &str) -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata/minimax_music3")
        .join(name)
}

fn read_json(name: &str) -> serde_json::Value {
    let text = std::fs::read_to_string(testdata(name)).expect(name);
    serde_json::from_str(&text).expect(name)
}

#[test]
fn official_weight_norm_conversion_keeps_explicit_float32_exception() {
    let fused = fuse_weight_norm_pairs(HashMap::from([
        (
            "conv.weight_v".to_string(),
            Tensor {
                data: vec![3.0, 4.0],
                shape: vec![1, 2],
                dtype: precision::DType::Bf16,
            },
        ),
        (
            "conv.weight_g".to_string(),
            Tensor {
                data: vec![2.0],
                shape: vec![1, 1],
                dtype: precision::DType::Bf16,
            },
        ),
    ]));
    let weight = &fused["conv.weight"];
    assert_eq!(weight.dtype, precision::DType::F32);
    assert_eq!(weight.data, vec![1.2, 1.6]);
}

#[test]
fn weight_norm_fusion_passes_unpaired_tensors_through_unchanged() {
    let tensor = |data: Vec<f32>, dtype| Tensor {
        shape: vec![data.len()],
        data,
        dtype,
    };
    let fused = fuse_weight_norm_pairs(HashMap::from([
        (
            "plain.weight".to_string(),
            tensor(vec![1.0, -2.0, 0.5], precision::DType::Bf16),
        ),
        (
            "lone.weight_g".to_string(),
            tensor(vec![7.0], precision::DType::F32),
        ),
        (
            "lone2.weight_v".to_string(),
            tensor(vec![0.25, 8.0], precision::DType::Bf16),
        ),
        (
            "paired.weight_g".to_string(),
            tensor(vec![2.0], precision::DType::Bf16),
        ),
        (
            "paired.weight_v".to_string(),
            Tensor {
                data: vec![3.0, 4.0],
                shape: vec![1, 2],
                dtype: precision::DType::Bf16,
            },
        ),
    ]));
    let mut keys: Vec<&str> = fused.keys().map(String::as_str).collect();
    keys.sort_unstable();
    assert_eq!(
        keys,
        [
            "lone.weight_g",
            "lone2.weight_v",
            "paired.weight",
            "plain.weight"
        ]
    );
    let plain = &fused["plain.weight"];
    assert_eq!(plain.data, vec![1.0, -2.0, 0.5]);
    assert_eq!(plain.shape, vec![3]);
    assert_eq!(plain.dtype, precision::DType::Bf16);
    assert_eq!(fused["lone.weight_g"].data, vec![7.0]);
    assert_eq!(fused["lone.weight_g"].dtype, precision::DType::F32);
    assert_eq!(fused["lone2.weight_v"].data, vec![0.25, 8.0]);
    assert_eq!(fused["lone2.weight_v"].dtype, precision::DType::Bf16);
    // Pairs still fuse to float32 next to the pass-through entries.
    assert_eq!(fused["paired.weight"].dtype, precision::DType::F32);
}

/// Read a little-endian f32 .npy (the sortformer reader convention).
fn read_npy(name: &str) -> (Vec<usize>, Vec<f32>) {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    let data = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (shape, data)
}

fn floats(value: &serde_json::Value) -> Vec<f32> {
    value
        .as_array()
        .expect("float array")
        .iter()
        .map(|v| v.as_f64().expect("f64") as f32)
        .collect()
}

fn ints(value: &serde_json::Value) -> Vec<i64> {
    value
        .as_array()
        .expect("int array")
        .iter()
        .map(|v| v.as_i64().expect("i64"))
        .collect()
}

fn max_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(
        a.len(),
        b.len(),
        "length mismatch: {} vs {}",
        a.len(),
        b.len()
    );
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0, f32::max)
}

fn load_plain_model() -> Model {
    Model::load_converted(&testdata("converted_plain")).expect("converted_plain loads")
}

fn short_text_ids() -> Vec<i32> {
    let trace = read_json("ar_trace_short.json");
    ints(&trace["text_ids"][0])
        .iter()
        .map(|v| *v as i32)
        .collect()
}

// ---------------------------------------------------------------------------
// RNG parity
// ---------------------------------------------------------------------------

#[test]
fn mlx_keys_and_split_chains_match_the_reference() {
    let fixtures = read_json("rng_fixtures.json");
    for seed in ints(&fixtures["seeds"]) {
        let key = rng::Key::new(seed as u64);
        let want = ints(&fixtures["keys"][seed.to_string()]);
        assert_eq!(
            (key.0 as i64, key.1 as i64),
            (want[0], want[1]),
            "key({seed})"
        );
        let mut current = key;
        for (depth, entry) in fixtures["split_chains"][seed.to_string()]
            .as_array()
            .expect("chain entries")
            .iter()
            .enumerate()
        {
            let first_want = ints(&entry[0]);
            let second_want = ints(&entry[1]);
            let (first, second) = rng::split(current);
            assert_eq!(
                (first.0 as i64, first.1 as i64),
                (first_want[0], first_want[1]),
                "split first half seed {seed} depth {depth}"
            );
            assert_eq!(
                (second.0 as i64, second.1 as i64),
                (second_want[0], second_want[1]),
                "split second half seed {seed} depth {depth}"
            );
            current = first;
        }
    }
}

#[test]
fn uniform_draws_are_bit_exact_across_word_layouts() {
    let fixtures = read_json("rng_fixtures.json");
    for seed in ints(&fixtures["seeds"]) {
        let mut current = rng::Key::new(seed as u64);
        for depth in 1..=3 {
            let (first, second) = rng::split(current);
            let entry = &fixtures["chain_uniforms"][format!("chain_{seed}_{depth}")];
            for (name, got) in [("first", first), ("second", second)] {
                let expected = floats(&entry[name]);
                let actual = rng::uniform01(got, 4);
                for (w, g) in expected.iter().zip(&actual) {
                    assert_eq!(w.to_bits(), g.to_bits(), "seed {seed} depth {depth} {name}");
                }
            }
            current = first;
        }
    }
    const SHAPES: [&str; 8] = [
        "[1]",
        "[2]",
        "[3]",
        "[4]",
        "[5]",
        "[8]",
        "[7, 3]",
        "[1, 16, 6]",
    ];
    for (index, name) in SHAPES.iter().enumerate() {
        let entry = &fixtures["flat"][*name];
        let words: usize = floats(&entry["uniform"]).len();
        let key = rng::Key::new(1000 + index as u64);
        let expected = floats(&entry["uniform"]);
        let actual = rng::uniform01(key, words);
        for (w, g) in expected.iter().zip(&actual) {
            assert_eq!(w.to_bits(), g.to_bits(), "flat {name}");
        }
        // erfinv source differs from Metal's; only closeness is
        // claimed for normal draws.
        let expected_normal = floats(&entry["normal"]);
        let actual_normal = rng::normal(key, words);
        let diff = max_diff(&expected_normal, &actual_normal);
        assert!(diff < 1e-5, "normal {name} max diff {diff}");
    }
}

#[test]
fn global_key_sequence_advances_like_the_reference() {
    let fixtures = read_json("rng_fixtures.json");
    for (seed, entry) in fixtures["global_sequence"].as_object().expect("sequences") {
        let seed: u64 = seed.parse().unwrap();
        let mut sequence = rng::KeySequence::new(seed);
        for draw in 0..3 {
            let got = rng::uniform01(sequence.next(), 4);
            let want = floats(&entry["uniform"][draw]);
            for (w, g) in want.iter().zip(&got) {
                assert_eq!(w.to_bits(), g.to_bits(), "seed {seed} draw {draw}");
            }
        }
    }
}

#[test]
fn categorical_tokens_match_and_margins_stay_clear_of_knife_edges() {
    let fixtures = read_json("rng_fixtures.json");
    let mut checked = 0usize;
    for case in fixtures["categorical"]
        .as_array()
        .expect("categorical cases")
    {
        let logits = floats(&case["logits"]);
        let top_k = case["top_k"].as_u64().unwrap() as usize;
        let mut key = rng::Key::new(case["seed"].as_u64().unwrap());
        for draw in case["draws"].as_array().expect("draws") {
            let (token, next) = rng::sample_top_k(&logits, key, top_k);
            assert_eq!(
                token as i64,
                draw["token"].as_i64().unwrap(),
                "categorical token for a {:}-logit pattern",
                logits.len()
            );
            let margin = draw["margin"].as_f64().unwrap();
            let total = draw["total"].as_f64().unwrap();
            assert!(
                margin > 1e-5 * total.max(1.0),
                "fixture draw sits on a knife edge; regenerate fixtures"
            );
            let uniform = rng::uniform01(key, 1)[0];
            assert_eq!(
                uniform.to_bits(),
                (draw["uniform"].as_f64().unwrap() as f32).to_bits()
            );
            checked += 1;
            key = next;
        }
    }
    assert!(
        checked >= 100,
        "expected a real sample of draws, got {checked}"
    );
}

/// The two-ended word layout is the RNG's load-bearing subtlety: a
/// sequential fill would emit different uniforms for the same key.
/// This mutation check re-derives a sequential layout from the hash
/// and proves the shipped layout differs.
#[test]
fn random_bits_pairing_survives_a_layout_mutation() {
    let key = rng::Key::new(42);
    let words = rng::random_bits(key, 4);
    let sequential: Vec<u32> = (0..4u32)
        .map(|i| rng::threefry2x32(key, (i, 0)).0)
        .collect();
    assert_ne!(
        words, sequential,
        "layout degenerated to sequential counters"
    );
}

// ---------------------------------------------------------------------------
// Prompt parity
// ---------------------------------------------------------------------------

#[test]
fn prompt_assembly_matches_the_reference() {
    let fixtures = read_json("prompt_fixtures.json");
    for case in fixtures["captions"].as_array().expect("captions") {
        let input = case["input"].as_str().unwrap();
        let want = case["clean"].as_str().unwrap();
        assert_eq!(prompt::clean_caption(input), want, "caption {input:?}");
    }
    for case in fixtures["lyrics"].as_array().expect("lyrics") {
        let input = case["input"].as_str().unwrap();
        let want = case["normalized"].as_str().unwrap();
        assert_eq!(prompt::normalize_lyrics(input), want, "lyrics {input:?}");
    }
    let tiny = &fixtures["tiny_text"]["cases"][0];
    assert_eq!(
        assemble_prompt(
            tiny["text"].as_str().unwrap(),
            tiny["lyrics"].as_str().unwrap(),
        ),
        tiny["assembled"].as_str().unwrap()
    );
}

#[test]
fn tiny_text_pair_matches_the_reference() {
    let fixtures = read_json("prompt_fixtures.json");
    let cfg_token = fixtures["tiny_text"]["audio_cfg_token_id"]
        .as_i64()
        .unwrap() as i32;
    for case in fixtures["tiny_text"]["cases"].as_array().expect("cases") {
        let pair = encode_tiny_text_pair(case["assembled"].as_str().unwrap(), cfg_token);
        let conditional = ints(&case["conditional"]);
        let unconditional = ints(&case["unconditional"]);
        assert_eq!(
            pair[..conditional.len()]
                .iter()
                .map(|v| *v as i64)
                .collect::<Vec<_>>(),
            conditional,
            "conditional row"
        );
        assert_eq!(
            pair[conditional.len()..]
                .iter()
                .map(|v| *v as i64)
                .collect::<Vec<_>>(),
            unconditional,
            "unconditional row"
        );
    }
}

// ---------------------------------------------------------------------------
// Contract tests (pure functions)
// ---------------------------------------------------------------------------

#[test]
fn chunk_starts_match_the_official_windows() {
    assert_eq!(chunk_starts(1), vec![0]);
    assert_eq!(chunk_starts(200), vec![0]);
    assert_eq!(chunk_starts(201), vec![0, 100]);
    assert_eq!(chunk_starts(300), vec![0, 100]);
    assert_eq!(chunk_starts(301), vec![0, 100, 200]);
}

#[test]
fn sigma_schedule_runs_from_noise_to_data() {
    let sigmas = euler::sigma_schedule(4).unwrap();
    let want = [0.0f32, 0.25, 0.5, 0.75, 1.0];
    assert_eq!(sigmas.len(), want.len());
    for (got, w) in sigmas.iter().zip(want) {
        assert!((got - w).abs() < 1e-7, "sigma {got} vs {w}");
    }
    assert!(euler::sigma_schedule(0).is_err());
}

#[test]
fn quant_predicate_targets_only_large_generation_linears() {
    assert!(model_quant_predicate(
        "language_model.model.layers.0.self_attn.q_proj",
        true
    ));
    assert!(model_quant_predicate(
        "rvq_depth_decoder.layers.0.attn.to_q",
        true
    ));
    assert!(model_quant_predicate(
        "transformer.transformer_blocks.0.ff_in",
        true
    ));
    assert!(!model_quant_predicate("language_model.lm_head", true));
    assert!(!model_quant_predicate(
        "rvq_depth_decoder.audio_heads.0",
        true
    ));
    assert!(!model_quant_predicate("vocoder.conv_in", false));
    assert!(!model_quant_predicate(
        "language_model.model.embed_tokens",
        false
    ));
}

#[test]
fn latent_length_and_interpolation_match_the_reference_rules() {
    assert_eq!(
        fusion::latent_length_from_frames(200, 24_000, 960, 44_100, 512),
        689
    );
    assert_eq!(
        fusion::latent_length_from_frames(2, 24_000, 960, 44_100, 512),
        6
    );
    assert_eq!(
        fusion::latent_length_from_frames(1, 24_000, 960, 44_100, 512),
        3
    );
    let x = [1.0f32, 2.0, 3.0, 4.0];
    assert_eq!(fusion::nearest_interpolate_1d(&x, 1, 4, 2), vec![1.0, 3.0]);
    assert_eq!(fusion::nearest_interpolate_1d(&x, 1, 4, 4), x);
}

#[test]
fn sigma_and_crop_constants_stay_pinned() {
    assert_eq!(CHUNK_FRAMES, 200);
    assert_eq!(CHUNK_HOP, 100);
    assert_eq!(OVERLAP_LATENT_LENGTH, 172);
    assert_eq!(CROP_LEFT_LATENT * LATENT_HOP_LENGTH, 44_032);
    assert_eq!(CROP_RIGHT_LATENT * LATENT_HOP_LENGTH, 132_096);
    assert_eq!(SAMPLING_RATE, 44_100);
    assert_eq!(FRAME_RATE as usize, 25);
}

#[test]
fn conv_transpose_key_matcher_covers_the_reference_regex() {
    assert!(is_conv_transpose_key("blocks.0.conv_t1.weight"));
    assert!(is_conv_transpose_key("decoder.conv_transpose.weight"));
    assert!(is_conv_transpose_key("decoder.deconv.weight"));
    assert!(is_conv_transpose_key("decoder.convtr1.weight"));
    assert!(!is_conv_transpose_key("decoder.conv_tier.weight"));
    assert!(!is_conv_transpose_key("conv_in.weight"));
}

// ---------------------------------------------------------------------------
// AR stage parity
// ---------------------------------------------------------------------------

#[test]
fn ar_stage_replays_the_reference_codebook_for_codebook() {
    let model = load_plain_model();
    let trace = read_json("ar_trace_short.json");
    let text_ids = short_text_ids();
    let max_frames = trace["max_frames"].as_u64().unwrap() as usize;
    let seed = trace["seed"].as_u64().unwrap();

    let (hiddens, codes) = model
        .generate_frame_hiddens(&text_ids, max_frames, seed)
        .expect("AR generation");
    let want = floats(&trace["frame_hiddens_stacked"]);
    let diff = max_diff(&hiddens, &want);
    assert!(diff < 2e-3, "frame hiddens max diff {diff}");

    // Every sampled codebook, token-exact against the recorded trace.
    let mut recorded = Vec::new();
    for frame in trace["frames"].as_array().expect("frames") {
        if frame["frame_index"].as_u64().unwrap() > 0 {
            if let Some(codes) = frame.get("frame_codes") {
                recorded.push(ints(codes));
            }
        }
    }
    assert_eq!(codes.len(), recorded.len(), "emitted frame count");
    for (got, want) in codes.iter().zip(&recorded) {
        assert_eq!(
            got.iter().map(|v| *v as i64).collect::<Vec<_>>(),
            *want,
            "sampled codebooks diverged"
        );
    }
}

#[test]
fn ar_prefill_hidden_and_logits_match_the_reference() {
    let model = load_plain_model();
    let trace = read_json("ar_trace_short.json");
    let text_ids = short_text_ids();
    let prompt_len = text_ids.len();
    let mut pair = text_ids.clone();
    if prompt_len > 3 {
        pair.push(text_ids[0]);
        pair.extend(std::iter::repeat_n(
            model.config().audio_cfg_token_id as i32,
            prompt_len - 3,
        ));
        pair.extend_from_slice(&text_ids[prompt_len - 2..]);
    } else {
        pair.extend(text_ids.clone());
    }
    let embeddings = model.lm.embed_ids(&pair, 2, prompt_len).unwrap();
    let mut cache: Vec<qwen3::KvCache> = (0..model.config().num_hidden_layers)
        .map(|_| qwen3::KvCache::new())
        .collect();
    let hidden = model
        .lm
        .hidden_forward(&embeddings, 2, prompt_len, &mut cache)
        .unwrap();
    let want_hidden = floats(&trace["prefill"]["hidden"]);
    let diff = max_diff(&hidden, &want_hidden);
    println!("prefill hidden max diff {diff}");
    println!(
        "my prefill row0 t0[:5] {:?} want {:?}",
        &hidden[..5],
        &want_hidden[..5]
    );
    assert!(diff < 5e-4, "prefill hidden max diff {diff}");

    let mut last_rows = Vec::new();
    let hidden_size = model.config().hidden_size;
    for b in 0..2 {
        let base = (b * prompt_len + prompt_len - 1) * hidden_size;
        last_rows.extend_from_slice(&hidden[base..base + hidden_size]);
    }
    let logits = model.lm.logits(&last_rows).unwrap();
    let want_logits = floats(&trace["prefill"]["logits"]);
    let diff = max_diff(&logits, &want_logits);
    assert!(diff < 5e-4, "prefill logits max diff {diff}");
}

// ---------------------------------------------------------------------------
// Flow stage parity
// ---------------------------------------------------------------------------

#[test]
fn dit_velocity_matches_the_reference_at_fixed_sigmas() {
    let model = load_plain_model();
    let meta = read_json("dit_op.json");
    let (_, noise) = read_npy(meta["input_npy"]["file"].as_str().unwrap());
    let (cond_shape, condition_row_major) =
        read_npy(meta["condition_npy"]["file"].as_str().unwrap());
    let cond_dim = cond_shape.last().copied().unwrap();
    let seq = cond_shape[cond_shape.len() - 2];
    let condition = condition_row_major_to_channel(&condition_row_major, cond_dim, seq);
    for (name, sigma) in [("sigma_0", 0.0f32), ("sigma_half", 0.5), ("sigma_1", 1.0)] {
        let velocity = model
            .transformer
            .forward(&noise, sigma, &condition, seq)
            .expect("DiT forward");
        let (_, want) = read_npy(
            meta[format!("{name}_velocity_npy")]["file"]
                .as_str()
                .unwrap(),
        );
        let diff = max_diff(&velocity, &want);
        assert!(diff < 5e-4, "{name} velocity max diff {diff}");
        let (_, want_uncond) = read_npy(
            meta[format!("{name}_uncond_velocity_npy")]["file"]
                .as_str()
                .unwrap(),
        );
        let zeros = vec![0.0f32; condition.len()];
        let velocity = model
            .transformer
            .forward(&noise, sigma, &zeros, seq)
            .expect("DiT uncond forward");
        let diff = max_diff(&velocity, &want_uncond);
        assert!(diff < 5e-4, "{name} uncond velocity max diff {diff}");
    }
}

#[test]
fn short_generation_matches_the_reference_waveform() {
    let model = load_plain_model();
    let trace = read_json("flow_trace_short.json");
    let text_ids = short_text_ids();
    assert_eq!(trace["chunk_starts"].as_array().unwrap().len(), 1);
    let request = GenerateRequest {
        text_ids,
        frames: 2,
        steps: trace["steps"].as_u64().unwrap() as usize,
        seed: trace["seed"].as_u64().unwrap(),
    };
    let generation = model.generate(&request).expect("generation");
    assert_eq!(generation.sample_rate, 44_100);
    let want = floats(&trace["waveform"]);
    let diff = max_diff(&generation.waveform, &want);
    assert!(diff < 5e-3, "waveform max diff {diff}");
    assert_eq!(
        generation.samples,
        trace["waveform_shape"][0].as_u64().unwrap() as usize
    );
}

#[test]
fn official_tree_conversion_reproduces_the_reference_ar() {
    let model = Model::load_official_tree(&testdata("official_tiny")).expect("official tree");
    let ar = read_json("ar_trace_short.json");
    let text_ids = short_text_ids();
    let (hiddens, codes) = model
        .generate_frame_hiddens(&text_ids, 2, ar["seed"].as_u64().unwrap())
        .expect("AR through the official tree");
    let want_hiddens = floats(&ar["frame_hiddens_stacked"]);
    let diff = max_diff(&hiddens, &want_hiddens);
    assert!(diff < 2e-3, "official-tree AR hiddens max diff {diff}");
    assert!(!codes.is_empty());
    // The official tree carries the same weights as the converted
    // tree, so its full generation also lands on the same waveform.
    let flow = read_json("flow_trace_short.json");
    let generation = model
        .generate(&GenerateRequest {
            text_ids,
            frames: 2,
            steps: flow["steps"].as_u64().unwrap() as usize,
            seed: flow["seed"].as_u64().unwrap(),
        })
        .expect("official-tree generation");
    let want = floats(&flow["waveform"]);
    let diff = max_diff(&generation.waveform, &want);
    assert!(diff < 5e-3, "official-tree waveform max diff {diff}");
}

#[test]
fn long_ar_replays_the_recorded_tokens() {
    let model = load_plain_model();
    let ar = read_json("ar_trace_long.json");
    let text_ids: Vec<i32> = ints(&ar["text_ids"][0]).iter().map(|v| *v as i32).collect();
    let (hiddens, codes) = model
        .generate_frame_hiddens(
            &text_ids,
            ar["max_frames"].as_u64().unwrap() as usize,
            ar["seed"].as_u64().unwrap(),
        )
        .expect("long AR");
    let (shape, want_hiddens) = read_npy("ar_frame_hiddens_long.npy");
    let recorded_frames = shape[1];
    assert_eq!(
        shape,
        vec![
            1,
            recorded_frames,
            model.config().num_codebooks * model.config().hidden_size
        ]
    );
    let diff = max_diff(&hiddens, &want_hiddens);
    assert!(diff < 2e-3, "long AR hiddens max diff {diff}");

    let mut recorded = Vec::new();
    for frame in ar["frames"].as_array().expect("frames") {
        if frame["frame_index"].as_u64().unwrap() > 0 {
            if let Some(c) = frame.get("frame_codes") {
                recorded.push(ints(c));
            }
        }
    }
    assert_eq!(codes.len(), recorded.len(), "long frame count");
    for (got, want) in codes.iter().zip(&recorded) {
        assert_eq!(
            got.iter().map(|v| *v as i64).collect::<Vec<_>>(),
            *want,
            "long sampled codebooks diverged"
        );
    }
}

#[test]
fn long_flow_stitches_two_chunks_over_tiled_hiddens() {
    let model = load_plain_model();
    let flow = read_json("flow_trace_long.json");
    let (hiddens_shape, hiddens) = read_npy("long_flow_hiddens.npy");
    let frames = hiddens_shape[1];
    assert_eq!(
        ints(&flow["chunk_starts"]),
        vec![0, 100],
        "long scenario must exercise two chunks"
    );
    let stereo = model
        .run_flow(
            &hiddens,
            frames,
            flow["steps"].as_u64().unwrap() as usize,
            flow["seed"].as_u64().unwrap(),
        )
        .expect("long flow");
    let spots = &flow["waveform_spots"];
    let stride = spots["stride"].as_u64().unwrap() as usize;
    let want_spots = floats(&spots["values"]);
    let samples = stereo.len() / 2;
    let mut spot_diff = 0.0f32;
    let mut worst = 0usize;
    // The recorded rows are interleaved [L, R] frames every `stride`.
    for (i, frame) in want_spots.chunks(2).enumerate() {
        let t = i * stride;
        if t < samples {
            let d0 = (stereo[t] - frame[0]).abs();
            let d1 = (stereo[samples + t] - frame[1]).abs();
            if d0.max(d1) > spot_diff {
                spot_diff = d0.max(d1);
                worst = t;
            }
        }
    }
    let _ = worst;
    assert!(spot_diff < 1e-4, "long waveform spot max diff {spot_diff}");
    let stats = &flow["waveform_stats"];
    assert_eq!(
        samples,
        stats["count"].as_f64().unwrap() as usize / 2,
        "stitched sample count"
    );
}

#[test]
fn long_flow_latents_match_the_reference_per_chunk() {
    let model = load_plain_model();
    let flow = read_json("flow_trace_long.json");
    let (_, hiddens) = read_npy("long_flow_hiddens.npy");
    let fused = model.config().num_codebooks * model.config().hidden_size;
    let channels = model.config().dit_in_channels;
    let cond_dim = model.config().condition_out_dim;
    let steps = flow["steps"].as_u64().unwrap() as usize;
    let mut previous_latent: Option<Vec<f32>> = None;
    let mut previous_condition: Option<Vec<f32>> = None;
    let mut noise_sequence = rng::KeySequence::new(flow["seed"].as_u64().unwrap() + 7);
    for chunk in flow["chunks"].as_array().expect("chunks") {
        let start = chunk["start"].as_u64().unwrap() as usize;
        let end = chunk["end"].as_u64().unwrap() as usize;
        let target = chunk["latent_length"].as_u64().unwrap() as usize;
        let condition = model
            .condition
            .forward(&hiddens[start * fused..end * fused], end - start)
            .expect("condition");
        // The recorded condition npy is row-major [1, T, D]; our
        // encoder returns the same order.
        let (_, want_condition) = read_npy(chunk["condition_npy"]["file"].as_str().unwrap());
        let diff = max_diff(&condition, &want_condition);
        assert!(
            diff < 5e-4,
            "chunk {} condition max diff {diff}",
            chunk["index"]
        );
        let cond_channel = condition_row_major_to_channel(&condition, cond_dim, target);
        let noise = rng::normal(noise_sequence.next(), channels * target);
        let (_, want_noise) = read_npy(chunk["noise_npy"]["file"].as_str().unwrap());
        let diff = max_diff(&noise, &want_noise);
        assert!(
            diff < 1e-5,
            "chunk {} noise max diff {diff}",
            chunk["index"]
        );
        let (latents, _) = euler::denoise_chunk(
            &model.transformer,
            &noise,
            &cond_channel,
            channels,
            cond_dim,
            target,
            steps,
            DIT_CFG_SCALE,
            previous_latent.as_deref(),
            previous_condition.as_deref(),
        )
        .expect("denoise");
        let (_, want_latents) = read_npy(chunk["latents_npy"]["file"].as_str().unwrap());
        let diff = max_diff(&latents, &want_latents);
        assert!(
            diff < 1e-4,
            "chunk {} latents max diff {diff}",
            chunk["index"]
        );
        let carry_start = target.saturating_sub(2 * OVERLAP_LATENT_LENGTH);
        let carry_end = carry_start.max(target.saturating_sub(OVERLAP_LATENT_LENGTH));
        previous_latent = Some(slice_channel_rows(
            &latents,
            channels,
            target,
            carry_start,
            carry_end,
        ));
        previous_condition = Some(slice_channel_rows(
            &cond_channel,
            cond_dim,
            target,
            carry_start,
            carry_end,
        ));
    }
}

// ---------------------------------------------------------------------------
// Loader gates
// ---------------------------------------------------------------------------

#[test]
fn converted_q8_tree_loads_and_generates_finite_stereo() {
    let q8 = Model::load_converted(&testdata("converted_q8")).expect("q8 loads");
    let text_ids = short_text_ids();
    let generation = q8
        .generate(&GenerateRequest {
            text_ids,
            frames: 2,
            steps: 2,
            seed: 7,
        })
        .expect("q8 generation");
    assert_eq!(generation.waveform.len(), 96);
    assert!(generation.waveform.iter().all(|v| v.is_finite()));
}

#[test]
fn generate_rejects_out_of_range_requests() {
    let model = load_plain_model();
    let ids = vec![1i32, 5, 6, 2];
    for frames in [0usize, MAX_AUDIO_FRAMES + 1] {
        assert!(
            model
                .generate(&GenerateRequest {
                    text_ids: ids.clone(),
                    frames,
                    steps: 2,
                    seed: 1
                })
                .is_err(),
            "frames {frames}"
        );
    }
    for steps in [0usize, 31] {
        assert!(
            model
                .generate(&GenerateRequest {
                    text_ids: ids.clone(),
                    frames: 2,
                    steps,
                    seed: 1
                })
                .is_err(),
            "steps {steps}"
        );
    }
    assert!(model
        .generate(&GenerateRequest {
            text_ids: vec![1; MAX_PROMPT_TOKENS + 1],
            frames: 2,
            steps: 2,
            seed: 1
        })
        .is_err());
}

#[test]
fn missing_trees_fail_loudly() {
    assert!(Model::load_converted(Path::new("/nonexistent/minimax")).is_err());
    assert!(Model::load_official_tree(Path::new("/nonexistent/official")).is_err());
}

#[test]
fn loader_tensor_map_is_strict_about_extra_tensors() {
    let mut tensors: HashMap<String, weights::Tensor> = HashMap::new();
    tensors.insert(
        "mystery.weight".to_string(),
        weights::Tensor {
            dtype: super::precision::DType::F32,
            data: vec![0.0],
            shape: vec![1],
        },
    );
    let store = weights::WeightStore::from_map(tensors);
    assert!(store.finish().is_err());
}

#[test]
fn shared_kernels_still_compute_the_documented_example() {
    let out = ops::linear(&[1.0, 2.0], &[1.0, 0.0, 0.0, 1.0], None, 1, 2, 2);
    assert_eq!(out, vec![1.0, 2.0]);
}

#[test]
fn depth_decoder_steps_match_the_reference() {
    let model = load_plain_model();
    let trace = read_json("ar_trace_short.json");
    for step in trace["frames"][0]["depth_steps"].as_array().unwrap() {
        let input = floats(&step["input"]);
        let shape = ints(&step["input_shape"]);
        let (batch, len) = (shape[0] as usize, shape[1] as usize);
        let out = model.depth.forward(&input, batch, len).unwrap();
        let want = floats(&step["output"]);
        let diff = max_diff(&out, &want);
        println!("depth step {} diff {}", step["index"], diff);
        assert!(
            diff < 5e-4,
            "depth step {} max diff {}",
            step["index"],
            diff
        );
    }
}

#[test]
fn caption_request_matches_upstream_defaults_and_validation() {
    let request = TextGenerateRequest::new("soft piano ballad", "[verse]\nFirst line");
    assert_eq!(request.resolve().unwrap(), (60.0, 30, 0));

    let mut custom = request.clone();
    custom.duration_seconds = Some(1.99);
    custom.steps = Some(4);
    custom.seed = Some(17);
    assert_eq!(custom.resolve().unwrap(), (1.99, 4, 17));

    assert!(TextGenerateRequest::new("  ", "[instrumental]")
        .resolve()
        .is_err());
    assert!(TextGenerateRequest::new("piano", " \n ").resolve().is_err());
    for duration in [0.0, -1.0, 360.01, f64::NAN, f64::INFINITY] {
        let mut invalid = request.clone();
        invalid.duration_seconds = Some(duration);
        assert!(invalid.resolve().is_err(), "duration {duration}");
    }
    for steps in [0, 31] {
        let mut invalid = request.clone();
        invalid.steps = Some(steps);
        assert!(invalid.resolve().is_err(), "steps {steps}");
    }
}

#[test]
fn corrupt_config_dimension_products_are_refused() {
    let mut config = ModelConfig::tiny();
    config.num_codebooks = usize::MAX;
    config.num_condition_layers = usize::MAX;
    assert!(matches!(
        config.validate(),
        Err(SpeechError::BadConfig { .. })
    ));
    let mut config = ModelConfig::tiny();
    config.vocab_size = usize::MAX;
    assert!(matches!(
        config.validate(),
        Err(SpeechError::BadConfig { .. })
    ));
}

#[test]
fn flow_accepts_the_largest_64_bit_seed() {
    let model = Model::load_converted(&testdata("converted_plain")).unwrap();
    let hiddens = vec![0.0; model.config.num_codebooks * model.config.hidden_size];
    let wave = model.run_flow(&hiddens, 1, 1, u64::MAX).unwrap();
    assert!(!wave.is_empty());
    assert!(wave.iter().all(|v| v.is_finite()));
}

#[test]
fn official_tokenizer_loader_finds_nested_huggingface_layout() {
    use std::collections::HashMap;
    use tokenizers::models::wordlevel::WordLevel;
    use tokenizers::pre_tokenizers::whitespace::Whitespace;
    use tokenizers::Tokenizer;

    let vocab = HashMap::from([
        ("[UNK]".to_string(), 0),
        ("warm".to_string(), 7),
        ("piano".to_string(), 11),
    ]);
    let model = WordLevel::builder()
        .vocab(vocab)
        .unk_token("[UNK]".to_string())
        .build()
        .unwrap();
    let mut tokenizer = Tokenizer::new(model);
    tokenizer.with_pre_tokenizer(Some(Whitespace));
    let temp =
        std::env::temp_dir().join(format!("minimax-music3-tokenizer-{}", std::process::id()));
    let tokenizer_dir = temp.join("tokenizer");
    std::fs::create_dir_all(&tokenizer_dir).unwrap();
    tokenizer
        .save(tokenizer_dir.join("tokenizer.json"), false)
        .unwrap();

    let loaded = load_tokenizer(&temp).unwrap().expect("tokenizer loaded");
    let ids = prompt::encode_official_text(&loaded, "warm piano").unwrap();
    assert_eq!(ids, vec![7, 11]);
    assert!(load_tokenizer(&std::env::temp_dir()).unwrap().is_none());
    std::fs::remove_dir_all(temp).unwrap();
}

#[test]
fn caption_generation_uses_tiny_fixture_path_and_returns_stereo_44100() {
    let model = load_plain_model();
    let mut request = TextGenerateRequest::new("soft piano ballad", "[instrumental]");
    request.duration_seconds = Some(0.04);
    request.steps = Some(1);
    request.seed = Some(7);
    let generated = model.generate_text(&request).unwrap();
    assert_eq!(generated.sample_rate, 44_100);
    assert_eq!(generated.waveform.len(), generated.samples * 2);
    assert!(generated.samples > 0);
    assert!(generated.waveform.iter().all(|sample| sample.is_finite()));
}

#[test]
fn all_upstream_quantization_profiles_parse_with_exact_geometry() {
    use weights::LinearQuantization;

    assert!(matches!(
        parse_quant_scheme(&serde_json::json!({})).unwrap(),
        LinearQuantization::Dense
    ));
    for (mode, bits, group_size, expected) in [
        (
            "affine",
            8,
            64,
            LinearQuantization::Affine(QuantScheme {
                bits: 8,
                group_size: 64,
            }),
        ),
        (
            "affine",
            6,
            64,
            LinearQuantization::Affine(QuantScheme {
                bits: 6,
                group_size: 64,
            }),
        ),
        (
            "affine",
            4,
            64,
            LinearQuantization::Affine(QuantScheme {
                bits: 4,
                group_size: 64,
            }),
        ),
        ("mxfp4", 4, 32, LinearQuantization::MxFp4),
        ("mxfp8", 8, 32, LinearQuantization::MxFp8),
        ("nvfp4", 4, 16, LinearQuantization::NvFp4),
    ] {
        let actual = parse_quant_scheme(&serde_json::json!({
            "quantization": {"mode": mode, "bits": bits, "group_size": group_size}
        }))
        .unwrap();
        assert!(
            same_quantization(actual, expected),
            "mode {mode}: {actual:?}"
        );
    }

    for (mode, bits, group_size) in [("mxfp4", 8, 32), ("mxfp8", 8, 16), ("nvfp4", 4, 32)] {
        assert!(parse_quant_scheme(&serde_json::json!({
            "quantization": {"mode": mode, "bits": bits, "group_size": group_size}
        }))
        .is_err());
    }
    assert!(parse_quant_scheme(&serde_json::json!({
        "quantization": {"mode": "unknown", "bits": 4, "group_size": 32}
    }))
    .is_err());
}

fn same_quantization(a: weights::LinearQuantization, b: weights::LinearQuantization) -> bool {
    use weights::LinearQuantization;
    match (a, b) {
        (LinearQuantization::Dense, LinearQuantization::Dense)
        | (LinearQuantization::MxFp4, LinearQuantization::MxFp4)
        | (LinearQuantization::MxFp8, LinearQuantization::MxFp8)
        | (LinearQuantization::NvFp4, LinearQuantization::NvFp4) => true,
        (LinearQuantization::Affine(a), LinearQuantization::Affine(b)) => a == b,
        _ => false,
    }
}

struct DTypeRecorder {
    dtypes: std::rc::Rc<std::cell::RefCell<Vec<precision::DType>>>,
    noise: Option<std::rc::Rc<std::cell::RefCell<Vec<f32>>>>,
}
impl backend::DeviceWeight for DTypeRecorder {
    fn linear(
        &self,
        _input: &[f32],
        _bias: Option<&[f32]>,
        rows: usize,
        _input_dim: usize,
        output_dim: usize,
        dtype: precision::DType,
    ) -> crate::Result<Vec<f32>> {
        self.dtypes.borrow_mut().push(dtype);
        Ok(vec![0.0; rows * output_dim])
    }
    fn embedding(&self, _ids: &[i32], _width: usize) -> crate::Result<Vec<f32>> {
        unreachable!("head recorder does not embed")
    }
    fn convolution(
        &self,
        _input: &[f32],
        _bias: Option<&[f32]>,
        _shape: backend::ConvShape,
        _dtype: precision::DType,
    ) -> crate::Result<Vec<f32>> {
        unreachable!("head recorder does not convolve")
    }
}
impl backend::ComputeBackend for DTypeRecorder {
    fn load_weight(
        &self,
        _data: backend::WeightData<'_>,
    ) -> crate::Result<std::rc::Rc<dyn backend::DeviceWeight>> {
        unreachable!("recorder installed after loading")
    }
    fn attention(
        &self,
        q: &[f32],
        k: &[f32],
        v: &[f32],
        shape: backend::AttentionShape,
        dtype: precision::DType,
    ) -> crate::Result<Vec<f32>> {
        backend::attention(&None, q, k, v, shape, dtype)
    }
    fn trace(&self, stage: &str, _data: &[f32], dtype: precision::DType, _shape: &[usize]) {
        if stage == "flow.condition" {
            self.dtypes.borrow_mut().push(dtype);
        }
        if stage == "flow.noise" {
            if let Some(noise) = &self.noise {
                *noise.borrow_mut() = _data.to_vec();
            }
        }
    }
}

#[test]
fn mixed_residual_embeddings_promote_each_depth_head_after_the_first() {
    let mut model = Model::load_converted_with_precision(
        &testdata("precision/mxfp8"),
        Music3Precision::Checkpoint,
    )
    .unwrap();
    model.depth.audio_embeddings.dtype = precision::DType::F32;
    let recorded = std::rc::Rc::new(std::cell::RefCell::new(Vec::new()));
    for head in &mut model.depth.audio_heads {
        *head = backend::Weight::Device {
            elements: model.config.hidden_size * model.config.audio_vocab_size,
            dtype: precision::DType::Bf16,
            packed: true,
            dynamic: true,
            weight: std::rc::Rc::new(DTypeRecorder {
                dtypes: recorded.clone(),
                noise: None,
            }),
        };
    }
    let text = assemble_prompt("Soft piano, warm melody, instrumental", "[instrumental]");
    let ids = prompt::encode_tiny_ids(&text, MAX_PROMPT_TOKENS);
    model.generate_frame_hiddens(&ids, 1, 7).unwrap();
    let calls = recorded.borrow();
    assert!(!calls.is_empty());
    assert_eq!(calls.len() % (2 * (model.config.num_codebooks - 1)), 0);
    for frame in calls.chunks_exact(2 * (model.config.num_codebooks - 1)) {
        assert_eq!(&frame[..2], &[precision::DType::Bf16; 2]);
        assert!(
            frame[2..].iter().all(|d| *d == precision::DType::F32),
            "later depth heads: {frame:?}"
        );
    }
}

#[test]
fn mixed_residual_embeddings_promote_fused_flow_condition() {
    let mut model = Model::load_converted_with_precision(
        &testdata("precision/mxfp8"),
        Music3Precision::Checkpoint,
    )
    .unwrap();
    model.depth.audio_embeddings.dtype = precision::DType::F32;
    let recorded = std::rc::Rc::new(std::cell::RefCell::new(Vec::new()));
    model.backend = Some(std::rc::Rc::new(DTypeRecorder {
        dtypes: recorded.clone(),
        noise: None,
    }));
    model
        .run_flow(
            &vec![0.0; model.config.num_codebooks * model.config.hidden_size],
            1,
            1,
            7,
        )
        .unwrap();
    assert_eq!(*recorded.borrow(), vec![precision::DType::F32]);
}

#[test]
fn supplied_flow_noise_validates_chunks_and_replays_at_logical_precision() {
    for precision in [Music3Precision::Checkpoint, Music3Precision::Float32] {
        let mut model =
            Model::load_converted_with_precision(&testdata("precision/mxfp8"), precision).unwrap();
        let hiddens = vec![0.0; model.config.num_codebooks * model.config.hidden_size];
        let target = fusion::latent_length_from_frames(
            1,
            model.config.input_sampling_rate,
            model.config.input_hop_length,
            model.config.output_sampling_rate,
            model.config.output_hop_length,
        );
        let count = model.config.dit_in_channels * target;
        let noise: Vec<f32> = (0..count)
            .map(|i| [0.12345, -0.67891, 0.01993][i % 3])
            .collect();
        let captured = std::rc::Rc::new(std::cell::RefCell::new(Vec::new()));
        model.backend = Some(std::rc::Rc::new(DTypeRecorder {
            dtypes: Default::default(),
            noise: Some(captured.clone()),
        }));
        let chunks = vec![noise.clone()];
        let wave = model.run_flow_with_noise(&hiddens, 1, 1, &chunks).unwrap();
        let replay = model.run_flow_with_noise(&hiddens, 1, 1, &chunks).unwrap();
        assert_eq!(wave, replay);
        assert!(wave.iter().all(|v| v.is_finite()));
        let dtype = if precision == Music3Precision::Checkpoint {
            precision::DType::Bf16
        } else {
            precision::DType::F32
        };
        assert_eq!(
            *captured.borrow(),
            noise.iter().map(|v| dtype.round(*v)).collect::<Vec<_>>()
        );
        assert!(model.run_flow_with_noise(&hiddens, 1, 1, &[]).is_err());
        assert!(model
            .run_flow_with_noise(&hiddens, 1, 1, &[noise.clone(), noise.clone()])
            .is_err());
        assert!(model
            .run_flow_with_noise(&hiddens, 1, 1, &[vec![0.0; count - 1]])
            .is_err());
        for value in [f32::NAN, f32::INFINITY] {
            let mut invalid = noise.clone();
            invalid[0] = value;
            assert!(model
                .run_flow_with_noise(&hiddens, 1, 1, &[invalid])
                .is_err());
        }
        if precision == Music3Precision::Checkpoint {
            let mut invalid = noise.clone();
            invalid[0] = f32::MAX;
            assert!(model
                .run_flow_with_noise(&hiddens, 1, 1, &[invalid])
                .is_err());
        }
    }
}

fn progress_request(duration: f64) -> TextGenerateRequest {
    let mut request = TextGenerateRequest::new("soft piano ballad", "[instrumental]");
    request.duration_seconds = Some(duration);
    request.steps = Some(1);
    request.seed = Some(7);
    request
}

#[test]
fn progress_reports_each_stage_and_leaves_output_unchanged() {
    let model = load_plain_model();
    // Twelve frames: fewer than the fixture's 27 before its end token.
    let request = progress_request(0.5);
    let target = (0.5 * model.config().frame_rate).trunc() as usize;
    let mut events = vec![];
    let (generated, timings) = model
        .generate_text_with_progress(&request, |event| {
            events.push(event);
            Control::Continue
        })
        .unwrap()
        .expect("not cancelled");
    assert!(matches!(events[0], Progress::Tokenized { prompt_tokens } if prompt_tokens > 0));
    let frames: Vec<usize> = events
        .iter()
        .filter_map(|e| match e {
            Progress::ArFrame {
                emitted,
                target: reported,
            } => {
                assert_eq!(*reported, target);
                Some(*emitted)
            }
            _ => None,
        })
        .collect();
    assert_eq!(frames, (1..=target).collect::<Vec<_>>());
    assert_eq!(
        events.last(),
        Some(&Progress::FlowChunk { index: 0, total: 1 })
    );
    assert_eq!((timings.frames, timings.chunks), (target, 1));
    // The callback path runs identical arithmetic.
    let plain = model.generate_text(&request).unwrap();
    assert_eq!(plain.waveform, generated.waveform);
}

#[test]
fn cancelling_before_or_during_ar_returns_none_and_the_model_stays_reusable() {
    let model = load_plain_model();
    let request = progress_request(0.5);
    let reference = model.generate_text(&request).unwrap();
    for stage in ["tokenized", "frame"] {
        let mut seen = 0usize;
        let outcome = model
            .generate_text_with_progress(&request, |event| {
                seen += 1;
                let hit = match (stage, event) {
                    ("tokenized", Progress::Tokenized { .. }) => true,
                    ("frame", Progress::ArFrame { emitted, .. }) => emitted == 3,
                    _ => false,
                };
                if hit {
                    Control::Cancel
                } else {
                    Control::Continue
                }
            })
            .unwrap();
        assert!(outcome.is_none(), "{stage} cancel must return None");
        // Tokenized, then frames 1..=3; nothing after the cancel.
        assert_eq!(seen, if stage == "tokenized" { 1 } else { 4 });
        let again = model.generate_text(&request).unwrap();
        assert_eq!(again.waveform, reference.waveform, "after {stage} cancel");
    }
}

#[test]
fn flow_reports_chunks_and_cancelling_mid_flow_leaves_no_state() {
    let model = load_plain_model();
    let (shape, hiddens) = read_npy("long_flow_hiddens.npy");
    let frames = shape[1];
    let reference = model.run_flow(&hiddens, frames, 1, 7).unwrap();
    let mut chunks = vec![];
    let observed = model
        .run_flow_internal(&hiddens, frames, 1, 7, None, &mut |event| {
            chunks.push(event);
            Control::Continue
        })
        .unwrap()
        .expect("not cancelled");
    assert_eq!(
        chunks,
        vec![
            Progress::FlowChunk { index: 0, total: 2 },
            Progress::FlowChunk { index: 1, total: 2 },
        ]
    );
    assert_eq!(observed, reference);
    let cancelled = model
        .run_flow_internal(&hiddens, frames, 1, 7, None, &mut |event| match event {
            Progress::FlowChunk { index: 1, .. } => Control::Cancel,
            _ => Control::Continue,
        })
        .unwrap();
    assert!(cancelled.is_none());
    assert_eq!(model.run_flow(&hiddens, frames, 1, 7).unwrap(), reference);
}
