//! Fixture parity tests for the SNAC port.
//!
//! Fixtures live in `testdata/snac/`, regenerated by
//! `tools/gen_snac_fixtures.py` against the pinned mlx-audio commit.
//! Codes are exact-equality gates protected by recorded VQ distance
//! margins; tensors are float-tolerant (different matmul reduction
//! orders). The real-checkpoint test reads the locally cached
//! `mlx-community/snac_24khz` snapshot and skips when it is absent;
//! tests never download.

use std::path::{Path, PathBuf};

use super::{Snac, SnacConfig};
use crate::codec::wnconv::WnConv1d;
use turbospark_model_io::safetensors::SafetensorsFile;

fn testdata(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata/snac")
        .join(name)
}

fn read_json(name: &str) -> serde_json::Value {
    let text = std::fs::read_to_string(testdata(name)).expect(name);
    serde_json::from_str(&text).expect(name)
}

/// Read a little-endian f32 .npy (the shared testdata convention).
fn read_npy(name: &str) -> (Vec<usize>, Vec<f32>) {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    let data = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (shape, data)
}

fn floats(value: &serde_json::Value) -> Vec<f32> {
    value
        .as_array()
        .expect("float array")
        .iter()
        .map(|v| v.as_f64().expect("f64") as f32)
        .collect()
}

fn code_levels(value: &serde_json::Value) -> Vec<Vec<i32>> {
    value
        .as_array()
        .expect("levels")
        .iter()
        .map(|level| {
            level
                .as_array()
                .expect("level")
                .iter()
                .map(|v| v.as_i64().expect("i64") as i32)
                .collect()
        })
        .collect()
}

fn max_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(
        a.len(),
        b.len(),
        "length mismatch: {} vs {}",
        a.len(),
        b.len()
    );
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
}

fn load_tiny(tag: &str) -> Snac {
    let config = read_json(&format!("{tag}_config.json"));
    let config = SnacConfig::from_json(&config).expect("config parses");
    let file = SafetensorsFile::open(&testdata(&format!("{tag}_weights.safetensors")))
        .expect("weights open");
    Snac::load(config, &file).expect("load")
}

#[test]
fn config_defaults_match_reference() {
    let config = SnacConfig::from_json(&serde_json::json!({})).unwrap();
    assert_eq!(config.sampling_rate, 44100);
    assert_eq!(config.encoder_dim, 64);
    assert_eq!(config.encoder_rates, vec![3, 3, 7, 7]);
    assert_eq!(config.latent_dim, 64 * 16);
    assert_eq!(config.decoder_dim, 1536);
    assert_eq!(config.decoder_rates, vec![7, 7, 3, 3]);
    assert_eq!(config.attn_window_size, Some(32));
    assert_eq!(config.codebook_size, 4096);
    assert_eq!(config.codebook_dim, 8);
    assert_eq!(config.vq_strides, vec![8, 4, 2, 1]);
    assert!(config.noise);
    assert!(config.depthwise);
    assert_eq!(config.hop_length(), 441);
}

#[test]
fn deployed_24khz_config_parses() {
    // config.json of mlx-community/snac_24khz, pinned here so the
    // deployed geometry is covered without reading the checkpoint.
    let value = serde_json::json!({
        "sampling_rate": 24000,
        "encoder_dim": 48,
        "encoder_rates": [2, 4, 8, 8],
        "decoder_dim": 1024,
        "decoder_rates": [8, 8, 4, 2],
        "attn_window_size": null,
        "codebook_size": 4096,
        "codebook_dim": 8,
        "vq_strides": [4, 2, 1],
        "noise": true,
        "depthwise": true
    });
    let config = SnacConfig::from_json(&value).unwrap();
    assert_eq!(config.latent_dim, 768);
    assert_eq!(config.hop_length(), 512);
    assert_eq!(config.attn_window_size, None);
    assert!(config.noise);
}

#[test]
fn attention_configs_are_refused() {
    let mut config = read_json("tiny_a_config.json");
    config["attn_window_size"] = serde_json::json!(32);
    let config = SnacConfig::from_json(&config).unwrap();
    let file = SafetensorsFile::open(&testdata("tiny_a_weights.safetensors")).unwrap();
    let Err(err) = Snac::load(config, &file) else {
        panic!("attention config must be refused");
    };
    assert!(err.to_string().contains("attn_window_size"), "{err}");
}

#[test]
fn tiny_a_end_to_end_matches_reference() {
    let model = load_tiny("tiny_a");
    let traces = read_json("traces.json");
    assert!(!model.config.noise);

    // Encode: codes are exact and the VQ margin proves no knife-edge.
    let wave = floats(&traces["a_wave"]);
    let codes = model.encode(&wave).unwrap();
    let golden_codes = code_levels(&traces["a_codes"]);
    assert_eq!(codes, golden_codes);
    let best = traces["a_vq_margins"]["best"].as_array().unwrap();
    let second = traces["a_vq_margins"]["second"].as_array().unwrap();
    for (b, s) in best.iter().zip(second) {
        let b = b.as_f64().unwrap();
        let s = s.as_f64().unwrap();
        assert!(s - b > 1e-5, "level margin {s} - {b} too small");
    }
    assert_eq!(codes, code_levels(&traces["a_codes_encode"]));

    // Encoder output z against the reference.
    let padded = model.padded_len(wave.len());
    assert_eq!(padded as i64, traces["a_padded_len"].as_i64().unwrap());
    let mut x = vec![0.0f32; padded];
    x[..wave.len()].copy_from_slice(&wave);
    let z = model.encoder.forward(&x);
    let (z_shape, golden_z) = read_npy("a_z.npy");
    assert_eq!(
        z_shape,
        vec![
            1,
            model.config.latent_dim,
            padded / model.config.hop_length()
        ]
    );
    assert_eq!(z.len(), golden_z.len());
    assert!(max_diff(&z, &golden_z) < 1e-4, "encoder z diff");

    // Quantizer forward output z_q.
    let mut z_q_sum = vec![0.0f32; z.len()];
    let mut residual = z.clone();
    for q in &model.quantizers {
        let (z_q, _) = q.encode(&residual, model.config.latent_dim);
        for (dst, src) in z_q_sum.iter_mut().zip(&z_q) {
            *dst += src;
        }
        for (r, s) in residual.iter_mut().zip(&z_q) {
            *r -= s;
        }
    }
    let (_, golden_zq) = read_npy("a_zq.npy");
    assert_eq!(z_q_sum.len(), golden_zq.len());
    assert!(max_diff(&z_q_sum, &golden_zq) < 1e-4, "z_q diff");

    // Decoder on the reference z_q.
    let audio_hat = model.decoder.forward(&golden_zq.clone(), &mut || 0.0);
    let (_, golden_hat) = read_npy("a_audio_hat.npy");
    assert_eq!(audio_hat.len(), golden_hat.len());
    assert!(max_diff(&audio_hat, &golden_hat) < 1e-4, "decoder diff");

    // Full decode from codes (zero-noise backbone; model is noise-free).
    let audio = model.decode(&codes).unwrap();
    let (_, golden_from_codes) = read_npy("a_audio_from_codes.npy");
    assert_eq!(audio.len(), golden_from_codes.len());
    assert!(max_diff(&audio, &golden_from_codes) < 1e-4);
}

#[test]
fn tiny_b_short_input_matches_reference() {
    let model = load_tiny("tiny_a");
    let traces = read_json("traces.json");
    let wave = floats(&traces["b_wave"]);
    assert_eq!(
        model.padded_len(wave.len()) as i64,
        traces["b_padded_len"].as_i64().unwrap()
    );
    let codes = model.encode(&wave).unwrap();
    assert_eq!(codes, code_levels(&traces["b_codes"]));
    let audio = model.decode(&codes).unwrap();
    let (_, golden) = read_npy("b_audio_from_codes.npy");
    assert_eq!(audio.len(), golden.len());
    assert!(max_diff(&audio, &golden) < 1e-4);
}

#[test]
fn noise_checkpoint_replays_recorded_draws() {
    let model = load_tiny("tiny_b");
    assert!(model.config.noise);
    let traces = read_json("traces.json");
    let wave = floats(&traces["a_wave"]);
    let codes = model.encode(&wave).unwrap();
    assert_eq!(codes, code_levels(&traces["noise_codes"]));

    // decode() refuses noise-enabled checkpoints.
    let Err(err) = model.decode(&codes) else {
        panic!("noise-enabled decode must be refused");
    };
    assert!(err.to_string().contains("noise"), "{err}");

    let (_, pool) = read_npy("noise_pool.npy");
    let mut cursor = 0usize;
    let audio = model
        .decode_with_noise(&codes, &mut || {
            let v = pool[cursor];
            cursor += 1;
            v
        })
        .unwrap();
    assert_eq!(cursor as i64, traces["noise_draws"].as_i64().unwrap());
    let (_, golden) = read_npy("noise_decode.npy");
    assert_eq!(audio.len(), golden.len());
    assert!(max_diff(&audio, &golden) < 1e-4);
}

#[test]
fn isolated_vq_level_matches_reference() {
    let model = load_tiny("tiny_a");
    let traces = read_json("traces.json");
    let (shape, vq_in) = read_npy("vq_in.npy");
    // Python input is (B, latent, frames), already channel-major.
    assert_eq!(shape, vec![1, model.config.latent_dim, 24]);
    let (zq, codes) = model.quantizers[0].encode(&vq_in, model.config.latent_dim);
    let golden_codes: Vec<i32> = traces["vq_codes"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_i64().unwrap() as i32)
        .collect();
    assert_eq!(codes, golden_codes);
    let (_, golden_zq) = read_npy("vq_zq.npy");
    assert_eq!(zq.len(), golden_zq.len());
    assert!(max_diff(&zq, &golden_zq) < 1e-4);
}

/// Real-checkpoint gate against the locally cached
/// mlx-community/snac_24khz snapshot; skips when absent. Override the
/// directory with TURBOSPARK_SNAC_MODEL.
#[test]
fn real_checkpoint_matches_reference() {
    let dir = std::env::var("TURBOSPARK_SNAC_MODEL").unwrap_or_else(|_| {
        let mut found: Option<PathBuf> = None;
        let root = format!(
            "{}/.cache/huggingface/hub/models--mlx-community--snac_24khz/snapshots",
            std::env::var("HOME").unwrap()
        );
        if let Ok(entries) = std::fs::read_dir(&root) {
            for entry in entries.flatten() {
                if entry.path().join("config.json").exists() {
                    found = Some(entry.path());
                    break;
                }
            }
        }
        found
            .map(|p| p.to_string_lossy().into_owned())
            .unwrap_or_else(|| format!("{root}/missing"))
    });
    if !Path::new(&dir).join("config.json").exists() {
        eprintln!("skipping: snac_24khz checkpoint not present at {dir}");
        return;
    }
    let model = Snac::open(Path::new(&dir)).unwrap();
    assert_eq!(model.config.sampling_rate, 24000);

    let (_, wave) = read_npy("real_wave.npy");
    let codes = model.encode(&wave).unwrap();
    let golden_codes = code_levels(&read_json("real_encode_codes.json"));
    assert_eq!(codes.len(), golden_codes.len());
    for (got, want) in codes.iter().zip(&golden_codes) {
        assert_eq!(got, want, "code level mismatch");
    }

    let audio = model.decode_with_noise(&codes, &mut || 0.0).unwrap();
    let (_, golden_audio) = read_npy("real_decode_zero_noise.npy");
    assert_eq!(audio.len(), golden_audio.len());
    assert!(max_diff(&audio, &golden_audio) < 1e-3, "real decode diff");
}

#[test]
fn weight_norm_convs_fold_to_reference_layout() {
    // The loader folds weight_g * weight_v / norm; a finite forward on
    // a unit probe catches layout transposes that read garbage.
    let file = SafetensorsFile::open(&testdata("tiny_a_weights.safetensors")).unwrap();
    let conv = WnConv1d::load(&file, "encoder.block.layers.0", 1, 8, 7, 1, 3, 1, 1).unwrap();
    assert_eq!(conv.in_ch, 1);
    assert_eq!(conv.out_ch, 8);
    assert_eq!(conv.kernel, 7);
    let probe = vec![1.0f32; 7];
    let out = conv.forward(&probe);
    assert_eq!(out.len(), 8 * 7);
    assert!(out.iter().all(|v| v.is_finite()));
}
