//! Fixture parity tests for the Nemotron VoiceChat codec port.
//!
//! Fixtures live in `testdata/nemotron_voicechat/`, regenerated by
//! `tools/gen_nemotron_voicechat_fixtures.py` against the pinned
//! mlx-audio commit. The batch encode/decode contract is gated end to
//! end, including a random-codes decode that bypasses the encoder. A
//! real checkpoint directory can be pointed at via
//! TURBOSPARK_NEMOTRON_VOICECHAT_MODEL and is skipped when absent.
//! Tests never download.

use std::path::{Path, PathBuf};

use super::{NemotronVoiceChatCodec, NemotronVoiceChatConfig};
use turbospark_model_io::safetensors::SafetensorsFile;

fn testdata(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata/nemotron_voicechat")
        .join(name)
}

fn read_json(name: &str) -> serde_json::Value {
    let text = std::fs::read_to_string(testdata(name)).expect(name);
    serde_json::from_str(&text).expect(name)
}

fn read_npy_header(bytes: &[u8]) -> (String, usize) {
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len])
        .unwrap()
        .to_string();
    (header, 10 + header_len)
}

fn npy_shape(header: &str) -> Vec<usize> {
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect()
}

fn read_npy(name: &str) -> (Vec<usize>, Vec<f32>) {
    let bytes = std::fs::read(testdata(name)).expect(name);
    let (header, data_start) = read_npy_header(&bytes);
    assert!(
        header.contains("<f4") || header.contains("|f4"),
        "{name} must be f32"
    );
    let data = bytes[data_start..]
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (npy_shape(&header), data)
}

fn read_codes(name: &str) -> Vec<Vec<i32>> {
    let bytes = std::fs::read(testdata(name)).expect(name);
    let (header, data_start) = read_npy_header(&bytes);
    assert!(header.contains("<i4"), "{name} must be int32");
    let shape = npy_shape(&header);
    assert_eq!(shape.len(), 2, "{name} must be [Q, T]");
    let (q, t) = (shape[0], shape[1]);
    let data: Vec<i32> = bytes[data_start..]
        .chunks_exact(4)
        .map(|c| i32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    assert_eq!(data.len(), q * t);
    // The reference stacks codes along axis 1, so npy rows are already
    // quantizers: [Q][T].
    (0..q)
        .map(|qi| data[qi * t..(qi + 1) * t].to_vec())
        .collect()
}

fn rel_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(a.len(), b.len(), "length mismatch");
    let max = b.iter().fold(0.0f32, |acc, v| acc.max(v.abs()));
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
        / max
}

fn load_tiny() -> NemotronVoiceChatCodec {
    let config = read_json("tiny_config.json");
    let config = NemotronVoiceChatConfig::from_json(&config).expect("config");
    let file = SafetensorsFile::open(&testdata("tiny_weights.safetensors")).expect("weights");
    NemotronVoiceChatCodec::load(config, &file).expect("load")
}

#[test]
fn config_defaults_match_reference() {
    let config = NemotronVoiceChatConfig::from_json(&serde_json::json!({})).unwrap();
    assert_eq!(config.sample_rate, 22_050);
    assert_eq!(config.base_channels, 384);
    assert_eq!(config.channel_multipliers, vec![1, 2, 4]);
    assert_eq!(config.downsample_rates, vec![7, 7, 9]);
    assert_eq!(config.blocks_per_stage, 3);
    assert_eq!(config.block_kernel_size, 7);
    assert_eq!(config.latent_dim, 512);
    assert_eq!(config.n_fft, 16);
    assert_eq!(config.hop_length, 4);
    assert_eq!(config.num_quantizers, 31);
    assert_eq!(config.codebook_size, 1024);
    assert_eq!(config.waveform_to_token_ratio(), 4 * 7 * 7 * 9);
    assert_eq!(config.stft_channels(), 18);
    assert!((config.frame_rate() - 22_050.0 / 1764.0).abs() < 1e-6);
}

#[test]
fn tiny_encode_decode_matches_reference() {
    let model = load_tiny();
    let traces = read_json("traces.json");
    for tag in ["a", "b"] {
        let (_, wave) = read_npy(&format!("{tag}_wave.npy"));
        let (lat_shape, golden_latents) = read_npy(&format!("{tag}_latents.npy"));
        // Latents first: codes are meaningless if the hidden states
        // diverge.
        let latents = model.encode_latents(&wave).unwrap();
        let frames = latents.len() / model.config.latent_dim;
        assert_eq!(lat_shape, vec![frames, model.config.latent_dim]);
        let rel = rel_diff(&latents, &golden_latents);
        assert!(rel < 1e-5, "tag {tag} latents rel diff {rel}");

        let codes = model.encode(&wave).unwrap();
        let golden_codes = read_codes(&format!("{tag}_codes.npy"));
        assert_eq!(codes.len(), golden_codes.len(), "tag {tag} quantizers");
        for (q, (mine, golden)) in codes.iter().zip(&golden_codes).enumerate() {
            assert_eq!(mine, golden, "tag {tag} quantizer {q}");
        }
        let margin = traces[format!("{tag}_min_margin").as_str()]
            .as_f64()
            .unwrap();
        assert!(margin > 1e-3, "tag {tag} margin {margin}");

        let (_, golden_wave) = read_npy(&format!("{tag}_decoded.npy"));
        let decoded = model.decode(&codes).unwrap();
        assert_eq!(decoded.len(), golden_wave.len());
        let rel = rel_diff(&decoded, &golden_wave);
        assert!(rel < 1e-5, "tag {tag} decoded rel diff {rel}");
        // Decode length is exact per token count; the encoder drops
        // any input tail shorter than one token.
        assert_eq!(
            decoded.len(),
            frames * model.config.waveform_to_token_ratio()
        );
    }
}

#[test]
fn random_codes_decode_matches_reference() {
    let model = load_tiny();
    let codes = read_codes("rand_codes.npy");
    let (_, golden) = read_npy("rand_decoded.npy");
    let decoded = model.decode(&codes).unwrap();
    assert_eq!(decoded.len(), golden.len());
    let rel = rel_diff(&decoded, &golden);
    assert!(rel < 1e-5, "random decode rel diff {rel}");
}

#[test]
fn decode_validates_codes() {
    let model = load_tiny();
    // More quantizers than the model carries.
    let too_many = vec![vec![0i32; 2]; model.config.num_quantizers + 1];
    assert!(model.decode(&too_many).is_err());
    // Out-of-range code id.
    let bad = vec![vec![model.config.codebook_size as i32; 2]];
    assert!(model.decode(&bad).is_err());
}

/// Real-checkpoint gate; opt-in via TURBOSPARK_NEMOTRON_VOICECHAT_MODEL
/// pointing at a directory with config.json + model.safetensors.
/// Skips when unset.
#[test]
fn real_checkpoint_gate() {
    let Ok(dir) = std::env::var("TURBOSPARK_NEMOTRON_VOICECHAT_MODEL") else {
        eprintln!("skipping: TURBOSPARK_NEMOTRON_VOICECHAT_MODEL not set");
        return;
    };
    let model = NemotronVoiceChatCodec::open(Path::new(&dir)).unwrap();
    let n = model.config.waveform_to_token_ratio() * 4;
    let wave: Vec<f32> = (0..n)
        .map(|i| ((i as f32) * 220.0 * std::f32::consts::TAU / 22_050.0).sin() * 0.2)
        .collect();
    let codes = model.encode(&wave).unwrap();
    assert_eq!(codes.len(), model.config.num_quantizers);
    assert!(codes.iter().all(|book| book
        .iter()
        .all(|&c| (0..model.config.codebook_size as i32).contains(&c))));
    let decoded = model.decode(&codes).unwrap();
    assert_eq!(decoded.len(), n);
    assert!(decoded.iter().all(|v| v.is_finite()));
}
