#!/usr/bin/env python3
"""Generate search entries from declarations adjacent to settings controls. --check detects drift."""
import json
from pathlib import Path
import re
import sys

root = Path(__file__).resolve().parent.parent
source = root / 'swift/TurboSparkApp/Sources/TurboSparkApp'
entries = {}
for path in sorted(source.rglob('*.swift')):
    for title, pane, timing in re.findall(r'\.settingsControl\("([^"\n]+)", pane: \.(\w+)(?:, timing: \.(\w+))?\)', path.read_text()):
        entries[(pane, title)] = timing or 'immediate'
# preferenceRow registers its title in the reusable row helper.
prefs = (source / 'Components/AppearancePreferencesCardView.swift').read_text()
for title in re.findall(r'preferenceRow\(\s*title: "([^"]+)"', prefs):
    entries[('appearance', title)] = 'immediate'
lines = ['// Generated by scripts/generate-settings-catalog.py. Edit settingsControl declarations.',
         'import Foundation', '', 'enum SettingsControlCatalog {',
         '    static let entries: [SettingsControlDescriptor] = [']
for (pane, title), timing in sorted(entries.items()):
    lines.append(f'        .init(title: {json.dumps(title)}, pane: .{pane}, timing: .{timing}),')
lines += ['    ]', '}', '']
output = '\n'.join(lines)
output = re.sub(r'\\u([0-9a-fA-F]{4})', lambda m: '\\u{' + m[1] + '}', output)
path = source / 'App/SettingsControlCatalog.swift'
if '--check' in sys.argv:
    if not path.exists() or path.read_text() != output:
        sys.exit('Settings catalogue is stale. Run scripts/generate-settings-catalog.py.')
else:
    path.write_text(output)
print(f'{len(entries)} settings search entries')
