// Dumps a Q3_K decode oracle out of ggml itself, so
// `crates/compute/src/quant_gguf/q3_k.rs`'s Q3_K reference is checked against
// the format's own implementation rather than against a second copy of this
// port's reading of it (Dense Qwen2 roadmap item; the pinned official
// Qwen2.5 Q3_K_M GGUF carries Q3_K attention and FFN projections).
//
// Sibling of `scripts/ggml_q5_k_oracle.c` and deliberately a separate file:
// that one is ROADMAP Phase M2's oracle, its output is checked in under
// `crates/compute/tests/generated/`, and re-running it to add an unrelated
// oracle would mean re-pasting a long table for nothing.
//
// WHY AN ORACLE AND NOT A ROUND TRIP. A round trip through this port's own
// quantizer and dequantizer passes whenever the two share a misreading, and
// they are written by the same person from the same paragraph. Here ggml
// produces BOTH the bytes and the expected floats, so the Rust decoder is
// the only thing under test. Q3_K has more ways than most to be finite and
// plausible while wrong: the super-scale sits LAST in the block, the high
// bits that sign the 2-bit levels are indexed `e % 32` with the BIT chosen
// by `e / 32`, and the sixteen 6-bit scales are packed into twelve bytes
// through a four-word shuffle.
//
// Build and run (brew's llama.cpp; same install `scripts/ggml_tables.c`,
// `scripts/ggml_q5_k_oracle.c` and `scripts/llamacpp_logits.c` compile
// against):
//
//   cc -O2 -I/opt/homebrew/include scripts/ggml_q3_k_oracle.c \
//      -L/opt/homebrew/lib -lggml-base -o /tmp/ggml_q3_k && /tmp/ggml_q3_k \
//      > crates/compute/tests/generated/quant_gguf_q3_k_oracle.rs
//
// It is NOT wired into the build: this workspace must not gain a libggml
// dependency for one fixture.

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include "ggml.h"

#define QK_K 256
// Two superblocks, so a bug that resets state per block (or that reads block
// 0's scales for block 1) has somewhere to show up.
#define N (2 * QK_K)

static uint32_t lcg(uint32_t *s) {
  *s = *s * 1664525u + 1013904223u;
  return *s;
}

int main(void) {
  const enum ggml_type t = GGML_TYPE_Q3_K;
  const size_t block_bytes = ggml_type_size(t);
  const int64_t block_elems = ggml_blck_size(t);
  if (block_elems != QK_K) {
    fprintf(stderr, "Q3_K block is %lld elements, expected %d\n",
            (long long)block_elems, QK_K);
    return 1;
  }
  if (block_bytes != 110) {
    fprintf(stderr, "Q3_K block is %zu bytes, expected 110\n", block_bytes);
    return 1;
  }

  const struct ggml_type_traits *tr = ggml_get_type_traits(t);
  if (!tr || !tr->to_float) {
    fprintf(stderr, "no Q3_K to_float in this libggml\n");
    return 1;
  }

  // Weights spanning a real range including both signs and a run of zeros,
  // because Q3_K's high-bit sign run is what a symmetric-quant habit drops
  // and an all-positive fixture would hide (a cleared bit shifts the stored
  // level down by 4).
  float x[N];
  uint32_t s = 20260919u;
  for (int i = 0; i < N; ++i) {
    x[i] = (float)((int32_t)(lcg(&s) % 2001) - 1000) / 1000.0f;
  }
  for (int i = 300; i < 340; ++i) {
    x[i] = 0.0f;
  }

  uint8_t bytes[2 * 110];
  const size_t total_bytes = (size_t)(N / QK_K) * block_bytes;
  if (total_bytes > sizeof(bytes)) {
    fprintf(stderr, "buffer too small: %zu\n", total_bytes);
    return 1;
  }
  // The public converter path, the same call `llama-quantize` makes, rather
  // than the traits' reference quantizer: whatever a real published file
  // went through is what the decoder has to read.
  const size_t wrote = ggml_quantize_chunk(t, x, bytes, 0, N / QK_K, QK_K,
                                           /* imatrix */ NULL);
  if (wrote != total_bytes) {
    fprintf(stderr, "quantize wrote %zu bytes, expected %zu\n", wrote,
            total_bytes);
    return 1;
  }

  float y[N];
  tr->to_float(bytes, y, N);

  printf("// Generated by scripts/ggml_q3_k_oracle.c against libggml. Do not "
         "edit.\n");
  printf("//\n// ggml quantized these bytes and decoded these floats. The "
         "Rust decoder\n// is the only side under test.\n\n");
  printf("/// What `ggml_quantize_chunk` produced for %d elements (%zu bytes "
         "per superblock).\n",
         N, block_bytes);
  printf("pub const Q3_K_ORACLE_BYTES: [u8; %zu] = [", total_bytes);
  for (size_t i = 0; i < total_bytes; ++i) {
    printf("%s%u", i ? ", " : "", bytes[i]);
  }
  printf("];\n\n");

  printf("/// What ggml's `to_float` reads back out of those exact bytes.\n");
  printf("#[allow(clippy::excessive_precision)]\n");
  printf("pub const Q3_K_ORACLE_FLOATS: [f32; %d] = [", N);
  for (int i = 0; i < N; ++i) {
    printf("%s%#.9g", i ? ", " : "", y[i]);
  }
  printf("];\n");
  return 0;
}
