#!/usr/bin/env python3
"""Regenerate crates/compute/tests/generated/quant_2bit_oracle.rs.

The sibling of `scripts/mlx_1bit_oracle.py`, at TWO bits, against
`prism-ml/Ternary-Bonsai-27B-mlx-2bit` (ROADMAP's ternary entry). Same rule
and same reason: recover the MLX affine layout by PROBING mlx's own
`mx.dequantize` on real published bytes rather than transcribing a format
description, because a decoder and the doc it was written from can be wrong
together.

Costs a few tens of KB of RANGED reads off an 8.5 GiB remote file (~5 s), so
it needs no local checkpoint. Run it under an ephemeral environment so
nothing is installed globally and nothing enters this workspace:

    uv run --python 3.12 --with mlx --with numpy scripts/mlx_2bit_oracle.py \
      > crates/compute/tests/generated/quant_2bit_oracle.rs

TWO DIFFERENCES FROM THE 1-BIT GENERATOR, both about the environment rather
than the layout. Upstream mlx supports `bits=2` on every device -- it refuses
only `bits=1` ("The supported bits are 2, 3, 4, 5, 6 and 8") -- so this needs
neither the PrismML fork nor the CPU-stream workaround its sibling wraps
`mx.dequantize` in. And the property being measured is different: at one bit
the checkpoint carries `bias == -scale / 2`, while this one carries
`bias == -scale` with the fourth level unused, i.e. a TERNARY `{-s, 0, +s}`
grid in a 2-bit affine word. Both are properties of the checkpoint and not of
the container, so they are re-measured here and printed rather than assumed.

NOTE what the level histogram does NOT prove. Permuting the 2-bit fields
inside a packed word permutes the multiset of levels without changing it, so
"level 3 never occurs" survives a wrong field order untouched -- the same
invariance that makes a popcount useless as a bit-order check at one bit.
Only the dequantize comparison below can see the order.
"""

import collections
import json
import struct
import sys
import urllib.request

import numpy as np
import mlx.core as mx

REPO = "prism-ml/Ternary-Bonsai-27B-mlx-2bit"
REVISION = "70f75f3ad081ab840a42f3304c02c27e7f89bfb7"
FILE = "model.safetensors"
URL = f"https://huggingface.co/{REPO}/resolve/{REVISION}/{FILE}"

# The same small tensor the 1-bit generator probes, which this checkpoint
# carries at the same logical shape: 48 rows of 5120 weights, so 30,720
# packed bytes and 1,920 groups. Its first row spans two groups with
# DIFFERENT scales, which is what lets the oracle catch a group-indexing bug.
TENSOR = "language_model.model.layers.0.linear_attn.in_proj_a"
GROUP_SIZE = 128
BITS = 2
# How much of row 0 to freeze: two whole groups.
ORACLE_ELEMENTS = 256


def fetch(start, end_inclusive):
    req = urllib.request.Request(URL, headers={"Range": f"bytes={start}-{end_inclusive}"})
    with urllib.request.urlopen(req, timeout=120) as r:
        return r.read()


def main():
    header_len = struct.unpack("<Q", fetch(0, 7))[0]
    header = json.loads(fetch(8, 8 + header_len - 1))
    data_start = 8 + header_len

    planes = {}
    for suffix in ("weight", "scales", "biases"):
        info = header[f"{TENSOR}.{suffix}"]
        lo, hi = info["data_offsets"]
        raw = fetch(data_start + lo, data_start + hi - 1)
        planes[suffix] = (info, raw)

    w_info, w_raw = planes["weight"]
    rows, packed_words = w_info["shape"]
    cols = packed_words * (32 // BITS)
    n_groups = cols // GROUP_SIZE

    w = np.frombuffer(w_raw, dtype=np.uint32).reshape(rows, packed_words)
    s = np.frombuffer(planes["scales"][1], dtype=np.float16).reshape(rows, n_groups)
    b = np.frombuffer(planes["biases"][1], dtype=np.float16).reshape(rows, n_groups)

    out = mx.dequantize(mx.array(w), mx.array(s), mx.array(b), group_size=GROUP_SIZE, bits=BITS)
    deq = np.array(out.astype(mx.float32))

    # The properties the Rust module states, re-measured here so the
    # generator reports them rather than the reader assuming them.
    #
    # `elements_per_byte` is 4 and a byte boundary falls on a field boundary,
    # so the BYTE view below is the whole layout and carries no endianness
    # assumption -- exactly as at one bit.
    sym = np.array_equal(b.astype(np.float32), -s.astype(np.float32))
    raw_bytes = np.frombuffer(w_raw, dtype=np.uint8).reshape(rows, cols // 4)
    q_lsb = np.zeros((rows, cols), dtype=np.uint8)
    for j in range(cols // 4):
        for k in range(4):
            q_lsb[:, j * 4 + k] = (raw_bytes[:, j] >> (2 * k)) & 3
    lsb_ok = np.array_equal(
        q_lsb.astype(np.float32) * np.repeat(s.astype(np.float32), GROUP_SIZE, axis=1)
        + np.repeat(b.astype(np.float32), GROUP_SIZE, axis=1),
        deq,
    )
    levels = collections.Counter(q_lsb.ravel().tolist())

    print(f"// Generated by scripts/mlx_2bit_oracle.py against mlx {mx.__version__}. Do not edit.")
    print("//")
    print(f"// Source: {REPO} {FILE}")
    print(f"//   revision {REVISION}")
    print(f"//   tensor {TENSOR}")
    print(f"//   shape {rows}x{cols}, bits {BITS}, group_size {GROUP_SIZE}")
    print("//")
    print("// MLX quantized these bytes and MLX decoded these floats. The Rust")
    print("// decoder is the only side under test.")
    print("//")
    print("// Measured over the whole probed tensor while generating:")
    print(f"//   LSB-first field order reproduces mx.dequantize exactly: {lsb_ok}")
    print(f"//   bias == -scale in all {rows * n_groups} groups: {sym}")
    print(f"//   level histogram over {rows * cols} elements: {dict(sorted(levels.items()))}")
    print("//   (a wrong field order permutes that histogram's multiset without")
    print("//    changing it, so the level counts prove nothing about order.)")
    if not lsb_ok or not sym:
        print("// WARNING: a property above is FALSE; the module header is stale.", file=sys.stderr)

    head_bytes = raw_bytes[0, : ORACLE_ELEMENTS // 4]
    head_groups = ORACLE_ELEMENTS // GROUP_SIZE
    s_bits = np.frombuffer(planes["scales"][1], dtype=np.uint16).reshape(rows, n_groups)
    b_bits = np.frombuffer(planes["biases"][1], dtype=np.uint16).reshape(rows, n_groups)

    print()
    print(f"/// Row 0's first {ORACLE_ELEMENTS} weights, as they are packed in the file.")
    print(f"pub const INT2_ORACLE_PACKED: [u8; {len(head_bytes)}] = {list(map(int, head_bytes))};")
    print()
    print("/// Their FP16 scale bit patterns, one per group.")
    print(
        f"pub const INT2_ORACLE_SCALES: [u16; {head_groups}] = "
        f"{list(map(int, s_bits[0, :head_groups]))};"
    )
    print()
    print("/// Their FP16 bias bit patterns, one per group.")
    print(
        f"pub const INT2_ORACLE_BIASES: [u16; {head_groups}] = "
        f"{list(map(int, b_bits[0, :head_groups]))};"
    )
    print()
    print("/// What `mx.dequantize` reads back out of those exact bytes.")
    print("#[allow(clippy::excessive_precision)]")
    # `%g` renders an exact zero as `0`, which is an INTEGER literal in Rust
    # and does not typecheck in an `[f32; N]`. The 1-bit generator never hit
    # this because a binary grid has no zero; a ternary one is a third zeros.
    def literal(v):
        s = f"{v:.13g}"
        return s if ("." in s or "e" in s) else f"{s}.0"

    floats = ", ".join(literal(v) for v in deq[0, :ORACLE_ELEMENTS])
    print(f"pub const INT2_ORACLE_FLOATS: [f32; {ORACLE_ELEMENTS}] = [{floats}];")


if __name__ == "__main__":
    main()
