#!/usr/bin/env python3
"""Regenerate crates/compute/tests/generated/quant_1bit_oracle.rs.

Recovers the MLX 1-bit affine layout by PROBING mlx's own `mx.dequantize`
on real published bytes, rather than transcribing a format description.
That is the same rule `scripts/ggml_tables.c` follows for the IQ codebooks,
and it is there for the same reason: a decoder and the doc it was written
from can be wrong together, and an independent implementation's output
cannot agree with a wrong unpacker by accident.

Costs a few tens of KB of RANGED reads off a 4.8 GiB remote file (~5 s), so
it needs no local checkpoint. It reads the safetensors header, resolves the
byte range of one small quantized tensor and its two FP16 companion planes,
fetches exactly those, and prints what MLX makes of them.

Run it under an ephemeral environment so nothing is installed globally and
nothing enters this workspace:

    uv run --python 3.12 --with mlx --with numpy scripts/mlx_1bit_oracle.py \
      > crates/compute/tests/generated/quant_1bit_oracle.rs

MLX's METAL path cannot do this: upstream mlx ships no
`affine_dequantize_*_gs_128_b_1` kernel (bits=1 is the PrismML fork's
addition), so the Metal device aborts the process. The CPU stream computes
it correctly, which is why the dequantize below is inside `mx.stream(mx.cpu)`.
"""

import json
import struct
import sys
import urllib.request

import numpy as np
import mlx.core as mx

REPO = "prism-ml/Bonsai-27B-mlx-1bit"
FILE = "model.safetensors"
URL = f"https://huggingface.co/{REPO}/resolve/main/{FILE}"

# One small quantized tensor: 48 rows of 5120 weights, so 30,720 packed
# bytes and 1,920 groups. Small enough to fetch whole, and its first row
# spans two groups with DIFFERENT scales, which is what makes the oracle
# able to catch a group-indexing bug.
TENSOR = "language_model.model.layers.0.linear_attn.in_proj_a"
GROUP_SIZE = 128
BITS = 1
# How much of row 0 to freeze: two whole groups.
ORACLE_ELEMENTS = 256


def fetch(start, end_inclusive):
    req = urllib.request.Request(URL, headers={"Range": f"bytes={start}-{end_inclusive}"})
    with urllib.request.urlopen(req, timeout=120) as r:
        return r.read()


def main():
    header_len = struct.unpack("<Q", fetch(0, 7))[0]
    header = json.loads(fetch(8, 8 + header_len - 1))
    data_start = 8 + header_len

    planes = {}
    for suffix in ("weight", "scales", "biases"):
        info = header[f"{TENSOR}.{suffix}"]
        lo, hi = info["data_offsets"]
        raw = fetch(data_start + lo, data_start + hi - 1)
        planes[suffix] = (info, raw)

    w_info, w_raw = planes["weight"]
    rows, packed_words = w_info["shape"]
    cols = packed_words * (32 // BITS)
    n_groups = cols // GROUP_SIZE

    w = np.frombuffer(w_raw, dtype=np.uint32).reshape(rows, packed_words)
    s = np.frombuffer(planes["scales"][1], dtype=np.float16).reshape(rows, n_groups)
    b = np.frombuffer(planes["biases"][1], dtype=np.float16).reshape(rows, n_groups)

    with mx.stream(mx.cpu):
        out = mx.dequantize(mx.array(w), mx.array(s), mx.array(b), group_size=GROUP_SIZE, bits=BITS)
        deq = np.array(out.astype(mx.float32))

    # The two properties the Rust module states, re-measured here so the
    # generator reports them rather than the reader assuming them.
    sym = np.array_equal(b.astype(np.float32), -s.astype(np.float32) / 2)
    bits_lsb = np.zeros((rows, cols), dtype=np.uint8)
    raw_bytes = np.frombuffer(w_raw, dtype=np.uint8).reshape(rows, cols // 8)
    for j in range(cols // 8):
        for k in range(8):
            bits_lsb[:, j * 8 + k] = (raw_bytes[:, j] >> k) & 1
    lsb_ok = np.array_equal(
        bits_lsb.astype(np.float32) * np.repeat(s.astype(np.float32), GROUP_SIZE, axis=1)
        + np.repeat(b.astype(np.float32), GROUP_SIZE, axis=1),
        deq,
    )
    print(f"// Generated by scripts/mlx_1bit_oracle.py against mlx {mx.__version__}. Do not edit.")
    print("//")
    print(f"// Source: {REPO} {FILE}")
    print(f"//   tensor {TENSOR}")
    print(f"//   shape {rows}x{cols}, bits {BITS}, group_size {GROUP_SIZE}")
    print("//")
    print("// MLX quantized these bytes and MLX decoded these floats. The Rust")
    print("// decoder is the only side under test.")
    print("//")
    print("// Measured over the whole probed tensor while generating:")
    print(f"//   LSB-first bit order reproduces mx.dequantize exactly: {lsb_ok}")
    print(f"//   bias == -scale / 2 in all {rows * n_groups} groups: {sym}")
    if not lsb_ok or not sym:
        print("// WARNING: a property above is FALSE; the module header is stale.", file=sys.stderr)

    head_bytes = raw_bytes[0, : ORACLE_ELEMENTS // 8]
    head_groups = ORACLE_ELEMENTS // GROUP_SIZE
    s_bits = np.frombuffer(planes["scales"][1], dtype=np.uint16).reshape(rows, n_groups)
    b_bits = np.frombuffer(planes["biases"][1], dtype=np.uint16).reshape(rows, n_groups)

    print()
    print(f"/// Row 0's first {ORACLE_ELEMENTS} weights, as they are packed in the file.")
    print(f"pub const INT1_ORACLE_PACKED: [u8; {len(head_bytes)}] = {list(map(int, head_bytes))};")
    print()
    print("/// Their FP16 scale bit patterns, one per group.")
    print(
        f"pub const INT1_ORACLE_SCALES: [u16; {head_groups}] = "
        f"{list(map(int, s_bits[0, :head_groups]))};"
    )
    print()
    print("/// Their FP16 bias bit patterns, one per group.")
    print(
        f"pub const INT1_ORACLE_BIASES: [u16; {head_groups}] = "
        f"{list(map(int, b_bits[0, :head_groups]))};"
    )
    print()
    print("/// What `mx.dequantize` reads back out of those exact bytes.")
    print("#[allow(clippy::excessive_precision)]")
    floats = ", ".join(f"{v:.13g}" for v in deq[0, :ORACLE_ELEMENTS])
    print(f"pub const INT1_ORACLE_FLOATS: [f32; {ORACLE_ELEMENTS}] = [{floats}];")


if __name__ == "__main__":
    main()
