#!/usr/bin/env python3
"""Probe mlx-vlm's qwen3_vl vision preprocessing and emit Rust golden fixtures.

The reference is PROBED, never transcribed: every number in
`crates/vision-io/tests/generated/` is produced by calling the vendored
mlx-vlm code, so a fixture cannot encode this port's own misreading of it.

Run each mode from the repository root:

    uv run --python 3.12 --with mlx --with mlx-vlm --with numpy --with pillow \
      scripts/qwen3vl_vision_oracle.py smart_resize
    uv run --python 3.12 --with mlx --with mlx-vlm --with numpy --with pillow \
      scripts/qwen3vl_vision_oracle.py preprocess
    uv run --python 3.12 --with mlx --with mlx-vlm --with numpy --with pillow \
      scripts/qwen3vl_vision_oracle.py pos_embed
    uv run --python 3.12 --with mlx --with mlx-vlm --with numpy --with pillow \
      scripts/qwen3vl_vision_oracle.py rope_freqs
    uv run --python 3.12 --with mlx --with mlx-vlm --with numpy --with pillow \
      scripts/qwen3vl_vision_oracle.py mrope
    # or `all`

`--mlx-vlm PATH` points at the vendored checkout (default
`../mlx-v/mlx-vlm`, relative to the repository root). The installed mlx-vlm
wheel supplies the dependencies; the vendored tree is what actually gets
imported, so the fixtures track the source that was read.

TWO THINGS ABOUT THE FIXTURES THAT ARE DELIBERATE.

Source images are SYNTHETIC and their bytes are embedded in the fixture
rather than regenerated on the Rust side. JPEG decode is not bit-compatible
across decoders (Pillow and the `image` crate disagree on individual samples
of the same file), so a JPEG-sourced fixture would compare arithmetic plus a
decoder difference and a failure could not be attributed. Embedding the bytes
also removes any shared generator that could drift between the two languages.

Most cases run at a REDUCED patch geometry (patch 2 rather than 16) and a
custom pixel budget. Both are constructor arguments of the reference
processor, so the same code runs and every loop is exercised; what shrinks
is only the fixture, from a quarter of a megabyte per case to a few KB. One
case runs at the real geometry to prove the real dimensions, and the pixel
budget sweep runs at the real checkpoint budget throughout.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "crates" / "vision-io" / "tests" / "generated"

# The real checkpoint's own numbers, read off `preprocessor_config.json`
# (`docs/VISION_PHASE0.md` item 5). Not the generic Qwen2-VL library default.
REAL_PATCH = 16
REAL_MERGE = 2
REAL_TPS = 2
REAL_MIN_PIXELS = 65_536
REAL_MAX_PIXELS = 16_777_216

BANNER = """// @generated by scripts/qwen3vl_vision_oracle.py {mode} -- do not edit by hand.
//
// Probed from the vendored mlx-vlm reference at {source}.
// Regenerate with:
//
//     uv run --python 3.12 --with mlx --with mlx-vlm --with numpy --with pillow \\
//       scripts/qwen3vl_vision_oracle.py {mode}
"""


def synth_image(height: int, width: int, seed: int) -> "np.ndarray":
    """A deterministic, non-flat, non-random (C, H, W) uint8 image.

    Deterministic so the fixture is reproducible; non-flat because a constant
    image is invariant under every resize kernel and would prove nothing; not
    white noise because a resample of noise is dominated by aliasing and hides
    a wrong filter window under plausible-looking numbers.
    """
    import numpy as np

    ys = np.arange(height)[:, None]
    xs = np.arange(width)[None, :]
    planes = []
    for c in range(3):
        wave = (
            127.5
            + 90.0 * np.sin((ys * (2.0 + c) + xs * (3.0 - c) + seed) * 0.21)
            + 30.0 * np.cos((ys * xs + seed * 7) * 0.037)
        )
        planes.append(np.clip(wave, 0, 255).astype(np.uint8))
    return np.stack(planes, axis=0)


def rust_u8_slice(values) -> str:
    body = ", ".join(str(int(v)) for v in values)
    return f"&[{body}]"


def rust_f32_slice(values) -> str:
    import numpy as np

    # `format_float_positional(unique=True)` emits the SHORTEST decimal that
    # round-trips through float32, so the fixture is exact and a fraction of
    # the size a fixed `%.9e` would make it. NOT `repr`: numpy 2.x wraps a
    # scalar's repr as `np.float32(0.5)`, which is neither short nor Rust.
    body = ", ".join(
        np.format_float_positional(np.float32(v), unique=True) for v in values
    )
    return f"&[{body}]"


def write(path: Path, mode: str, source: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    header = BANNER.format(mode=mode, source=source)
    path.write_text(header + "\n" + body)
    print(f"wrote {path.relative_to(REPO_ROOT)} ({path.stat().st_size} bytes)")


# --------------------------------------------------------------------------
# Mode 1: smart_resize
# --------------------------------------------------------------------------


def emit_smart_resize(mod, source: Path) -> None:
    smart = mod.processing_qwen3_vl._smart_resize_image
    factor = REAL_PATCH * REAL_MERGE

    cases = []
    seen = set()

    def add(h, w, min_px, max_px):
        key = (h, w, min_px, max_px)
        if key in seen:
            return
        seen.add(key)
        try:
            out_h, out_w = smart(h, w, factor=factor, min_pixels=min_px, max_pixels=max_px)
        except ValueError:
            return  # refused by the aspect check; covered by its own case below
        cases.append((h, w, min_px, max_px, out_h, out_w))

    # A strided sweep at the REAL budget: ordinary photo and page shapes.
    for h in range(1, 2200, 137):
        for w in range(1, 2200, 211):
            add(h, w, REAL_MIN_PIXELS, REAL_MAX_PIXELS)

    # Banker's-rounding edges: every h/factor landing on an exact .5, where
    # Python's round() and f64::round disagree by a whole patch row.
    for k in range(1, 24):
        edge = int(factor * (k - 0.5))
        add(edge, edge, REAL_MIN_PIXELS, REAL_MAX_PIXELS)
        add(edge, 512, REAL_MIN_PIXELS, REAL_MAX_PIXELS)
        add(512, edge, REAL_MIN_PIXELS, REAL_MAX_PIXELS)
        add(edge, edge, 1, 1 << 40)  # both branches suppressed: pure rounding

    # Both budget branches taken deliberately, at a small budget so the
    # rescale is the thing under test rather than the source size.
    for h, w in [(64, 64), (65, 33), (200, 100), (33, 700), (1000, 40), (7, 9)]:
        add(h, w, 1024, 4096)
        add(h, w, 4096, 8192)
        add(h, w, 1, 1024)

    # The aspect-ratio limit from both sides. 200.0 exactly is accepted (the
    # reference tests `> 200`), 201 is refused.
    add(200, 1, REAL_MIN_PIXELS, REAL_MAX_PIXELS)
    add(1, 200, REAL_MIN_PIXELS, REAL_MAX_PIXELS)
    refused = []
    for h, w in [(201, 1), (1, 201), (4000, 3)]:
        try:
            smart(h, w, factor=factor, min_pixels=REAL_MIN_PIXELS, max_pixels=REAL_MAX_PIXELS)
        except ValueError:
            refused.append((h, w))
        else:
            raise SystemExit(f"expected {h}x{w} to be refused by the aspect check")

    rows = ",\n    ".join(f"({h}, {w}, {mn}, {mx}, {oh}, {ow})" for h, w, mn, mx, oh, ow in cases)
    refused_rows = ", ".join(f"({h}, {w})" for h, w in refused)
    body = f"""/// The rounding granularity: `patch_size * merge_size`.
pub const FACTOR: usize = {factor};
/// The real checkpoint's pixel budget, from its `preprocessor_config.json`.
pub const REAL_MIN_PIXELS: usize = {REAL_MIN_PIXELS};
pub const REAL_MAX_PIXELS: usize = {REAL_MAX_PIXELS};

/// `(orig_h, orig_w, min_pixels, max_pixels, resized_h, resized_w)`.
pub const CASES: &[(usize, usize, usize, usize, usize, usize)] = &[
    {rows},
];

/// `(orig_h, orig_w)` pairs the reference refuses on the aspect-ratio check.
pub const REFUSED: &[(usize, usize)] = &[{refused_rows}];
"""
    write(OUT_DIR / "smart_resize_oracle.rs", "smart_resize", source, body)


# --------------------------------------------------------------------------
# Mode 2: preprocess
# --------------------------------------------------------------------------

#: `(name, height, width, patch, merge, tps, min_pixels, max_pixels, full)`.
#:
#: The three `full` cases run at patch 2 rather than the real 16, which cuts
#: `patch_dim` from 1536 to 24 and the fixture from a quarter of a megabyte to
#: tens of kilobytes. Every loop in the pipeline is parameterized on the
#: geometry, so the same code runs; what shrinks is the fixture. Between them
#: they take all three `smart_resize` branches -- `tiny_a` is rounded and left
#: alone (and its 10/4 hits an exact `.5`, so banker's rounding is exercised
#: end to end rather than only in its own unit test), `tiny_upscaled` is below
#: `min_pixels`, `tiny_downscaled` is above `max_pixels`.
#:
#: `real_geometry` is the one case at the checkpoint's own patch 16 / merge 2.
#: It commits a STRIDED SAMPLE rather than whole rows: a leading-rows sample
#: would leave most patch rows unchecked, while a stride that is coprime with
#: `patch_dim` walks a different offset in every row.
PREPROCESS_CASES = [
    ("tiny_a", 10, 14, 2, 2, 2, 128, 4096, True),
    # An IDENTITY resize: 8x16 is already a whole number of factors and
    # already inside the budget, so the reference's early-out fires. Without
    # this case nothing here reaches that branch, and a bicubic resample of an
    # image onto its own size is NOT the identity (the kernel's half-pixel
    # centre offset makes it a mild blur), so removing the early-out would go
    # unnoticed.
    ("tiny_identity", 8, 16, 2, 2, 2, 16, 4096, True),
    ("tiny_upscaled", 3, 5, 2, 2, 2, 96, 4096, True),
    ("tiny_downscaled", 20, 28, 2, 2, 2, 16, 192, True),
    ("real_geometry", 34, 40, REAL_PATCH, REAL_MERGE, REAL_TPS, 1024, 65_536, False),
]

#: Sample stride for a `full = False` case. Coprime with 1536.
SAMPLE_STRIDE = 97


def emit_preprocess(mod, source: Path) -> None:
    import numpy as np

    chunks = []
    names = []
    for i, (name, h, w, patch, merge, tps, min_px, max_px, full) in enumerate(PREPROCESS_CASES):
        proc = mod.processing_qwen3_vl.Qwen3VLImageProcessor(
            patch_size=patch,
            temporal_patch_size=tps,
            merge_size=merge,
            min_pixels=min_px,
            max_pixels=max_px,
        )
        image = synth_image(h, w, seed=i * 13 + 1)
        pixel_values, grid = proc._process_one(image)
        pixel_values = np.asarray(pixel_values, dtype=np.float32)
        flat = pixel_values.reshape(-1)
        sample_indices = list(range(0, len(flat), 1 if full else SAMPLE_STRIDE))
        kept = flat[sample_indices]

        upper = name.upper()
        names.append(upper)
        # `image` is (C, H, W); the fixture stores it interleaved (y, x, c),
        # which is what a decoder hands back and what the Rust side takes.
        interleaved = np.transpose(image, (1, 2, 0)).reshape(-1)
        stride_note = (
            "Every element."
            if full
            else f"Every {SAMPLE_STRIDE}th element of {len(flat)}."
        )
        chunks.append(
            f"""/// `{name}`: {h}x{w} source, patch {patch}, merge {merge}, temporal {tps},
/// budget {min_px}..{max_px}. {stride_note}
pub const {upper}_GEOMETRY: (usize, usize, usize) = ({patch}, {merge}, {tps});
pub const {upper}_BUDGET: (usize, usize) = ({min_px}, {max_px});
pub const {upper}_SRC_HW: (usize, usize) = ({h}, {w});
/// Interleaved `(y, x, c)` RGB8.
pub const {upper}_SRC: &[u8] = {rust_u8_slice(interleaved)};
/// `(t, h, w)` in patches.
pub const {upper}_GRID: (usize, usize, usize) = ({grid[0]}, {grid[1]}, {grid[2]});
pub const {upper}_PATCH_ROWS_TOTAL: usize = {pixel_values.shape[0]};
pub const {upper}_PATCH_DIM: usize = {pixel_values.shape[1]};
/// Stride between committed elements: 1 when every element is committed.
pub const {upper}_SAMPLE_STRIDE: usize = {1 if full else SAMPLE_STRIDE};
/// Reference `pixel_values` flattened, trailing axes in the reference's own
/// `(C, T, P_h, P_w)` order -- NOT this crate's `(T, P_h, P_w, C)`. The
/// parity test applies the permutation explicitly.
pub const {upper}_PIXEL_VALUES: &[f32] = {rust_f32_slice(kept)};
"""
        )

    listing = ", ".join(f'"{n.lower()}"' for n in names)
    body = f"""/// Case names, for a test that wants to report which one failed.
pub const CASE_NAMES: &[&str] = &[{listing}];

""" + "\n".join(chunks)
    write(OUT_DIR / "preprocess_oracle.rs", "preprocess", source, body)


# --------------------------------------------------------------------------
# Mode 3: pos_embed interpolation
# --------------------------------------------------------------------------

#: `(grid_h, grid_w)` pairs. The three interesting shapes are a non-square
#: grid, a grid LARGER than the table's side (upsampling past it), and a
#: single-patch axis, which is where `linspace(0, n-1, 1)` degenerates.
POS_EMBED_GRIDS = [(2, 2), (4, 6), (8, 8), (12, 10), (2, 16), (6, 2)]
POS_EMBED_SIDE = 8  # num_position_embeddings = 64
POS_EMBED_HIDDEN = 4


def emit_pos_embed(mod, source: Path) -> None:
    import mlx.core as mx
    import numpy as np

    cfg = mod.config.VisionConfig(
        depth=1,
        hidden_size=POS_EMBED_HIDDEN,
        intermediate_size=POS_EMBED_HIDDEN,
        out_hidden_size=POS_EMBED_HIDDEN,
        num_heads=1,
        patch_size=4,
        spatial_merge_size=2,
        temporal_patch_size=2,
        num_position_embeddings=POS_EMBED_SIDE * POS_EMBED_SIDE,
        deepstack_visual_indexes=[],
    )
    model = mod.vision.VisionModel(cfg)
    assert model.num_grid_per_side == POS_EMBED_SIDE, model.num_grid_per_side

    # A deterministic table. Distinct per (row, column) so a wrong index is
    # visible, and spread over a range where a wrong weight is visible too.
    table = np.arange(POS_EMBED_SIDE * POS_EMBED_SIDE * POS_EMBED_HIDDEN, dtype=np.float32)
    table = (np.sin(table * 0.37) * 3.0 + np.cos(table * 0.11)).astype(np.float32)
    table = table.reshape(POS_EMBED_SIDE * POS_EMBED_SIDE, POS_EMBED_HIDDEN)
    model.pos_embed.weight = mx.array(table)

    chunks = []
    for h, w in POS_EMBED_GRIDS:
        out = model.fast_pos_embed_interpolate(mx.array([[1, h, w]]))
        out = np.asarray(out, dtype=np.float32)
        chunks.append(
            f"""/// grid `(1, {h}, {w})`: `{out.shape[0]}` rows of {POS_EMBED_HIDDEN},
/// already permuted into merge-window order by the reference.
pub const GRID_{h}X{w}: (usize, usize, usize) = (1, {h}, {w});
pub const OUT_{h}X{w}: &[f32] = {rust_f32_slice(out.reshape(-1))};
"""
        )

    body = f"""pub const SIDE: usize = {POS_EMBED_SIDE};
pub const HIDDEN: usize = {POS_EMBED_HIDDEN};
pub const MERGE_SIZE: usize = 2;
/// The seeded `pos_embed.weight`, `SIDE * SIDE` rows of `HIDDEN`.
pub const TABLE: &[f32] = {rust_f32_slice(table.reshape(-1))};

""" + "\n".join(chunks)
    write(OUT_DIR / "pos_embed_oracle.rs", "pos_embed", source, body)


# --------------------------------------------------------------------------
# Mode 4: vision rope frequency rows
# --------------------------------------------------------------------------

#: A non-square grid, a very wide one, and a `t > 1` grid, which is where
#: `rot_pos_emb` tiles the coordinate list rather than extending it.
ROPE_GRIDS = [(1, 2, 2), (1, 4, 6), (1, 2, 10), (2, 4, 4)]
#: The real tower's head dim: hidden 1152 over 16 heads.
ROPE_HEAD_DIM = 72


def emit_rope_freqs(mod, source: Path) -> None:
    import mlx.core as mx
    import numpy as np

    cfg = mod.config.VisionConfig(
        depth=1,
        hidden_size=ROPE_HEAD_DIM * 2,
        intermediate_size=ROPE_HEAD_DIM,
        out_hidden_size=ROPE_HEAD_DIM,
        num_heads=2,
        patch_size=4,
        spatial_merge_size=2,
        temporal_patch_size=2,
        num_position_embeddings=64,
        deepstack_visual_indexes=[],
    )
    model = mod.vision.VisionModel(cfg)

    chunks = []
    for t, h, w in ROPE_GRIDS:
        rows = np.asarray(model.rot_pos_emb(mx.array([[t, h, w]])), dtype=np.float32)
        chunks.append(
            f"""/// grid `({t}, {h}, {w})`: `{rows.shape[0]}` rows of {rows.shape[1]}.
pub const GRID_{t}_{h}X{w}: (usize, usize, usize) = ({t}, {h}, {w});
pub const ROWS_{t}_{h}X{w}: &[f32] = {rust_f32_slice(rows.reshape(-1))};
"""
        )

    body = f"""/// `hidden_size / num_heads` for the real tower.
pub const HEAD_DIM: usize = {ROPE_HEAD_DIM};
/// The vision tower's rope base -- the library default, NOT the trunk's 1e7.
pub const THETA: f32 = 10000.0;
pub const MERGE_SIZE: usize = 2;

""" + "\n".join(chunks)
    write(OUT_DIR / "rope_freqs_oracle.rs", "rope_freqs", source, body)


# --------------------------------------------------------------------------
# Mode 5: mRoPE position triples
# --------------------------------------------------------------------------

VISION_START = 151_652
IMAGE_PAD = 151_655
VIDEO_PAD = 151_656
MERGE = 2


def mrope_cases():
    """`(name, ids, grids)`. Ids other than the two markers are arbitrary text.

    `grids` are `(t, h, w)` in PATCHES; the walk divides the spatial axes by
    the merge size itself.
    """

    def image(grid):
        t, h, w = grid
        return [VISION_START] + [IMAGE_PAD] * (t * (h // MERGE) * (w // MERGE))

    text = lambda n, base=1000: list(range(base, base + n))  # noqa: E731

    return [
        ("text_only", text(9), []),
        ("image_mid", text(4) + image((1, 4, 6)) + text(3, 2000), [(1, 4, 6)]),
        ("image_at_start", image((1, 2, 2)) + text(5), [(1, 2, 2)]),
        ("image_at_end", text(6) + image((1, 6, 4)), [(1, 6, 4)]),
        (
            "two_images",
            text(2) + image((1, 2, 4)) + text(3, 2000) + image((1, 4, 2)) + text(2, 3000),
            [(1, 2, 4), (1, 4, 2)],
        ),
        ("adjacent_images", image((1, 2, 2)) + image((1, 4, 4)), [(1, 2, 2), (1, 4, 4)]),
        ("square_image", text(1) + image((1, 8, 8)) + text(1, 2000), [(1, 8, 8)]),
    ]


def emit_mrope(mod, source: Path) -> None:
    import types

    import mlx.core as mx
    import numpy as np

    chunks = []
    names = []
    for name, ids, grids in mrope_cases():
        # `get_rope_index` reads only `self.config`, so it is called as an
        # unbound function against a duck-typed stand-in. Constructing a real
        # LanguageModel would allocate a whole trunk to reach a pure index
        # walk (and mlx's nn.Module blocks `object.__new__` anyway).
        holder = types.SimpleNamespace(config=_mrope_config(mod))
        grid_arg = mx.array(grids, dtype=mx.int32) if grids else None
        positions, delta = mod.language.LanguageModel.get_rope_index(
            holder, mx.array([ids], dtype=mx.int32), image_grid_thw=grid_arg
        )
        positions = np.asarray(positions, dtype=np.int32)
        # The text-only branch returns a (batch, seq) 1-D arange rather than
        # the (3, batch, seq) stack; broadcast it so the fixture is one shape.
        if positions.ndim == 2:
            triples = np.repeat(positions[None, :, :], 3, axis=0)[:, 0, :]
        else:
            triples = positions[:, 0, :]
        delta = int(np.asarray(delta).reshape(-1)[0])

        flat = ", ".join(
            f"({triples[0][i]}, {triples[1][i]}, {triples[2][i]})" for i in range(len(ids))
        )
        grid_rows = ", ".join(f"({t}, {h}, {w})" for t, h, w in grids)
        id_rows = ", ".join(str(int(i)) for i in ids)
        upper = name.upper()
        names.append(upper)
        chunks.append(
            f"""/// `{name}`
pub const {upper}_IDS: &[i32] = &[{id_rows}];
/// `(t, h, w)` in PATCHES, before the merge divide.
pub const {upper}_GRIDS: &[(usize, usize, usize)] = &[{grid_rows}];
pub const {upper}_TRIPLES: &[(i32, i32, i32)] = &[{flat}];
pub const {upper}_ROPE_DELTA: i32 = {delta};
"""
        )

    listing = ", ".join(f'"{n.lower()}"' for n in names)
    body = f"""pub const VISION_START_ID: i32 = {VISION_START};
pub const IMAGE_PAD_ID: i32 = {IMAGE_PAD};
pub const MERGE_SIZE: usize = {MERGE};
pub const CASE_NAMES: &[&str] = &[{listing}];

""" + "\n".join(chunks)
    write(OUT_DIR / "mrope_oracle.rs", "mrope", source, body)


def _mrope_config(mod):
    """The smallest object `get_rope_index` reads: four ids and a merge size."""

    class VC:
        spatial_merge_size = MERGE

    class C:
        vision_config = VC()
        image_token_id = IMAGE_PAD
        video_token_id = VIDEO_PAD
        vision_start_token_id = VISION_START

    return C()


# --------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "mode",
        choices=["smart_resize", "preprocess", "pos_embed", "rope_freqs", "mrope", "all"],
    )
    parser.add_argument(
        "--mlx-vlm",
        default=str(REPO_ROOT.parent / "mlx-v" / "mlx-vlm"),
        help="the vendored mlx-vlm checkout to import from",
    )
    args = parser.parse_args()

    vendored = Path(args.mlx_vlm).resolve()
    if not (vendored / "mlx_vlm").is_dir():
        raise SystemExit(f"no mlx_vlm package under {vendored}")
    sys.path.insert(0, str(vendored))

    import importlib
    import types

    mod = types.SimpleNamespace(
        processing_qwen3_vl=importlib.import_module(
            "mlx_vlm.models.qwen3_vl.processing_qwen3_vl"
        ),
        vision=importlib.import_module("mlx_vlm.models.qwen3_vl.vision"),
        language=importlib.import_module("mlx_vlm.models.qwen3_vl.language"),
        config=importlib.import_module("mlx_vlm.models.qwen3_vl.config"),
    )
    imported = Path(mod.vision.__file__).resolve()
    if not str(imported).startswith(str(vendored)):
        raise SystemExit(
            f"imported {imported}, which is not under {vendored}; "
            "an installed wheel is shadowing the vendored tree"
        )
    source = imported.parent

    emitters = {
        "smart_resize": emit_smart_resize,
        "preprocess": emit_preprocess,
        "pos_embed": emit_pos_embed,
        "rope_freqs": emit_rope_freqs,
        "mrope": emit_mrope,
    }
    modes = list(emitters) if args.mode == "all" else [args.mode]
    for mode in modes:
        emitters[mode](mod, source)
    return 0


if __name__ == "__main__":
    os.chdir(REPO_ROOT)
    raise SystemExit(main())
