// PORT-LOCAL, AND A MEASURED DEAD END. Kept, with its bench, because
// `simdgroup_matrix` is the lever every reader reaches for next and
// `docs/SPECULATIVE_DECODING.md` named it as "the one remaining lever".
// It is not one.
//
// Measured 2026-08-17 against the SIMD sibling, same session, same
// matrices, `c(M)` on gate/up 17408x5120 (and the same shape on every
// other row of QWEN38_SHAPES):
//
//   M      exact   matrix   matrix/exact
//   2      0.52     3.39      6.56x slower
//   4      0.58     1.69      2.92x
//   8      0.48     0.85      1.76x
//   16     0.47     0.62      1.33x
//   32       --     0.52      past the SIMD kernel's cap
//   64       --     0.58      past the SIMD kernel's cap
//
// **IT LOSES AT EVERY WIDTH, AND THE PLATEAU IS THE FINDING.** Past M=16 it
// stops improving at ~0.5 -- worse than what the exact kernel already
// reaches at M=16 -- so this is not an implementation that more batching
// would rescue. Two hypotheses were tested and killed on the way: widening
// the staged K block from 8 to 64 (cutting barriers eightfold) changed
// nothing, and running past the SIMD kernel's register cap to M=32 and 64
// changed nothing.
//
// The reason it cannot work here: a packed INT4 run cannot be
// `simdgroup_load`ed, so every weight element must be dequantized into
// threadgroup memory first. That work is proportional to rows x K and is
// INDEPENDENT OF B, while the MAC work matrix hardware accelerates is
// proportional to rows x K x B. At the widths this engine has, the kernel
// is dequant-bound, and matrix hardware is accelerating the term that is
// not the cost. It would take weights that are already in a loadable
// format, not a better tiling.
//
// So the exact kernel wins on BOTH axes: it is faster AND it is
// bit-identical to a sequential decode. Nothing dispatches this one.
//
// `dequant_int4_gemm_mma` is the matrix-hardware form of
// `dequant_int4_gemm_simd`, and it is a SEPARATE KERNEL rather than a
// function-constant variant for a reason that is not style:
//
//   **IT IS NOT BIT-EXACT AGAINST THE GEMV, BY CONSTRUCTION.**
//
// `simdgroup_multiply_accumulate` reduces its K dimension in hardware, in
// an order Apple does not document and this port cannot control, where both
// the GEMV and the SIMD GEMM walk K in a fixed sequence into one FP32
// accumulator. So a verify pass built on this kernel would stop agreeing
// bit-for-bit with a sequential decode, and speculative output would stop
// being provably identical to non-speculative output -- the property
// AGENTS.md Gotcha 27 exists to protect, the one `accept_length_probe.rs`
// is written around, and the bar `docs/BATCHED_PREFILL.md` sets for a
// chunked prefill ("byte-identity is the bar, not coherence").
//
// Keeping both kernels is therefore the whole design: the exact one stays
// the default and this one is reachable only from a caller that has
// accepted the trade in writing. Never make this a fast path selected by a
// heuristic -- that would make the generated bytes a function of a shape.
//
// Concatenated AFTER dequant_int4.metal (crate Gotcha 4) for kGroupSize.

#include <metal_simdgroup_matrix>

// One SIMD group owns an 8-row x 8-column output tile and there is exactly
// ONE SIMD group per threadgroup. That is deliberate: the dequantized
// weight tile has to be staged in threadgroup memory (a packed INT4 run
// cannot be `simdgroup_load`ed directly), and with one SIMD group the
// staging needs only `simdgroup_barrier`, not `threadgroup_barrier`. The
// header of the SIMD kernel next door records that full threadgroup
// barriers across eight SIMD groups cost more than the staging saves; this
// shape is what avoids re-learning that.
constant constexpr uint kMmaTile = 8;
// Eight column tiles covers B up to 64. The SIMD sibling stops at 16
// because its accumulators are a per-thread register array; this kernel's
// are `simdgroup_matrix` accumulators spread across the SIMD group, ~4
// registers per lane per tile, so it is not bound the same way. That
// difference is the reason to measure it past 16: see MMA_MAX_BATCH_ROWS.
constant constexpr uint kMmaMaxColTiles = 8;
// K elements staged per barrier pair. **This is the whole cost model of
// this kernel.** A packed INT4 run cannot be `simdgroup_load`ed, so the
// weight tile has to be dequantized into threadgroup memory first, and the
// first draft staged only kMmaTile (8) at a time -- 640 staging rounds and
// 1280 barriers per output tile at N=5120, which made it 5.5x SLOWER than
// the plain SIMD kernel at M=2. Staging kMmaK at once amortizes the
// barriers over kMmaK/8 matrix multiplies.
constant constexpr uint kMmaK = 64;
constant constexpr uint kMmaKTiles = kMmaK / kMmaTile;

kernel void dequant_int4_gemm_mma(
    device const uint8_t* W      [[buffer(0)]],
    device const bfloat*  scales [[buffer(1)]],
    device const bfloat*  biases [[buffer(2)]],
    device const half*    x      [[buffer(3)]],
    device half*          y      [[buffer(4)]],
    constant uint&        M      [[buffer(5)]],
    constant uint&        N      [[buffer(6)]],
    constant uint&        B      [[buffer(7)]],
    uint                  tg_idx [[threadgroup_position_in_grid]],
    uint                  lane   [[thread_index_in_simdgroup]]
) {
    const uint row0 = tg_idx * kMmaTile;
    if (row0 >= M) return;

    const uint n_groups  = N / kGroupSize;
    const uint row_bytes = N / 2;
    const uint col_tiles = (B + kMmaTile - 1u) / kMmaTile;

    // Staging for the dequantized weight tile, and for the result on the
    // way out. The result staging is not optional: `y` is [B, M] and a
    // direct transposed store would write all eight batch rows, running
    // past the end of a caller's buffer whenever B is not a multiple of 8.
    threadgroup half w_tile[kMmaTile * kMmaK];
    // FLOAT, matching the accumulator: `simdgroup_store` deduces one type
    // for the matrix and the destination, so a half staging tile does not
    // compile against a `simdgroup_float8x8`. The narrowing to `y`'s half
    // happens in the copy-out below, which is where the GEMV does it too.
    threadgroup float y_tile[kMmaTile * kMmaTile];

    simdgroup_float8x8 acc[kMmaMaxColTiles];
    for (uint t = 0; t < kMmaMaxColTiles; ++t) {
        acc[t] = make_filled_simdgroup_matrix<float, 8, 8>(0.0f);
    }

    // Each lane dequantizes kMmaTile * kMmaK / 32 of the staged elements.
    constexpr uint per_lane = (kMmaTile * kMmaK) / 32u;

    for (uint n0 = 0; n0 < N; n0 += kMmaK) {
        // Dequantize W[row0 .. row0+8, n0 .. n0+kMmaK] into threadgroup
        // memory, row-major with stride kMmaK. A row past M is filled with
        // zeros rather than skipped, so the multiply stays uniform across
        // the SIMD group.
        for (uint slot = 0; slot < per_lane; ++slot) {
            const uint e = lane * per_lane + slot;
            const uint m = e / kMmaK;
            const uint k = e % kMmaK;
            const uint row = row0 + m;
            half value = 0.0h;
            if (row < M) {
                const uint n = n0 + k;
                const uint8_t byte = W[uint(row) * row_bytes + (n >> 1)];
                const uint q = (n & 1u) ? uint(byte >> 4) : uint(byte & 0x0Fu);
                const uint g = n / kGroupSize;
                const float s = float(scales[uint(row) * n_groups + g]);
                const float b = float(biases[uint(row) * n_groups + g]);
                value = half(fma(float(q), s, b));
            }
            w_tile[e] = value;
        }
        simdgroup_barrier(mem_flags::mem_threadgroup);

        for (uint kt = 0; kt < kMmaKTiles; ++kt) {
            simdgroup_half8x8 w_mat;
            simdgroup_load(w_mat, w_tile + kt * kMmaTile, kMmaK);
            for (uint t = 0; t < col_tiles; ++t) {
                // `x` is [B, N]; the tile at (t*8, n0 + kt*8) with row
                // stride N is [8 batch][8 k], and the multiply wants
                // [8 k][8 batch], so it is loaded transposed. Rows past B
                // are not read: `col_tiles` is ceil(B/8) and the caller
                // sizes `x` for a whole number of tiles, which the host
                // documents and the test honours.
                simdgroup_half8x8 x_mat;
                simdgroup_load(x_mat,
                               x + uint(t) * kMmaTile * N + n0 + kt * kMmaTile,
                               N,
                               ulong2(0, 0),
                               true);
                simdgroup_multiply_accumulate(acc[t], w_mat, x_mat, acc[t]);
            }
        }
        simdgroup_barrier(mem_flags::mem_threadgroup);
    }

    for (uint t = 0; t < col_tiles; ++t) {
        // Store transposed so the staging tile is [8 batch][8 row], which
        // is `y`'s own order, then copy out only the rows and columns that
        // exist.
        simdgroup_store(acc[t], y_tile, kMmaTile, ulong2(0, 0), true);
        simdgroup_barrier(mem_flags::mem_threadgroup);
        for (uint e = lane; e < kMmaTile * kMmaTile; e += 32u) {
            const uint b = t * kMmaTile + e / kMmaTile;
            const uint m = row0 + e % kMmaTile;
            if (b < B && m < M) {
                y[b * M + m] = half(y_tile[e]);
            }
        }
        simdgroup_barrier(mem_flags::mem_threadgroup);
    }
}
