//! Fixture parity tests for the MossFormer2 SE port.
//!
//! Fixtures live in `testdata/mossformer2_se/`, regenerated by
//! `tools/gen_mossformer2_se_fixtures.py` against the pinned mlx-audio
//! commit with dither=0 fbank features (the reference default is
//! stochastic). A local real checkpoint directory can be pointed at
//! via TURBOSPARK_MOSSFORMER2_SE_MODEL and is skipped when absent.
//! Tests never download.

use std::path::{Path, PathBuf};

use super::{MossFormer2Se, MossFormer2SeConfig};
use turbospark_model_io::safetensors::SafetensorsFile;

fn testdata(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata/mossformer2_se")
        .join(name)
}

fn read_json(name: &str) -> serde_json::Value {
    let text = std::fs::read_to_string(testdata(name)).expect(name);
    serde_json::from_str(&text).expect(name)
}

fn read_npy(name: &str) -> (Vec<usize>, Vec<f32>) {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    let data = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (shape, data)
}

fn max_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(
        a.len(),
        b.len(),
        "length mismatch {} vs {}",
        a.len(),
        b.len()
    );
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
}

fn load_model() -> MossFormer2Se {
    let config: MossFormer2SeConfig =
        MossFormer2SeConfig::from_json(&read_json("config.json")).unwrap();
    let file = SafetensorsFile::open(&testdata("tiny_weights.safetensors")).expect("weights");
    MossFormer2Se::load(config, &file).unwrap()
}

#[test]
fn config_parses_and_validates() {
    let config = MossFormer2SeConfig::from_json(&read_json("config.json")).unwrap();
    assert_eq!(config.sample_rate, 48000);
    assert_eq!(config.win_len, 1920);
    assert_eq!(config.win_inc, 384);
    assert_eq!(config.num_mels, 60);
    assert_eq!(config.in_channels, 180);
    assert_eq!(config.out_channels, 64);
    assert_eq!(config.out_channels_final, 961);
    assert_eq!(config.num_blocks, 2);

    let mut broken = read_json("config.json");
    broken["out_channels_final"] = serde_json::json!(100);
    assert!(MossFormer2SeConfig::from_json(&broken).is_err());
    let mut broken = read_json("config.json");
    broken["in_channels"] = serde_json::json!(100);
    assert!(MossFormer2SeConfig::from_json(&broken).is_err());
}

#[test]
fn kaldi_features_match_reference() {
    let model = load_model();
    let (_, wave) = read_npy("wave.npy");
    // The reference computes features on the 32768-scaled audio.
    let scaled: Vec<f32> = wave.iter().map(|&v| v * 32768.0).collect();
    let (fbank_shape, golden_fbank) = read_npy("fbank.npy");
    let fbank = model.kaldi_fbank(&scaled, 0.0).unwrap();
    assert_eq!(fbank.len(), fbank_shape[0] * fbank_shape[1]);
    let diff = max_diff(&fbank, &golden_fbank);
    eprintln!("fbank max diff {diff}");
    assert!(diff < 1e-4, "fbank diff {diff}");

    let (_, golden_delta) = read_npy("delta.npy");
    let (_, golden_ddelta) = read_npy("ddelta.npy");
    let frames = fbank_shape[0];
    let mels = fbank_shape[1];
    let mut fbank_t = vec![0.0f32; frames * mels];
    for f in 0..frames {
        for c in 0..mels {
            fbank_t[c * frames + f] = fbank[f * mels + c];
        }
    }
    let delta_t = MossFormer2Se::kaldi_deltas(&fbank_t, mels, frames, 5);
    let ddelta_t = MossFormer2Se::kaldi_deltas(&delta_t, mels, frames, 5);
    let mut delta = vec![0.0f32; frames * mels];
    let mut ddelta = vec![0.0f32; frames * mels];
    for f in 0..frames {
        for c in 0..mels {
            delta[f * mels + c] = delta_t[c * frames + f];
            ddelta[f * mels + c] = ddelta_t[c * frames + f];
        }
    }
    let diff = max_diff(&delta, &golden_delta);
    eprintln!("delta max diff {diff}");
    assert!(diff < 5e-5, "delta diff {diff}");
    let diff = max_diff(&ddelta, &golden_ddelta);
    eprintln!("ddelta max diff {diff}");
    assert!(diff < 2e-5, "ddelta diff {diff}");
}

#[test]
fn nonzero_dither_refused() {
    let model = load_model();
    let wave = vec![0.1f32; 48000];
    assert!(model.kaldi_fbank(&wave, 1.0).is_err());
}

#[test]
fn network_stages_match_reference() {
    let model = load_model();
    let (_, features) = read_npy("features.npy");
    let (features_shape, _) = read_npy("features.npy");
    let frames = features_shape[0];
    let masknet = &model.masknet;

    let mut x = features.clone();
    masknet.gln.run(&mut x, frames);
    let (_, golden_normed) = read_npy("net_normed.npy");
    let diff = max_diff(&x, &golden_normed);
    eprintln!("gln max diff {diff}");
    assert!(diff < 2e-5, "gln diff {diff}");

    let encoded = masknet.encoder.run(&x, frames);
    let (_, golden_encoded) = read_npy("net_encoded.npy");
    let diff = max_diff(&encoded, &golden_encoded);
    eprintln!("encoded max diff {diff}");
    assert!(diff < 3e-5, "encoded diff {diff}");

    let flash_out = masknet.mdl.layers[0].forward(&read_npy("net_pos_added.npy").1, frames);
    let (_, golden_flash0) = read_npy("net_flash0.npy");
    let diff = max_diff(&flash_out, &golden_flash0);
    eprintln!("flash0 max diff {diff}");
    assert!(diff < 2e-5, "flash0 diff {diff}");

    let gfsmn_out = masknet.mdl.fsmns[0].forward(&golden_flash0, frames);
    let (_, golden_gfsmn0) = read_npy("net_gfsmn0.npy");
    let diff = max_diff(&gfsmn_out, &golden_gfsmn0);
    eprintln!("gfsmn0 max diff {diff}");
    assert!(diff < 5e-5, "gfsmn0 diff {diff}");
}

#[test]
fn mask_matches_reference() {
    let model = load_model();
    let (_, features) = read_npy("features.npy");
    let (features_shape, _) = read_npy("features.npy");
    let frames = features_shape[0];
    let mask = model.masknet.forward(&features, frames);
    let (_, golden_mask) = read_npy("net_mask.npy");
    assert_eq!(mask.len(), frames * model.config.out_channels_final);
    let diff = max_diff(&mask, &golden_mask);
    eprintln!("mask max diff {diff}");
    assert!(diff < 1e-5, "mask diff {diff}");
}

#[test]
fn stft_and_masked_spectrum_match_reference() {
    let model = load_model();
    let (_, wave) = read_npy("wave.npy");
    let scaled: Vec<f32> = wave.iter().map(|&v| v * 32768.0).collect();
    let spectra = model.stft_frames(&scaled).unwrap();
    let (_, golden_real) = read_npy("stft_real.npy");
    let (_, golden_imag) = read_npy("stft_imag.npy");
    let (stft_shape, _) = read_npy("stft_real.npy");
    let frames = stft_shape[0];
    let freqs = stft_shape[1];
    assert_eq!(spectra.len(), frames);
    let mut real = Vec::with_capacity(frames * freqs);
    let mut imag = Vec::with_capacity(frames * freqs);
    for spectrum in &spectra {
        for value in spectrum {
            real.push(value.re);
            imag.push(value.im);
        }
    }
    let diff = max_diff(&real, &golden_real);
    // Different f32 FFT algorithms (radix-2 here, MLX's own) leave a
    // small relative residue on 32768-scale values; compare against
    // the peak magnitude.
    let peak = golden_real
        .iter()
        .fold(0.0f32, |a, &v| a.max(v.abs()))
        .max(1.0);
    eprintln!("stft real max diff {diff} peak {peak}");
    assert!(diff < 1e-3 * peak, "stft real diff {diff} peak {peak}");
    let diff = max_diff(&imag, &golden_imag);
    eprintln!("stft imag max diff {diff}");
    assert!(diff < 1e-3 * peak, "stft imag diff {diff} peak {peak}");

    // Mask application and iSTFT together reproduce the enhanced audio.
    let (_, golden_mask) = read_npy("net_mask.npy");
    let mut masked = Vec::with_capacity(frames * freqs);
    for f in 0..frames {
        for b in 0..freqs {
            let m = golden_mask[f * freqs + b];
            masked.push(crate::fft::ComplexF32::new(
                real[f * freqs + b] * m,
                imag[f * freqs + b] * m,
            ));
        }
    }
    let mut spectra = Vec::with_capacity(frames);
    for f in 0..frames {
        spectra.push(masked[f * freqs..(f + 1) * freqs].to_vec());
    }
    let enhanced = model.istft(&spectra, scaled.len()).unwrap();
    let (_, golden_enhanced) = read_npy("enhanced.npy");
    let diff = max_diff(&enhanced, &golden_enhanced);
    eprintln!("enhanced max diff {diff}");
    assert!(diff < 5e-2, "enhanced diff {diff}");
}

#[test]
fn end_to_end_matches_reference() {
    let model = load_model();
    let (_, wave) = read_npy("wave.npy");
    let enhanced = model.enhance(&wave).unwrap();
    let (_, golden_enhanced) = read_npy("enhanced.npy");
    // The fixture captures the iSTFT output on the 32768-scaled
    // reference path, before the final division in _decode_one_audio.
    let golden: Vec<f32> = golden_enhanced.iter().map(|&v| v / 32768.0).collect();
    let diff = max_diff(&enhanced, &golden);
    eprintln!("end-to-end max diff {diff}");
    assert!(diff < 1e-4, "end-to-end diff {diff}");
    // Enhancement must not blow up: peak stays bounded.
    let peak = enhanced.iter().fold(0.0f32, |a, &v| a.max(v.abs()));
    assert!(peak < 4.0, "enhanced peak {peak}");
}

/// Segmented and chunked reassembly are covered by invariant tests:
/// the reference index math must tile the output with the documented
/// discard pattern. The full-path parity fixture pins `process_chunk`.
#[test]
fn segmented_reassembly_invariants() {
    let model = load_model();
    // 22 s of audio crosses the 20 s segmented threshold.
    let sample_rate = model.config.sample_rate;
    let audio: Vec<f32> = (0..22 * sample_rate)
        .map(|i| ((i as f32) * 110.0 * std::f32::consts::TAU / sample_rate as f32).sin() * 0.2)
        .collect();
    let out = model.enhance(&audio).unwrap();
    assert_eq!(out.len(), audio.len());
    assert!(out.iter().all(|v| v.is_finite()));
}

#[test]
fn chunked_reassembly_invariants() {
    let model = load_model();
    // Force the chunked path on 3 s of audio (single chunk + partial).
    let sample_rate = model.config.sample_rate;
    let audio: Vec<f32> = (0..3 * sample_rate)
        .map(|i| ((i as f32) * 220.0 * std::f32::consts::TAU / sample_rate as f32).sin() * 0.2)
        .collect();
    let out = model.enhance_with_mode(&audio, Some(true)).unwrap();
    assert_eq!(out.len(), audio.len());
    assert!(out.iter().all(|v| v.is_finite()));
}

/// Real-checkpoint gate; opt-in via TURBOSPARK_MOSSFORMER2_SE_MODEL
/// pointing at a directory with model.safetensors (fp32 or fp16, or
/// int8; config.json optional). Skips when unset.
#[test]
fn real_checkpoint_gate() {
    let Ok(dir) = std::env::var("TURBOSPARK_MOSSFORMER2_SE_MODEL") else {
        eprintln!("skipping: TURBOSPARK_MOSSFORMER2_SE_MODEL not set");
        return;
    };
    let model = MossFormer2Se::open(Path::new(&dir)).unwrap();
    // When the reference output for the stored clip exists, compare
    // directly; the clip was generated with numpy default_rng(31337)
    // and enhanced by the fp16 checkpoint via from_pretrained.
    if testdata("real_clip.npy").exists() && testdata("real_enhanced.npy").exists() {
        let (_, clip) = read_npy("real_clip.npy");
        let (_, golden) = read_npy("real_enhanced.npy");
        let enhanced = model.enhance(&clip).unwrap();
        assert_eq!(enhanced.len(), golden.len());
        let peak = golden.iter().fold(0.0f32, |a, &v| a.max(v.abs())).max(1e-6);
        let diff = max_diff(&enhanced, &golden);
        eprintln!("real checkpoint enhanced diff {diff} peak {peak}");
        assert!(diff < 5e-2, "real checkpoint diff {diff} peak {peak}");
        return;
    }
    // 1 s: a clean tone plus strong white noise.
    let sample_rate = model.config.sample_rate;
    let mut state = 0x2545_F491_4F6C_DD1Du64;
    let mut next = || {
        state ^= state << 13;
        state ^= state >> 7;
        state ^= state << 17;
        (state >> 40) as f32 / (1u32 << 24) as f32 - 1.0
    };
    let audio: Vec<f32> = (0..sample_rate)
        .map(|i| {
            0.3 * ((i as f32) * 440.0 * std::f32::consts::TAU / sample_rate as f32).sin()
                + 0.3 * next()
        })
        .collect();
    let enhanced = model.enhance(&audio).unwrap();
    assert_eq!(enhanced.len(), audio.len());
    assert!(enhanced.iter().all(|v| v.is_finite()));
    let in_rms: f32 = audio.iter().map(|v| v * v).sum::<f32>() / audio.len() as f32;
    let out_rms: f32 = enhanced.iter().map(|v| v * v).sum::<f32>() / enhanced.len() as f32;
    eprintln!("input rms {in_rms} output rms {out_rms}");
    assert!(
        out_rms < in_rms * 0.8,
        "expected noise suppression, rms {in_rms} -> {out_rms}"
    );
}
