//! Fixture parity tests for the DialogueSidon port.
//!
//! Fixtures live in `testdata/dialogue_sidon/`, regenerated by
//! `tools/gen_dialogue_sidon_fixtures.py` against the pinned mlx-audio
//! commit. Tests never download.

use std::path::{Path, PathBuf};

use super::{DialogueSidon, DpmSolver, SidonConfig};
use turbospark_model_io::safetensors::SafetensorsFile;

fn testdata(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata/dialogue_sidon")
        .join(name)
}

fn read_json(name: &str) -> serde_json::Value {
    let text = std::fs::read_to_string(testdata(name)).expect(name);
    serde_json::from_str(&text).expect(name)
}

fn read_npy(name: &str) -> (Vec<usize>, Vec<f32>) {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    let data = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (shape, data)
}

fn max_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(
        a.len(),
        b.len(),
        "length mismatch {} vs {}",
        a.len(),
        b.len()
    );
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
}

fn load_model() -> DialogueSidon {
    let config = SidonConfig::from_json(&read_json("config.json")).unwrap();
    let file = SafetensorsFile::open(&testdata("tiny_weights.safetensors")).expect("weights");
    let dac_config =
        crate::codec::descript::DacConfig::from_json(&read_json("tiny_dac_config.json")).unwrap();
    let dac = SafetensorsFile::open(&testdata("tiny_dac.safetensors")).expect("dac");
    DialogueSidon::load(config, &file, dac_config, &dac).unwrap()
}

#[test]
fn config_parses() {
    let config = SidonConfig::from_json(&read_json("config.json")).unwrap();
    assert_eq!(config.latent_dim, 4);
    assert_eq!(config.encoder.num_hidden_layers, 2);
    assert_eq!(config.encoder.hidden_size, 32);
    assert_eq!(config.diffusion.num_layers, 2);
    assert_eq!(config.decoder_rates, vec![2, 3]);
    assert!(!config.latent_norm_initialized);
}

#[test]
fn frontend_matches_reference() {
    let model = load_model();
    let (_, wave) = read_npy("wave.npy");
    let normed = model.normalize_chunk(&wave);
    let (features, mask) = model.extract_features(&normed).unwrap();
    let (fshape, golden) = read_npy("features.npy");
    assert_eq!(features.len(), fshape.iter().product::<usize>());
    let diff = max_diff(&features, &golden);
    eprintln!("features diff {diff}");
    assert!(diff < 5e-4, "features diff {diff}");
    let (_, golden_mask) = read_npy("mask.npy");
    let got = mask.to_vec();
    assert_eq!(got.len(), golden_mask.len());
    assert_eq!(got, golden_mask);
}

#[test]
fn encoder_matches_reference() {
    let model = load_model();
    let (fshape, features) = read_npy("features.npy");
    let (_, mask) = read_npy("mask.npy");
    let tokens = fshape[0];
    let encoded = model.encoder.forward(&features, tokens, Some(&mask));
    let (eshape, golden) = read_npy("encoder_out.npy");
    assert_eq!(encoded.len(), eshape.iter().product::<usize>());
    let diff = max_diff(&encoded, &golden);
    eprintln!("encoder diff {diff}");
    assert!(diff < 2e-3, "encoder diff {diff}");

    let first = model.linear1.run(&encoded, tokens);
    let second = model.linear2.run(&encoded, tokens);
    let (_, golden_first) = read_npy("first.npy");
    let (_, golden_second) = read_npy("second.npy");
    let diff = max_diff(&first, &golden_first);
    eprintln!("first diff {diff}");
    assert!(diff < 2e-3, "first diff {diff}");
    let diff = max_diff(&second, &golden_second);
    eprintln!("second diff {diff}");
    assert!(diff < 2e-3, "second diff {diff}");
}

#[test]
fn conditioning_matches_reference() {
    let model = load_model();
    let (fshape, features) = read_npy("features.npy");
    let (_, mask) = read_npy("mask.npy");
    let tokens = fshape[0];
    let cond = model.conditioning(&features, tokens, &mask);
    let (cshape, golden) = read_npy("conditioning.npy");
    assert_eq!(cond.len(), cshape.iter().product::<usize>());
    let diff = max_diff(&cond, &golden);
    eprintln!("conditioning diff {diff}");
    assert!(diff < 3e-3, "conditioning diff {diff}");
}

#[test]
fn diffusion_head_matches_reference() {
    let model = load_model();
    let (cshape, conditioning) = read_npy("conditioning.npy");
    let (_, noise) = read_npy("noise.npy");
    let frames = cshape[0];
    let prediction = model
        .diffusion_head
        .forward(&noise, frames, 500.0, &conditioning);
    let (_, golden) = read_npy("prediction.npy");
    let diff = max_diff(&prediction, &golden);
    eprintln!("prediction diff {diff}");
    assert!(diff < 1e-2, "prediction diff {diff}");
}

#[test]
fn dpm_solver_matches_reference() {
    let config = SidonConfig::from_json(&read_json("config.json")).unwrap();
    let mut solver = DpmSolver::new(&config.diffusion, 8).unwrap();
    assert_eq!(solver.timesteps.len(), 8);
    assert_eq!(solver.timesteps[0], 999);
    let (_, noise) = read_npy("noise.npy");
    let (cshape, conditioning) = read_npy("conditioning.npy");
    let frames = cshape[0];
    let mut latents = noise.clone();
    for &t in &solver.timesteps.clone() {
        let prediction = model()
            .diffusion_head
            .forward(&latents, frames, t as f32, &conditioning);
        latents = solver.step(&prediction, &latents).unwrap();
    }
    let (_, golden) = read_npy("latents.npy");
    let diff = max_diff(&latents, &golden);
    eprintln!("latents diff {diff}");
    assert!(diff < 1e-2, "latents diff {diff}");
}

fn model() -> DialogueSidon {
    load_model()
}

#[test]
fn decoded_speakers_match_reference() {
    let model = load_model();
    let (_, latents) = read_npy("latents.npy");
    let (lshape, _) = read_npy("latents.npy");
    let frames = lshape[0];
    let speakers = model.decode_latents(&latents, frames).unwrap();
    let (sshape, golden) = read_npy("speakers.npy");
    assert_eq!(speakers.len(), sshape.iter().product::<usize>());
    let peak = golden.iter().fold(0.0f32, |a, &v| a.max(v.abs())).max(1e-6);
    let diff = max_diff(&speakers, &golden);
    eprintln!("speakers diff {diff} peak {peak}");
    assert!(diff < 5e-2, "speakers diff {diff} peak {peak}");
    assert!(speakers.iter().all(|v| v.is_finite()));
}
