//! 2-bit affine groupwise quantization reference (MLX `affine` layout at
//! `bits = 2`, the `prism-ml/Ternary-Bonsai-27B-mlx-2bit` layout).
//!
//! A separate module from [`crate::quant_1bit`] for the reason that one is
//! separate from `quant.rs`: it is not the same layout at a different width.
//! The CONTAINER is shared -- a packed plane beside per-group `scales` and
//! `biases`, `w = q * scale + bias` -- and everything below it differs:
//!
//! - **Four elements per byte, not eight**, so the field ORDER inside a byte
//!   is two bits wide and a wrong order is a permutation within a run of
//!   four rather than of eight.
//! - **`q` runs over `{0, 1, 2, 3}`**, so unlike the 1-bit case there is no
//!   sign-flip shortcut and the quant is a genuine index.
//! - **The checkpoint's grid is TERNARY.** See below; it is measured here,
//!   not assumed.
//!
//! It shares [`crate::quant_1bit`]'s two structural properties, and both are
//! worth restating because they are what the INT4/INT8 sibling gets wrong:
//! the group size is a PARAMETER (this checkpoint groups by 128 where
//! `quant.rs` pins 64), and the companions are FP16 rather than BF16 (the
//! two are the same width and share no exponent field, so a misread is
//! undetectable by any length check).
//!
//! **THE CONVENTION BELOW WAS MEASURED, NOT READ OFF A FORMAT DOC.**
//! `crates/compute/tests/quant_2bit.rs` carries the oracle: 64 packed bytes
//! and their two FP16 companion pairs, lifted by ranged read out of the real
//! `model.safetensors`, against the 256 floats MLX's own `mx.dequantize`
//! produces from them. The LSB-first field order is exact on all 245,760
//! elements of the probed tensor. Regenerate with
//! `scripts/mlx_2bit_oracle.py`.
//!
//! # Layout
//!
//! One row of `n` weights, `n` a multiple of the group size:
//!
//! - `packed`: `n / 4` bytes. Element `i` is the two-bit field at bit
//!   `2 * (i % 4)` of byte `i / 4`, least significant field first. MLX stores
//!   the same run as `n / 16` little-endian `u32` words; because a byte holds
//!   a whole number of fields, the byte view is identical and carries no
//!   endianness assumption, which is why it is the one used here.
//! - `scales` / `biases`: one FP16 bit pattern each per group.
//!
//! An element decodes as `w = q * scale + bias` with `q` in `{0, 1, 2, 3}`.
//!
//! # The ternary grid is a property of the checkpoint, not of the format
//!
//! Every group of the probed tensor has `bias == -scale` exactly, and no
//! element anywhere in it decodes at `q == 3` (the level histogram over
//! 245,760 elements is `{0: 93895, 1: 57398, 2: 94467}`). So the three levels
//! in use are `-scale`, `0` and `+scale`: a ternary grid carried in a 2-bit
//! affine word, which is what "1.58 bits" names -- an information measure,
//! `log2(3)`, rather than a container.
//!
//! **NOTE the roadmap predicted `{-s, 0, +s}` with a ZERO bias and that is
//! wrong**; `q = 0` has to reach `-s`, so the bias is `-s` and the zero is
//! the middle level.
//!
//! Neither property is assumed anywhere in this module. The container
//! permits any `(scale, bias)` pair and all four levels, nothing in the file
//! declares otherwise, and a decoder that baked either in would produce
//! plausible wrong weights on a checkpoint that used the fourth level.
//! [`is_ternary_symmetric`] and [`uses_fourth_level`] MEASURE them instead,
//! which is [`crate::quant_1bit::is_symmetric`]'s precedent.
//!
//! # There is no `+/-1`-style fast path here, deliberately
//!
//! At one bit, `bias == -scale/2` lets a GEMV accumulate `+/-x` and apply the
//! scale once per group. The ternary analogue would accumulate
//! `sum over q != 1 of sign * x`, and it has the same defect the 1-bit one
//! turned out to have: it reassociates the sum (AGENTS.md Gotcha 27), so
//! selecting it per tensor at dispatch time would make generated bytes a
//! function of which tensors happened to quantize symmetrically. The 1-bit
//! fast path is reachable from no decode flow for exactly that reason, and a
//! second dead kernel is not worth having.

/// Widen an FP16 bit pattern to `f32`, and narrow one back.
///
/// Re-exported from [`crate::quant_1bit`] rather than restated: the companion
/// dtype is the same at both widths, and two copies of a binary16 conversion
/// are two chances to hand-roll one (AGENTS.md Gotcha 3).
pub use crate::quant_1bit::{f16_to_f32, f32_to_f16};

/// The group size the real ternary checkpoint declares
/// (`config.json`: `quantization.group_size`).
///
/// Not a constant of the format, and not this module's business to enforce.
/// Pass the checkpoint's own value; this exists so a caller writing a fixture
/// does not invent one. It is the same 128 the 1-bit checkpoint uses, which
/// is a fact about one publisher rather than about two bits.
pub const TERNARY_GROUP_SIZE: usize = 128;

/// Elements packed into one byte at two bits each.
pub const INT2_ELEMENTS_PER_BYTE: usize = 4;

/// One row of 2-bit-affine packed weights: `n / 4` bytes, plus one FP16 scale
/// and one FP16 bias per group.
///
/// `group_size` travels with the row because it is a property of the
/// checkpoint (see the module header), and a row separated from it cannot be
/// decoded.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Int2AffineRow {
    pub packed: Vec<u8>,
    pub scales: Vec<u16>,
    pub biases: Vec<u16>,
    pub group_size: usize,
}

impl Int2AffineRow {
    /// Number of weights this row decodes to.
    pub fn len(&self) -> usize {
        self.packed.len() * INT2_ELEMENTS_PER_BYTE
    }

    /// True when the row carries no weights.
    pub fn is_empty(&self) -> bool {
        self.packed.is_empty()
    }

    /// The unsigned 2-bit quant at element `i`, least significant field
    /// first.
    #[inline]
    pub fn quant(&self, i: usize) -> u8 {
        (self.packed[i / 4] >> (2 * (i % 4))) & 3
    }
}

/// Checks the `bias == -scale` relationship group by group, on the decoded
/// FP16 values rather than on the bit patterns.
///
/// Returns the number of groups that are NOT symmetric, so `0` means the row
/// sits on a `{-s, 0, +s, +2s}` grid whose middle level is exactly zero. The
/// comparison is exact: negation is exact in FP16 whatever the value, so a
/// tolerance here would hide a genuinely asymmetric group rather than absorb
/// rounding.
pub fn asymmetric_group_count_int2(row: &Int2AffineRow) -> usize {
    row.scales
        .iter()
        .zip(row.biases.iter())
        .filter(|(&s, &b)| f16_to_f32(b) != -f16_to_f32(s))
        .count()
}

/// True when every group of the row satisfies `bias == -scale`.
///
/// That alone does NOT make the row ternary: it says levels 0, 1 and 2 land
/// on `-s`, `0` and `+s`, and says nothing about whether level 3 (`+2s`) is
/// used. Pair it with [`uses_fourth_level`] before calling a row ternary.
pub fn is_ternary_symmetric(row: &Int2AffineRow) -> bool {
    asymmetric_group_count_int2(row) == 0
}

/// True when any element of the row decodes at `q == 3`.
///
/// Reported, never acted on. The real checkpoint never uses the fourth level,
/// which is what makes it ternary rather than merely 2-bit, but that is a
/// property of the QAT recipe and this module refuses to depend on it.
pub fn uses_fourth_level(row: &Int2AffineRow) -> bool {
    (0..row.len()).any(|i| row.quant(i) == 3)
}

fn check_shape(n: usize, group_size: usize) {
    assert!(group_size > 0, "group size must be positive");
    assert!(
        group_size % INT2_ELEMENTS_PER_BYTE == 0,
        "group size {group_size} is not a whole number of bytes"
    );
    assert!(
        n % group_size == 0,
        "row length {n} is not a multiple of the group size {group_size}"
    );
}

/// Ternary 2-bit affine quantize: `q in {0, 1, 2}`, `w ~= q * scale + bias`
/// with `bias = -scale`, so the three representable values are `-scale`, `0`
/// and `+scale`. The fourth level is left unused, as the real checkpoint
/// leaves it.
///
/// **This is not the min/max affine rule the INT4 and INT8 quantizers use,
/// for [`crate::quant_1bit::quantize_int1_affine_symmetric`]'s reason.** At
/// four bits, `scale = (max - min) / 15` with `bias = min` spends its
/// endpoints on the group's extremes and its interior levels on everything
/// between. At two bits over a symmetric distribution the interior is one
/// level, so the min/max rule would place `0` off-centre and quantize a
/// zero-mean group to a lopsided grid. It would also not reproduce the
/// convention the real QAT checkpoint uses, so a fixture built with it would
/// exercise a layout no file has.
///
/// The threshold is the standard ternary one: `scale = 0.7 * mean(|w|)`
/// rounded through FP16, and an element is `+/-1` when `|w| > scale / 2`.
/// A group of all zeros gets a zero scale and decodes back to zeros.
pub fn quantize_int2_affine_ternary(row: &[f32], group_size: usize) -> Int2AffineRow {
    check_shape(row.len(), group_size);
    let n_groups = row.len() / group_size;
    let mut packed = vec![0u8; row.len() / INT2_ELEMENTS_PER_BYTE];
    let mut scales = vec![0u16; n_groups];
    let mut biases = vec![0u16; n_groups];

    for g in 0..n_groups {
        let group = &row[g * group_size..(g + 1) * group_size];
        let mean_abs = group.iter().map(|w| w.abs()).sum::<f32>() / group_size as f32;
        let s_bits = f32_to_f16(0.7 * mean_abs);
        let scale = f16_to_f32(s_bits);
        // Stored rather than derived on decode: the file carries an
        // independent bias plane and this module refuses to assume the two
        // are related (see the module header).
        let b_bits = f32_to_f16(-scale);
        scales[g] = s_bits;
        biases[g] = b_bits;

        for (k, &w) in group.iter().enumerate() {
            // Level 1 is the zero; 0 and 2 are `-scale` and `+scale`.
            let level: u8 = if scale == 0.0 || w.abs() <= scale / 2.0 {
                1
            } else if w > 0.0 {
                2
            } else {
                0
            };
            let i = g * group_size + k;
            packed[i / 4] |= level << (2 * (i % 4));
        }
    }

    Int2AffineRow {
        packed,
        scales,
        biases,
        group_size,
    }
}

/// Dequantize an [`Int2AffineRow`] to `n` FP32 elements.
pub fn dequantize_int2_affine(r: &Int2AffineRow, n: usize) -> Vec<f32> {
    assert_eq!(n, r.len(), "n must equal packed.len() * 4");
    check_shape(n, r.group_size);
    let mut out = vec![0f32; n];
    for g in 0..n / r.group_size {
        let scale = f16_to_f32(r.scales[g]);
        let bias = f16_to_f32(r.biases[g]);
        for k in 0..r.group_size {
            let i = g * r.group_size + k;
            out[i] = r.quant(i) as f32 * scale + bias;
        }
    }
    out
}

/// FP32 reference for the 2-bit-affine embedding lookup: one row of a
/// `[V, D]` table, dequantized and scaled by `out_scale` (Gemma's
/// `sqrt(hidden)` post-embedding scale, or `1.0` for a raw dequant).
///
/// The sibling of [`crate::quant_1bit::embed_lookup_int1`], and it exists for
/// the same reason: the real checkpoint QUANTIZES ITS EMBEDDING TABLE, which
/// was read off the safetensors header rather than assumed
/// (`language_model.model.embed_tokens.weight` is `U32 [248320, 320]`, i.e.
/// 320 packed words is 5120 elements, the hidden size). The head is another
/// matrix through the resident GEMV; the table is not. So 2-bit's footing is
/// a GEMV plus a lookup and NO routed-expert pair -- AGENTS.md Gotcha 29's
/// per-type rule as the one real file decides it, the model being dense.
///
/// Note the bound checks cover the SCALE plane as well as the packed one: at
/// two bits a row is four times shorter than at eight, so a `token_id` that
/// walks off the end of one plane can still be inside the other.
pub fn embed_lookup_int2(
    table_packed: &[u8],
    table_scales: &[u16],
    table_biases: &[u16],
    token_id: usize,
    d: usize,
    group_size: usize,
    out_scale: f32,
) -> Vec<f32> {
    check_shape(d, group_size);
    let groups_per_row = d / group_size;
    let row_bytes = d / INT2_ELEMENTS_PER_BYTE;
    let pack_base = token_id * row_bytes;
    let scale_base = token_id * groups_per_row;
    assert!(
        pack_base + row_bytes <= table_packed.len(),
        "token out of range"
    );
    assert!(
        scale_base + groups_per_row <= table_scales.len(),
        "scales out of range"
    );
    assert!(
        scale_base + groups_per_row <= table_biases.len(),
        "biases out of range"
    );

    let mut out = vec![0f32; d];
    for (i, out_val) in out.iter_mut().enumerate() {
        let byte = table_packed[pack_base + (i / 4)];
        let q = (byte >> (2 * (i % 4))) & 3;
        let g = i / group_size;
        let scale = f16_to_f32(table_scales[scale_base + g]);
        let bias = f16_to_f32(table_biases[scale_base + g]);
        *out_val = (q as f32 * scale + bias) * out_scale;
    }
    out
}

/// Dequantize-and-multiply reference GEMV: `out[row] = sum_i w[row][i] * x[i]`.
///
/// Accumulates in FP32 in element order, which is the order a per-row GPU
/// kernel's lane partials have to be reduced in to match. Mirrors
/// [`crate::quant_1bit::dequant_int1_gemv`].
pub fn dequant_int2_gemv(weight_rows: &[Int2AffineRow], x: &[f32], n: usize) -> Vec<f32> {
    assert_eq!(x.len(), n, "x.len() must equal n");
    let mut out = vec![0f32; weight_rows.len()];
    for (r, row) in weight_rows.iter().enumerate() {
        let w = dequantize_int2_affine(row, n);
        out[r] = w.iter().zip(x.iter()).map(|(a, b)| a * b).sum();
    }
    out
}
