//! Fixture parity tests for the ECAPA-TDNN port.
//!
//! Fixtures live in `testdata/ecapa_tdnn/`, regenerated by
//! `tools/gen_ecapa_fixtures.py` against the pinned mlx-audio commit.
//! Both the plain and global-context pooling variants are gated end to
//! end on the reference embedding vectors.

use std::path::{Path, PathBuf};

use super::{EcapaTdnn, EcapaTdnnConfig};
use turbospark_model_io::safetensors::SafetensorsFile;

fn testdata(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata/ecapa_tdnn")
        .join(name)
}

fn read_json(name: &str) -> serde_json::Value {
    let text = std::fs::read_to_string(testdata(name)).expect(name);
    serde_json::from_str(&text).expect(name)
}

fn read_npy(name: &str) -> (Vec<usize>, Vec<f32>) {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    let data = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (shape, data)
}

fn floats(value: &serde_json::Value) -> Vec<f32> {
    value
        .as_array()
        .expect("float array")
        .iter()
        .map(|v| v.as_f64().expect("f64") as f32)
        .collect()
}

fn max_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(
        a.len(),
        b.len(),
        "length mismatch: {} vs {}",
        a.len(),
        b.len()
    );
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
}

fn load_tiny(tag: &str) -> EcapaTdnn {
    let config = read_json(&format!("tiny_{tag}_config.json"));
    let config = EcapaTdnnConfig::from_json(&config).expect("config parses");
    let file = SafetensorsFile::open(&testdata(&format!("tiny_{tag}_weights.safetensors")))
        .expect("weights open");
    EcapaTdnn::load(config, &file).expect("load")
}

#[test]
fn config_defaults_match_reference() {
    let config = EcapaTdnnConfig::from_json(&serde_json::json!({})).unwrap();
    assert_eq!(config.input_size, 60);
    assert_eq!(config.channels, 1024);
    assert_eq!(config.embed_dim, 256);
    assert_eq!(config.kernel_sizes, vec![5, 3, 3, 3, 1]);
    assert_eq!(config.dilations, vec![1, 2, 3, 4, 1]);
    assert_eq!(config.attention_channels, 128);
    assert_eq!(config.res2net_scale, 8);
    assert_eq!(config.se_channels, 128);
    assert!(!config.global_context);
}

#[test]
fn tiny_end_to_end_matches_reference() {
    for tag in ["gc0", "gc1"] {
        let model = load_tiny(tag);
        let traces = read_json("traces.json");
        for case in ["a", "b"] {
            let (shape, feats) = read_npy(&format!("{tag}_{case}_feats.npy"));
            // (1, T, C) channels-last -> [C, T]
            let t = shape[1];
            let c = shape[2];
            assert_eq!(c, model.config.input_size);
            let mut x = vec![0.0f32; c * t];
            for ti in 0..t {
                for ci in 0..c {
                    x[ci * t + ti] = feats[ti * c + ci];
                }
            }
            let embed = model.forward(&x, t).unwrap();
            let golden = floats(&traces[format!("{tag}_{case}_embed").as_str()]);
            assert_eq!(embed.len(), golden.len());
            assert!(
                max_diff(&embed, &golden) < 1e-4,
                "{tag}/{case} embed diff {}",
                max_diff(&embed, &golden)
            );
        }
    }
}
