//! Fixture parity tests for the Fish S1 DAC port.
//!
//! Fixtures live in `testdata/fish_s1_dac/`, regenerated by
//! `tools/gen_fish_s1_dac_fixtures.py` against the pinned mlx-audio
//! commit (tiny mirrored geometry of `build_ae()`; the transformers'
//! `freqs_cis` and causal masks stay at their true init values and are
//! recomputed, never loaded). Gates: encode codes per book and the
//! decoded waveforms, plus a random-codes decode. A real checkpoint
//! directory can be pointed at via TURBOSPARK_FISH_S1_DAC_MODEL and is
//! skipped when absent. Tests never download.

use std::path::{Path, PathBuf};

use super::{FishS1Dac, FishS1DacConfig};
use turbospark_model_io::safetensors::SafetensorsFile;

fn testdata(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("testdata/fish_s1_dac")
        .join(name)
}

fn read_json(name: &str) -> serde_json::Value {
    let text = std::fs::read_to_string(testdata(name)).expect(name);
    serde_json::from_str(&text).expect(name)
}

fn read_npy(name: &str) -> (Vec<usize>, Vec<f32>) {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    let data = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (shape, data)
}

/// Codes arrive as int32 npy, rows are books.
fn read_codes(name: &str) -> Vec<Vec<i32>> {
    let bytes = std::fs::read(testdata(name)).expect(name);
    assert_eq!(&bytes[..6], b"\x93NUMPY");
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let header = std::str::from_utf8(&bytes[10..10 + header_len]).unwrap();
    assert!(header.contains("<i4"), "{name} must be int32");
    let start = header.find('(').unwrap() + 1;
    let end = header[start..].find(')').unwrap() + start;
    let shape: Vec<usize> = header[start..end]
        .split(',')
        .filter_map(|p| p.trim().parse::<usize>().ok())
        .collect();
    assert_eq!(shape.len(), 2, "{name} must be [books, T]");
    let (books, frames) = (shape[0], shape[1]);
    let data: Vec<i32> = bytes[10 + header_len..]
        .chunks_exact(4)
        .map(|c| i32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    (0..books)
        .map(|b| data[b * frames..(b + 1) * frames].to_vec())
        .collect()
}

fn rel_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(a.len(), b.len());
    let max = b.iter().fold(0.0f32, |acc, v| acc.max(v.abs()));
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
        / max
}

fn load_tiny() -> FishS1Dac {
    let config = read_json("tiny_config.json");
    let config = FishS1DacConfig::from_json(&config).expect("config");
    let file = SafetensorsFile::open(&testdata("tiny_weights.safetensors")).expect("weights");
    FishS1Dac::load(config, &file).expect("load")
}

#[test]
fn config_defaults_match_build_ae() {
    let config = FishS1DacConfig::build_ae();
    assert_eq!(config.sample_rate, 44_100);
    assert_eq!(config.encoder_dim, 64);
    assert_eq!(config.encoder_rates, vec![2, 4, 8, 8]);
    assert_eq!(config.latent_dim, 1024);
    assert_eq!(config.decoder_dim, 1536);
    assert_eq!(config.decoder_rates, vec![8, 8, 4, 2]);
    assert_eq!(config.encoder_transformer_layers, vec![0, 0, 0, 4]);
    assert_eq!(config.hop_length(), 512);
    assert_eq!(config.frame_length(), 2048);
    assert_eq!(config.quantizer.n_codebooks, 9);
    assert_eq!(config.quantizer.semantic_codebook_size, 4096);
    assert_eq!(config.quantizer.codebook_size, 1024);
    assert_eq!(config.quantizer.codebook_dim, 8);
    assert_eq!(config.quantizer.downsample_factor, vec![2, 2]);
    assert_eq!(config.total_books(), 10);
    // The pre/post transformer windows come from build_ae.
    assert_eq!(config.quantizer.pre.window_size, 128);
    assert_eq!(config.quantizer.pre.n_head, 16);
}

#[test]
fn encode_decode_matches_reference() {
    let model = load_tiny();
    let traces = read_json("traces.json");
    for tag in ["a", "b"] {
        let (_, wave) = read_npy(&format!("{tag}_wave.npy"));
        let (codes, code_len) = model.encode(&wave).unwrap();
        let golden = read_codes(&format!("{tag}_codes.npy"));
        assert_eq!(codes.len(), golden.len(), "tag {tag} book count");
        for (b, (mine, gold)) in codes.iter().zip(&golden).enumerate() {
            assert_eq!(mine, gold, "tag {tag} book {b}");
        }
        assert_eq!(
            code_len as i64,
            traces[format!("{tag}_codes_shape").as_str()]
                .as_array()
                .unwrap()[1]
                .as_i64()
                .unwrap()
        );
        let (_, golden_wave) = read_npy(&format!("{tag}_decoded.npy"));
        let audio = model.decode(&codes).unwrap();
        assert_eq!(audio.len(), golden_wave.len());
        // The tiny stack amplifies; relative gate as in the sibling
        // fixture families.
        let rel = rel_diff(&audio, &golden_wave);
        assert!(rel < 1e-3, "tag {tag} decoded rel diff {rel}");
        assert_eq!(
            audio.len(),
            code_len * model.config.frame_length(),
            "tag {tag} length"
        );
    }
}

#[test]
fn random_codes_decode_matches_reference() {
    let model = load_tiny();
    let codes = read_codes("rand_codes.npy");
    let (_, golden) = read_npy("rand_decoded.npy");
    let audio = model.decode(&codes).unwrap();
    assert_eq!(audio.len(), golden.len());
    let rel = rel_diff(&audio, &golden);
    assert!(rel < 1e-3, "rand decode rel diff {rel}");
}

#[test]
fn decode_validates_books() {
    let model = load_tiny();
    let too_few = vec![vec![0i32; 2]];
    assert!(model.decode(&too_few).is_err());
    // Out-of-range semantic code (16-entry book).
    let mut bad = read_codes("rand_codes.npy");
    bad[0][0] = 99;
    assert!(model.decode(&bad).is_err());
}

/// Real-checkpoint gate; opt-in via TURBOSPARK_FISH_S1_DAC_MODEL
/// pointing at a directory with model.safetensors (config.json
/// optional; geometry defaults to build_ae). Skips when unset.
#[test]
fn real_checkpoint_gate() {
    let Ok(dir) = std::env::var("TURBOSPARK_FISH_S1_DAC_MODEL") else {
        eprintln!("skipping: TURBOSPARK_FISH_S1_DAC_MODEL not set");
        return;
    };
    let model = FishS1Dac::open(Path::new(&dir)).unwrap();
    let n = model.config.frame_length() * 2;
    let wave: Vec<f32> = (0..n)
        .map(|i| ((i as f32) * 220.0 * std::f32::consts::TAU / 44_100.0).sin() * 0.2)
        .collect();
    let (codes, code_len) = model.encode(&wave).unwrap();
    assert_eq!(code_len, 2);
    assert_eq!(codes.len(), model.config.total_books());
    let audio = model.decode(&codes).unwrap();
    assert_eq!(audio.len(), n);
    assert!(audio.iter().all(|v| v.is_finite()));
}
