//! `mference-server`: binds the OpenAI-compatible Chat Completions router to
//! loopback. Takes a tokenizer sidecar directory since no real `.gturbo`
//! model loading exists yet (see `mrefrust_server`'s crate docs); every
//! response is generated by `ScriptedChatModel`, a fixed placeholder
//! sequence, not a real forward pass.
//!
//! Usage: `mference-server <tokenizer-dir> [port]` (default port 8080).
//! Optional tailnet bind (vs. loopback-only) is not implemented.

use std::path::PathBuf;
use std::sync::Arc;

use tokenizer::MfTokenizer;

#[tokio::main]
async fn main() -> std::process::ExitCode {
    let mut args = std::env::args().skip(1);
    let Some(tokenizer_dir) = args.next() else {
        eprintln!("usage: mference-server <tokenizer-dir> [port]");
        return std::process::ExitCode::from(2);
    };
    let port: u16 = args.next().and_then(|p| p.parse().ok()).unwrap_or(8080);

    let tok = match MfTokenizer::load_from_dir(&PathBuf::from(tokenizer_dir)) {
        Ok(t) => t,
        Err(e) => {
            eprintln!("failed to load tokenizer: {e}");
            return std::process::ExitCode::from(1);
        }
    };
    let model: Arc<dyn mrefrust_server::ChatModel> = Arc::new(
        mrefrust_server::ScriptedChatModel::new(tok, 4096, Vec::new()),
    );
    let router = mrefrust_server::build_router(model);

    let addr = format!("127.0.0.1:{port}");
    let listener = match tokio::net::TcpListener::bind(&addr).await {
        Ok(l) => l,
        Err(e) => {
            eprintln!("failed to bind {addr}: {e}");
            return std::process::ExitCode::from(1);
        }
    };
    eprintln!("mference-server listening on http://{addr}/v1/chat/completions");
    if let Err(e) = axum::serve(listener, router).await {
        eprintln!("server error: {e}");
        return std::process::ExitCode::from(1);
    }
    std::process::ExitCode::SUCCESS
}
